import type { Interpretation } from "./types";

export const JUPITER_IN_HOUSE: Interpretation[] = [
  {
    title: "Jupiter in the 1st House",
    body: "You take up room, and the room is usually glad. Jupiter in the house of the self expands whatever you are: your laugh carries, your appetite for life is visible from across the street, and strangers hand you opportunities partly because you look like someone already mid-story. This is not luck exactly — it is the way **openness attracts openings**. Your body, however it is shaped, wants to move through the world at full stride rather than apologize its way down the hallway.\n\nThe practice is discernment inside the abundance. You can say yes faster than you can follow through, and promising is more fun than delivering. Choose the growth that actually feeds you, not just the growth that flatters you. And keep this permission close: **taking up space is not a flaw to manage**. It is the assignment. The people who need bigness modeled are watching you do it kindly."
  },
  {
    title: "Jupiter in the 2nd House",
    body: "Money and material life carry a strange buoyancy for you. Resources arrive through generosity, reputation, teaching, or simply the trust you inspire — and they tend to return after they leave, which teaches you early that **scarcity is a story, not a law**. You are the person who feeds people, funds the thing, covers the difference, often before checking the balance. Your relationship to what you own is warm rather than white-knuckled.\n\nThe growth edge is defining enough, because Jupiter never will. Expansion for its own sake becomes clutter, debt, or a bigger version of a life you did not choose. Build your material world around **what you actually value** — values live in the second house too. When your spending, your giving, and your convictions all point the same direction, this placement stops being lucky and starts being wealthy in the older sense: enough, plus some to share."
  },
  {
    title: "Jupiter in the 3rd House",
    body: "Your mind is a wide road with generous shoulders. Curiosity here is almost athletic: you collect ideas, languages, half-read books, long conversations with neighbors, the whole texture of the everyday. Learning is not preparation for your life — it is one of the main **pleasures your life is made of**. Siblings, cousins, and the people three doors down often turn out to be teachers in disguise, and your words tend to open doors that credentials never touched.\n\nThe friction is depth. A mind this quick can skim forever, sampling every subject and marrying none. So the practice is to let one question hold you long enough to change you — study something until it **rearranges how you see**, not just what you can mention. And notice the quiet ministry available here: your encouragement, delivered in passing, in a text, in the hallway, has moved people further than you know."
  },
  {
    title: "Jupiter in the 4th House",
    body: "Home is where your abundance concentrates. Whatever your first household looked like — and it may have been complicated — you carry an instinct for making shelter feel bigger than its square footage: food on the stove, doors that open, room at the table for one more. For many people with this placement, the deepest expression is **chosen family**: the kin you gather on purpose, who make belonging a practice rather than an accident of birth.\n\nThe invitation is to treat your roots as a living resource, not a museum. Tend the rituals that make a place yours. Learn the histories you come from, including the ones that were hidden from you, because Jupiter here often finds **inheritance where others saw only silence**. When you build a home generous enough to hold your whole self, it becomes the ground other people stand on too. That is not a small legacy. It may be the one."
  },
  {
    title: "Jupiter in the 5th House",
    body: "Play is not the break from your purpose; play is load-bearing. Jupiter here pours abundance into whatever you make for the joy of making it — art, romance, games, the young people in your life whether or not you raise any, the Saturday spent on something gloriously unnecessary. Your creations get luckier the less you apologize for them, and **delight is your most reliable compass**: what you make while grinning travels further than what you make while proving.\n\nThe growth edge is risk. Pleasure this available can stay safe, circling the same familiar joys, when Jupiter is asking you to bet bigger on your own gladness — share the work, say the flirtation out loud, take the stage. And hold this permission: **joy is not frivolous in a hard world**. It is evidence. Every time you create openly, you demonstrate that a life can be enjoyed on purpose, and somebody watching needed that proof."
  },
  {
    title: "Jupiter in the 6th House",
    body: "You find meaning in maintenance, which is rarer than it sounds. The daily round — work, chores, the body's care, the small repeated acts that keep a life running — is where your growth actually compounds. Colleagues experience you as the generous one: the mentor, the fixer, the person who says yes before the sentence is finished. Service is genuinely your gladness, and **useful is one of your love languages**.\n\nThe friction is volume. Jupiter enlarges whatever it touches, and in the house of work and health it can enlarge the calendar until the body files a complaint. Your growth edge is learning that service is richest when it is **chosen, portioned, and occasionally declined** — a no on Tuesday is what keeps the yes on Thursday honest. Treat your own body as the first colleague you serve. The rituals you build for your own care become, quietly, the most persuasive thing you teach."
  },
  {
    title: "Jupiter in the 7th House",
    body: "Partnership is your classroom, and you have a gift for enrolling with teachers. The people you commit to — lovers, business partners, the friend who is functionally family — tend to widen your world: they open doors, hand you philosophies, arrive from somewhere far from your starting point. You grow **through the mirror of another**, and you offer the same enlargement back; being loved by you tends to make people more themselves, not less.\n\nThe edge is idealization. Jupiter can gild the mirror, and you may keep relating to someone's potential long after the person has clarified who they are. Let your partners be **human-sized and specific** — flawed, changing, real — and the luck between you multiplies instead of evaporating on contact. Whatever shape your commitments take, and they need not match anyone's template, choose people who are also curious. Growth is the one thing you cannot partner without."
  },
  {
    title: "Jupiter in the 8th House",
    body: "You grow in the places most people avoid. Intimacy, shared money, grief, the truths that only surface after midnight — these depths feed you rather than drain you, and others can sense it. People hand you their heaviest things because something in you communicates that **the dark is survivable**. Inheritance, joint resources, and other people's trust tend to move toward you across a lifetime, often at the exact junctures you need them.\n\nThe growth edge is reciprocity. You are practiced at holding; you are less practiced at being held, and Jupiter here insists that merging is meant to **enrich you too** — your grief witnessed, your debts shared, your body allowed to receive. Let someone all the way in on purpose. The permission this placement grants is enormous: you are allowed to profit, emotionally and materially, from going deep. Depth is not your sacrifice. It is your economy."
  },
  {
    title: "Jupiter in the 9th House",
    body: "Distance calls to you — sometimes as a passport, sometimes as a philosophy, sometimes as a faith you keep lovingly revising. Jupiter in the ninth is a pilgrim's placement: meaning is your native appetite, and you are most alive mid-quest, halfway through the book or the border crossing that is rearranging you. Teachers find you, and eventually **you become the teacher**, often for people the original institutions never welcomed.\n\nThe edge is certainty. A believer this gifted can settle into conclusions and start defending the map instead of walking the territory. Keep the humility clause in your creed: the horizon only keeps teaching if you keep admitting you have not arrived. And take the permission seriously — you are allowed to **build a faith that actually fits you**, assembled from every tradition that fed you and none that harmed you. A borrowed god was never the requirement. An honest search was."
  },
  {
    title: "Jupiter in the 10th House",
    body: "Your reputation wants room, and it usually gets it. Visibility comes easier to you than to most: doors at the top of the staircase seem to unlock at your knock, and mentors, promotions, and public trust arrive with a frequency your colleagues quietly notice. The tenth is the most exposed ground in a chart, and Jupiter here means **you are built to be witnessed** — your work carries further when it carries your name.\n\nThe question is never whether you will be seen but for what, because Jupiter enlarges whatever you stand on, wisdom and mistakes alike. So choose a public purpose worthy of amplification: a body of work, a cause, a standard of care. Beware the drift toward growth without direction — bigger title, hollower days. **Aim the abundance.** When your ambition serves something past yourself, this placement stops feeling like pressure and starts feeling like a commission."
  },
  {
    title: "Jupiter in the 11th House",
    body: "The old astrologers called the eleventh the place of Good Spirit, and Jupiter rejoices here — this is one of its favorite rooms in any chart. Your people are your providence: friendship, community, and shared causes carry a genuine golden thread for you, and the future you imagine tends to arrive **through introductions** — the friend of a friend, the group that adopted you. You dream in the plural, and the plural dreams back.\n\nThe practice is depth of alliance. A network this alive can stay wide and shallow, a hundred warm acquaintances doing what five true allies could — which is less than it looks. Invest in the handful who share your actual hopes. And notice the permission: for anyone who ever felt unclaimed by the family or the town they started in, this placement is a promise that **belonging can be built**, and that yours will be abundant."
  },
  {
    title: "Jupiter in the 12th House",
    body: "There is a benefactor in your chart, and it works the night shift. Jupiter in the twelfth protects from behind the scenes: the rescue you cannot explain, the stranger's kindness at the exact ledge, the soft landing that keeps not making sense. Solitude genuinely feeds you — retreat, prayer, sleep, the hour before anyone else wakes — and your compassion extends furthest toward **the hidden and the written-off**, because some part of you has lived there.\n\nThe growth edge is trust. Grace that arrives invisibly is easy to discount, and you may keep trying to earn what is already given, performing worthiness for an audience that never asked. The practice is rest: deliberately, unproductively, as an act of faith. Let yourself be **carried sometimes**. This placement's deepest teaching is that you were never as alone as the hard years insisted, and the proof keeps arriving quietly, on schedule."
  }
];

export const SATURN_IN_HOUSE: Interpretation[] = [
  {
    title: "Saturn in the 1st House",
    body: "You met gravity early. Saturn in the house of the self often means childhood asked you to be older than your years, and you may still carry a formality you never ordered — a sense that ease must be earned before it is allowed, that your presence needs a permit. The same weight, though, builds unusual dignity. People trust your word almost on sight, and **your seriousness reads as substance** because it is.\n\nThe lifetime work is softening toward yourself without dropping the spine you built. Saturn here matures beautifully: the self-consciousness of your twenties becomes the self-possession of your forties, and the body you may have treated as a project becomes a home you maintain with respect. Practice being visibly imperfect on purpose, in small doses. **You do not have to audition for your own life.** The authority you were reaching for was always going to arrive; it was never going to arrive faster through self-punishment."
  },
  {
    title: "Saturn in the 2nd House",
    body: "Money is your long apprenticeship. Scarcity may have been an early teacher, or your sense of worth got tangled with earning somewhere back there, and now you double-check every foundation before standing on it. Understand what that vigilance has already built: you keep what you make, you honor debts, and people twice your age come to you for steadiness. **What you build slowly, you keep.**\n\nThe deeper work is separating net worth from self-worth, because Saturn will happily let you audit yourself forever. Your value was never the number; the number is just a tool you are learning to use without fear. Practice small, deliberate acts of material ease — the good coat, the unclenched grocery run — as evidence that **security is allowed to be enjoyed**, not only guarded. The person who survived the lean years deserves to live in the sturdy house they built, not just patrol it."
  },
  {
    title: "Saturn in the 3rd House",
    body: "You weigh your words before spending them. Maybe school felt like a locked door, or speaking up once cost too much, and your mind learned caution as a first language — the slow hand up, the sentence rehearsed twice before release. But careful thinkers become authoritative ones. When you finally speak, it lands with **the density of something tested**, and the people around you have learned to lean in.\n\nThe growth edge is giving your voice the patience you give everything else. The early verdicts about your intelligence were measurements of the classroom, not of you, and Saturn here often blooms into the late-arriving writer, the precise teacher, the one whose message settles the argument. Practice speaking at eighty percent certainty instead of one hundred. **Your thoughts do not need to be perfect to be welcome.** The world has enough fast talkers; what it is short on is people whose words can bear weight."
  },
  {
    title: "Saturn in the 4th House",
    body: "The foundations were yours to pour. Something about your early home asked you to be the adult in a room that already had adults in it, and belonging may still feel like a structure you must personally maintain — checked, braced, never quite trusted to stand on its own. Take the long view this placement always rewards: Saturn here builds **a late-blooming, deeply permanent home**, the kind you construct on purpose rather than inherit by accident.\n\nThe practice is letting your chosen ground be softer than your first one. You get to decide what family means now — blood, chosen, or both — and the household you build can run on repair instead of silence. Give yourself the private tenderness the early years rationed. **The child who held the walls up deserves to finally live inside them.** What you establish deliberately, with your own standards of care, will outlast everything you were handed."
  },
  {
    title: "Saturn in the 5th House",
    body: "Joy asks you for credentials, and you are learning to stop showing them. With Saturn in the house of play, creativity can feel high-stakes — as if art must be excellent before it is allowed, romance must be sensible, and fun must be earned by suffering first. You may have decided early that you were not the creative one. That verdict was **a fence, not a fact**.\n\nHere is what this placement builds when you push through: work with real bones. Your discipline, aimed at craft, produces things that last — the novel actually finished, the practice actually kept, the love built to weather decades. So the practice is deliberately lowering the stakes: make bad art on purpose, flirt clumsily, play badly at something weekly. **Pleasure earned this honestly runs deep**, and the joy you construct brick by brick will hold your whole weight, which the easy kind never could."
  },
  {
    title: "Saturn in the 6th House",
    body: "Your days are your masterwork. Routine, craft, and the maintenance of the body are where Saturn asks for excellence, and you likely hold standards at work that few colleagues can match — the checklist kept, the detail caught, the deadline that was never in danger. Understand the honor in this: **competence is a form of care**, and yours is the load-bearing kind that whole workplaces quietly rest on.\n\nWatch the drift toward duty without replenishment, because the body keeps honest books and files its reports as symptoms. Saturn here can turn health itself into a performance review — the punishing regimen, the rest deferred until the work is done, which it never is. The practice is structuring your recovery as seriously as your labor: rest scheduled, meals defended, the walk taken like a meeting. **You are the instrument, not just the operator.** Maintain yourself with the same devotion you spend on everything else."
  },
  {
    title: "Saturn in the 7th House",
    body: "You take promises literally, which is rarer than it should be. Partnership under Saturn matures slowly, sometimes late, always seriously — you would rather be alone than casually accompanied, and the revolving door of low-stakes connection has never interested you. When you commit, you build **the kind of bond people assume only exists in theory**: witnessed, weathered, renegotiated on purpose, still standing.\n\nThe tension is mistaking guardedness for standards. Waiting for a partner who presents zero risk means waiting forever, because real commitment is a structure two people build in weather, not a certificate of pre-approval. Notice, too, that Saturn here sometimes arrives as older partners, long timelines, or unions the paperwork was never designed for — **let your commitments take the shape that is true**, not the shape that photographs conventionally. The practice is one measured risk at a time. You are allowed to choose before you are certain."
  },
  {
    title: "Saturn in the 8th House",
    body: "Depth is a discipline for you, not a mood. Merging with another — emotionally, financially, bodily — gets weighed like a contract, and vulnerability can feel like debt you will be servicing forever. Somewhere you learned that handing yourself over was expensive, so now the vault has one key and you hold it. The gift inside the guarding: **rare integrity in the dark**. You do not gossip, leverage, or leak. People hand you their worst chapters because you have proven you can carry sealed documents.\n\nThe growth edge is letting trust be built in installments rather than demanded as a lump sum. Intimacy does not require handing over the whole vault on day one; it requires the discipline you already have, applied to opening instead of sealing. Share one weighted thing with one tested person. **What you release on purpose cannot be taken from you.** That is the eighth-house secret Saturn teaches slowest and best."
  },
  {
    title: "Saturn in the 9th House",
    body: "You refuse to believe on borrowed authority. Faith, philosophy, meaning — all of it must pass your personal inspection, which can leave whole stretches of life feeling map-less while others coast comfortably on inherited answers. If a doctrine ever used you as its cautionary tale, you know exactly why the inspection exists. **Doubt, for you, is due diligence**, not weakness.\n\nStay in the inquiry, because this placement's payoff is extraordinary: a worldview built by your own hands and tested against real weather becomes wisdom sturdy enough for other people to shelter under. Saturn here often makes the rigorous teacher, the translator between traditions, the elder whose faith survived its own demolition. The practice is patience with the unfinished cathedral — you are allowed to live inside a belief system that is still under construction. **A tested faith is worth a slow one.** Keep the scaffolding up as long as you need."
  },
  {
    title: "Saturn in the 10th House",
    body: "Saturn rules this hill, and it is training you to climb it properly. In the house of career and public standing, Saturn works from its own territory — ambition here is not optional but structural, and you have probably noticed the pattern already: shortcuts collapse under you while **the slow route holds every time**. Authority is your inheritance, claimed step by deliberate step, and the world tends to hand you responsibility early and recognition late.\n\nMake peace with the timeline. Your best chapters likely arrive after your peers have peaked, built on foundations they skipped, and they will last correspondingly longer. The practice is choosing a mountain actually worth the decades — audit your ambitions for whose approval they are secretly chasing. And note the permission: **you are allowed to become the authority**, not just answer to one. The standards you were held to become the standards you get to set, kinder and truer, for everyone climbing behind you."
  },
  {
    title: "Saturn in the 11th House",
    body: "You count friends the way jewelers count carats: few, verified, precious. Groups may have felt like exams once — the lunch table with rules nobody published, the club that tolerated rather than welcomed — and belonging can still seem conditional on usefulness, as if your membership is renewed only by what you contribute. Underneath the caution sits the real gift: **a genius for durable alliance**. Your loyalty, once given, is architectural.\n\nThe growth edge is joining anyway. The future the eleventh house governs is a group project, and your standards are meant to select your people, not exempt you from having any. Choose communities worth your seriousness — the union, the collective, the three friends who show up with tools — and then commit past the awkward phase. **Belonging is a practice, not a verdict.** Some of the most bonded circles in the world are held together by one person who decided to keep showing up. Be that one."
  },
  {
    title: "Saturn in the 12th House",
    body: "Saturn finds its joy in the twelfth house, the old texts say — which sounds grim until you understand it: this is the planet of boundaries standing guard at the border of the invisible. In practice, it can feel like a critic working from an unlit room — vague guilt, dread with no return address, burdens carried privately on principle. **Naming the fear is half the cure**; what stays anonymous stays in charge.\n\nUsed deliberately, this placement is monastic in the best sense. Solitude becomes your workshop rather than your exile: the meditation kept like a covenant, the therapy done thoroughly, the grief metabolized instead of stored. What you master in the quiet becomes **compassion with structure** — the steadiness that lets you sit with other people's darkness without drowning in it. Your work on the unseen levels is real work. It counts, even when nobody applauds, and it is holding up more than you know."
  }
];

export const URANUS_IN_HOUSE: Interpretation[] = [
  {
    title: "Uranus in the 1st House",
    body: "You never fully match the description on file, and the file was always the problem. Uranus in the house of the self makes identity a live experiment: sudden reinventions, a name or look or manner that refuses the issued categories, a nervous system tuned to lightning. People call you unpredictable, but there is a pattern — **you break molds the moment they harden**, including the ones you made yourself last year.\n\nFor anyone living outside the standard scripts, this placement is a load-bearing gift: your self was never going to be assigned; it was always going to be **authored**. The practice is making the freedom deliberate rather than reactive — rebelling toward a truer version of you, not just away from whoever tried to define you. You are the demonstration that a person can be self-invented and real at the same time. Somebody watching you exist is quietly finding their own permission."
  },
  {
    title: "Uranus in the 2nd House",
    body: "Your income has a plot-twist habit. Money arrives through unconventional channels and departs through equally strange ones — the niche skill nobody else has, the industry that did not exist five years ago, the windfall, the sudden restructure. Traditional financial advice fits you like someone else's coat, because it assumes a straight line and **your material life moves in lightning strikes**.\n\nThe invitation is to innovate on purpose instead of just weathering surprises. Build multiple streams; keep skills that travel; let your livelihood match your actual shape rather than the standard-issue one. And do the deeper renovation while you are at it — your worth was never the salary, the title, or any number a system assigned you. **You get to define what you are worth**, and the definition can be revised. Beneath the experiments, keep one boring, unshakable floor: some savings, some stability. Freedom funds itself best from a solid base."
  },
  {
    title: "Uranus in the 3rd House",
    body: "Your thoughts arrive sideways, and that is their value. This mind leaps where others walk, connecting ideas nobody else at the table would have introduced to each other — the metaphor from an unrelated field, the question that reframes the whole meeting. School may have read your pace as a problem; genuine curiosity never has. **The angle no one else has is precisely your usefulness.**\n\nThe practice is saying the strange thing out loud, early, before you have sanded it down to fit the room. Your first draft of an idea is often the valuable one. Watch the scattered edge — a mind this electric can open forty tabs and finish none — so pair the lightning with one or two grounding rituals: the notebook, the walk, the single project protected from your own novelty. And extend patience to slower thinkers; they are not obstacles. **Translation is part of your gift**, and the future needs interpreters."
  },
  {
    title: "Uranus in the 4th House",
    body: "Home was never quite standard-issue for you — whether through moves, ruptures, an unconventional household, or a family that ran on its own operating system. Somewhere in that turbulence you learned a rare skill: **roots can be portable**. Your sense of ground travels with you, and you can assemble belonging in places that would read as unlivable to someone raised on stability.\n\nThe task now is building a base that holds without confining — belonging with the windows open. You may need a home that flexes: housemates instead of the nuclear script, a chosen family with room for reinvention, a floor plan you rearrange when your self does. All of that is legitimate. **Home is whatever reliably receives you**, and you get to draft the blueprint. When you finally design shelter on your own terms instead of recreating or rebelling against the first one, the restlessness quiets. It was never asking you to keep running. It was asking you to build differently."
  },
  {
    title: "Uranus in the 5th House",
    body: "Your creativity refuses the assignment and turns in something better. Whatever you make — art, romance, a game, a life with young people in it — carries an experimental signature that either startles its audience or liberates it, and usually both. Love, for you, needs air and novelty to survive: **attraction follows the unexpected**, and your heart has never once consulted the approved list.\n\nGive your play its full strangeness. The pressure to make normal things, love normal ways, and enjoy approved pleasures is just static; originality is not your risk, it is **your native medium**, and diluting it is the only real failure available here. The practice is finishing — electric minds start gloriously and abandon easily, so choose a few experiments worth completing. And let your joy be visible. Every time you delight in something off-script, publicly and without apology, you widen the field of what everyone watching believes is allowed."
  },
  {
    title: "Uranus in the 6th House",
    body: "The nine-to-five was not built with you in mind, and your body will tell you so before your calendar does — the mysterious fatigue in rigid jobs, the health that improves the moment the schedule loosens. Routine under Uranus needs **rhythm without rigidity**: flexible hours, work that keeps changing shape, wellness practices you essentially invented and that would embarrass a textbook.\n\nTreat your restlessness at work as data, not defect. It is a sensor reading, telling you which systems have gone dead around you — and you are usually right about which ones, which is why you make such a good reformer of workplaces, workflows, and daily life. The practice is redesigning instead of merely enduring or exploding: propose the better process, automate the soul-crushing part, build the schedule that matches your actual body. **Your daily life is allowed to be custom-built.** Health, for you, is not compliance with a regimen. It is honest architecture."
  },
  {
    title: "Uranus in the 7th House",
    body: "You partner best with people who surprise you, and you tend to find them. Relationships here resist the standard blueprint: unusual matches, unconventional arrangements, bonds that begin abruptly or refuse the ordinary sequence entirely. For anyone whose love was never going to fit the issued forms, this placement is quiet good news — **your relationships were always meant to be designed, not assigned**.\n\nThe tension is craving closeness while bolting from capture. Intimacy can start to feel like a cage the moment it becomes predictable, and you may end good things just to feel the door still opens. The practice is naming your need for space early and structurally — the separate rooms, the flexible agreements, the honesty about what commitment means to you specifically. **Freedom declared is not a threat to love; freedom smuggled is.** The right people will not flinch at your terms. They have been looking for someone who lets them have terms too."
  },
  {
    title: "Uranus in the 8th House",
    body: "Your transformations come as lightning, not erosion. The eighth house holds intimacy, shared resources, and the psyche's basement, and Uranus wires all of it with live current: change here arrives suddenly and completely — the inheritance out of nowhere, the settlement, the midnight insight that ends an era before breakfast. What looks like upheaval is usually **liberation with bad timing**.\n\nThe practice is updating your agreements before the storm does it for you. Revisit the entanglements — financial, emotional, sexual — while things are calm, because this placement punishes autopilot in shared arrangements and rewards radical honesty about them. Say the unsaid thing early. And trust your gift: you can release what others grip for decades, walking out of the burning identity with surprising lightness. **You are built for sudden freedom.** When the bolt comes, you are not being punished. You are being unstuck, fast, by the only method that was ever going to work on you."
  },
  {
    title: "Uranus in the 9th House",
    body: "You believe in revision. Inherited doctrine slid off you early — maybe spectacularly — and your philosophy has been self-assembled from unlikely parts ever since: science shelved next to mysticism, ancestral practice annotated with footnotes, the sacred and the skeptical in ongoing conversation. Travel and study exist, for you, to **detonate your assumptions**, and you keep buying tickets because you like the sound.\n\nTeach what you find. Heretics with receipts make the best professors, and this placement often becomes the one who cracks a tradition open so the people it excluded can finally get in — the reinterpreter, the bridge, the one who says the old text can mean something new. The practice is staying revisable yourself: even your rebellions can calcify into doctrine if you defend them long enough. Keep one belief on probation at all times. **A living philosophy molts.** Yours is healthiest mid-shed, slightly raw, and honest about it."
  },
  {
    title: "Uranus in the 10th House",
    body: "Your career will not stay in its lane, and forcing it to is the only real failure available here. Expect zigzags: sudden pivots, fields that barely existed when you started, a public identity as the innovator, the friendly disruptor, the one who left the good job and was right to. Conventional ladders bore you into sabotage — **the resume was never going to be linear**, and that is its strength.\n\nThe practice is coherence without conformity. Let the pivots share a throughline — the value you carry from field to field — so the zigzag reads as a signature rather than static. Build a body of work only you could have made and let it introduce you. And accept the public role your difference creates: being visibly unconventional in your profession is itself a contribution, because **every field needs proof that the mold is optional**. Someone earlier on the path is watching you work free, and taking notes."
  },
  {
    title: "Uranus in the 11th House",
    body: "Uranus works from home territory in the house of friendship and the collective future, and your social world proves it. Your circles are gloriously unmatched: collaborators from every subculture, friendships that begin in odd corners of the internet or the world and quietly reroute your life. You tend to see **where the collective is going a few years early** — the movement before it has a name, the tool before it has users.\n\nTrust that sight, and put it to work with others. Your role in any group is the one who opens the window: questioning the bylaws, welcoming the person the group did not know it needed, updating the mission before it fossilizes. The practice is staying through the friction your openings create — revolutionaries who leave at the first pushback change nothing. Find the others; they are your real inheritance. **The future is a group project**, and you were built to be early to it."
  },
  {
    title: "Uranus in the 12th House",
    body: "Your breakthroughs incubate in the dark. Insight arrives through dreams, solitude, and sudden knowing that skips every logical step, as if a back channel to the collective stays open while you sleep — you wake with answers to questions you had not consciously asked. The twelfth house keeps things hidden, though, so this genius can feel **like a signal you receive but never broadcast**: a radical inner life behind an unassuming exterior.\n\nThe practice is bringing the rebel above ground. Keep the notebook by the bed; give the strange insights daylight and form before they evaporate; find even one person or page that hears your uncensored thinking. Unexpressed, this placement leaks — restlessness with no address, insomnia, the sense of a life running in parallel. Expressed, it builds. **Your inner strangeness is a resource, not a secret to keep.** The visions you have been quietly storing were never meant to stay in the archive."
  }
];

export const NEPTUNE_IN_HOUSE: Interpretation[] = [
  {
    title: "Neptune in the 1st House",
    body: "You are a soft-focus photograph people project their longings onto. Neptune in the house of the self blurs your edges beautifully: you absorb the mood of every room, shape-shift by company, and carry a glamour you never consciously applied — strangers confide in you, cast you in their stories, swear you remind them of someone. The gift is **an empathy that borders on telepathy**. The cost is that your outline can go missing in a crowded room.\n\nThe practice is keeping one definition of yourself that no audience can edit. Not a rigid brand — just a few facts about who you are that survive other people's projections: what you love, what you will not do, what you know about yourself at 3 a.m. Check your boundaries the way sailors check weather, routinely and without drama. **Your porousness is an instrument, not a leak**, once you decide when it opens. You get to be the one holding the lens."
  },
  {
    title: "Neptune in the 2nd House",
    body: "Money behaves like weather for you — atmospheric, hard to grip, occasionally miraculous. Funds dissolve mysteriously and materialize the same way, and you may earn through imagination, healing, or art while **undercharging for all three**, because how do you invoice for something as unmeasurable as what you actually do? It is measurable. Other people with half your gift are measuring it right now and billing accordingly.\n\nThe practice is gentle structure, not conversion to accountancy: the automatic transfer, the one weekly look at the numbers, the rate you set once — slightly too high, on purpose — and stop renegotiating with yourself. Underneath the fog, this placement carries an uncanny nose for value others miss: the undervalued idea, the overlooked beauty, worth invisible to the market until you point at it. And hold the deeper truth: **your value does not fluctuate with your bank balance**. It never did. The account is weather; you are the climate."
  },
  {
    title: "Neptune in the 3rd House",
    body: "You think in watercolor. Language, for you, is less a filing system than a tide: poetry comes easier than paperwork, you often know what someone means before they finish the sentence, and your best ideas arrive as images that take days to translate into words. Conversations with you tend to drift somewhere deeper than anyone planned — **you speak fluent subtext**, and people leave feeling mysteriously understood.\n\nThe blur cuts both ways, so build small verification habits: repeat back the time, write down the address, confirm the thing you are certain you heard, because certainty is exactly where the fog hides. Then write — actually write. Minds like yours exist to **say the unsayable**, to give the collective its words for feelings it has only hummed. Journaling, lyrics, letters, voice memos at red lights: the form matters less than the practice. What moves through you is meant to land somewhere. Give it a page."
  },
  {
    title: "Neptune in the 4th House",
    body: "Home carries a longing you cannot quite trace, as if the address you are homesick for was never on any map. Family history may hold fog — idealized figures, quiet absences, stories with soft spots nobody presses — and you may have grown up sensing **the feelings under the floorboards** more clearly than anyone named them. That sensitivity was accurate. It was also never yours to carry alone.\n\nYour work is making sanctuary real: rooms, rituals, and people with actual weight. Salt at the doorway if that is your practice, soup on the stove, music at dusk — you have a gift for making a home feel enchanted, and it deserves a sturdy container: the lease read, the boundaries kept, the door that locks. Grieve the ideal home so you can build the true one. **Homecoming is something you can construct**, and the belonging you make on purpose will hold better than the one you kept dreaming backward toward."
  },
  {
    title: "Neptune in the 5th House",
    body: "You fall in love the way other people fall asleep — deeply, and half into a dream. Romance and creativity both run on enchantment here: your art can genuinely transport people somewhere better, and your affections arrive with a soundtrack, a golden light, a sense of destiny that is **part perception and part production design**. Nobody romances like you. That is the gift and the caution in one sentence.\n\nThe edge is discernment. Muses are real, but so are mirages, and you have loved at least one projection wearing a person as a costume. The practice is loving the actual human — bored, flawed, specific — and making the actual thing rather than endlessly imagining it, because **magic that survives contact is the only kind worth keeping**. Finish the song. Date the real person. Your imagination is not diminished by reality; it is the rare kind strong enough to be built with."
  },
  {
    title: "Neptune in the 6th House",
    body: "Your work wants to be service, and your body speaks in symbols. Ordinary jobs drain you strangely fast unless they carry meaning, while healing, creative, or care-centered work returns more than it takes — you are solar-powered by **usefulness that actually matters**. Meanwhile the body runs on subtext: fatigue, tension, and mood arrive as messengers about what the mind has not admitted yet, and they are rarely wrong.\n\nTreat the symptoms as mail, not malfunction. Ask what the exhaustion knows. And guard the porousness at work, because you absorb every colleague's crisis and every client's grief by default — **boundaries are not cynicism; they are hygiene**, the professional kind that lets you keep serving for decades instead of burning sacred and fast. Build routines with softness in them: water, rest, unhurried mornings where possible. Your daily life is a spiritual practice whether you name it one or not. Choose the rituals on purpose."
  },
  {
    title: "Neptune in the 7th House",
    body: "You see the best possible version of every partner — sometimes years before they do, sometimes instead of them. Relationship is your holy ground and your fog bank at once: devotion comes naturally, and you can love with a completeness that feels, to the person receiving it, like being believed in for the first time. The shadow is that **you sometimes fall for your own forecast** and date the potential while the actual person stands there, unexamined.\n\nDiscernment is the acquired skill. Ask who is actually in front of you, and keep asking, especially in month four when the soundtrack swells. Watch for the placement's classic castings — the partner you must save, the partner who must save you — and step out of both scripts; **real love survives focus; only illusions require the blur**. When you bring your enchantment to an honest bond, this is one of the most genuinely romantic placements there is. The dream was never the problem. The dodge was."
  },
  {
    title: "Neptune in the 8th House",
    body: "Intimacy, for you, borders on the mystical. Merging with another — in sex, in grief, in the strange trust of shared bank accounts — can feel like dissolving a boundary the rest of the world insists on, and you sense the undercurrents others walk straight past: the unspoken resentment in the estate, the real reason the money argument is never about money. **You read the deep water fluently.**\n\nThe caution is losing your outline down there. Fusion this available can slide into fog — debts absorbed that were never yours, grief carried on someone else's behalf, a self misplaced inside a we. So bring your own lantern: clear agreements around shared resources, a therapist or practice that keeps your edges findable, sobriety about what is actually yours to hold. Do that, and these waters become your genius — **you can accompany people through what terrifies them** and return whole, carrying back the kind of knowing that cannot be taught."
  },
  {
    title: "Neptune in the 9th House",
    body: "Your faith is oceanic and none of the containers quite fit. You are drawn to the mystical branch of every tradition — the poets, the contemplatives, the far shore of every map — and meaning arrives for you as **experience rather than argument**: the moment in the mountains, the dream that reordered you, the stranger's sentence that landed like scripture. Doctrine has always felt like a photograph of water.\n\nBeware gurus with confident answers, because your longing for the divine can make salesmen look like saints; the test is always how a teacher handles doubt and power. Your path is direct taste — pilgrimage suits you, even when it looks like an ordinary trip, and study suits you when it is allowed to become devotion. Take the permission fully: **you are allowed a faith made of your own encounters**, syncretic, revisable, and answerable to no committee. The sacred has been meeting you directly all along. That was never an error. That was the syllabus."
  },
  {
    title: "Neptune in the 10th House",
    body: "Your public role is a canvas others paint on — an asset and a hazard in one. You carry professional mystique: people project ideals onto you, remember you as larger than the meeting, assume depths (correctly) and intentions (variably). Careers in art, healing, film, spirit, or service fit because **your work is at its best when it moves people**, not just when it functions.\n\nThe tension is drift — a calling that stays felt but unfocused for years, a decade of almost-directions, the sense of being meant for something you cannot name at parties. The practice is naming the dream specifically: not helping people in general but which people, how, in what form, starting when. Mist becomes direction the moment it gets coordinates. And tend your reputation deliberately, because projections curdle when unmanaged; let your visible work state plainly what you value. **You are allowed to be publicly devoted to something tender.** That is not unprofessional. It is your profession."
  },
  {
    title: "Neptune in the 11th House",
    body: "You dream in the collective tense. Friendship, for you, aspires to communion — you want circles gathered around ideals, not just calendars: the artists, the healers, the believers in some better arrangement of the world. In good company you almost dissolve into the shared purpose, and your presence tends to raise a group's sense of **what it is really for**.\n\nYour radar for group longing is exquisite; your radar for group dysfunction lags behind it, which is how visionaries end up holding the unpaid labor of half-imaginary utopias. So choose communities by their actions, not their language — watch how they treat the least glamorous member, how money moves, who does the dishes after the meeting about the revolution. Bring your vision to people with follow-through, and it finally lands somewhere real. And keep one or two friendships that are just human-sized — soup, laundry, honesty — because **belonging needs a body**, not only a dream."
  },
  {
    title: "Neptune in the 12th House",
    body: "Neptune runs at full strength in the twelfth, and the door between you and the invisible sits unusually ajar. Solitude is not optional for you; it is **where you refill, receive, and remember** what the noise made you forget. Dreams carry mail. Music undoes you in public. You know things about strangers you have no business knowing, and the border between your feelings and the world's has always needed customs officers it never got.\n\nThe practice is returning — coming back from the deep with something in hand rather than staying under, because this placement's one real danger is escape that forgets to end: the scrolling, the substances, the fantasy that quietly replaces the life. Structure your retreats so they have an exit: the timed meditation, the scheduled solitude, the creative practice that gives the ocean a shoreline. **You were built for both worlds.** The gift was never the leaving. It is what you carry back."
  }
];

export const PLUTO_IN_HOUSE: Interpretation[] = [
  {
    title: "Pluto in the 1st House",
    body: "You arrive with an intensity you did not choose and cannot fully dim. People sense power in your presence before you have said a word, and they respond with fascination or flinching — rarely indifference, which you learned early and perhaps the hard way. Your life runs on **deliberate reinvention**: you shed whole selves like old skins, and the person you were five years ago can feel like a rumor.\n\nThe practice is owning the force openly, because hidden power distorts and claimed power builds. Denying your own intensity does not make you smaller; it makes you underground, and underground pressure finds cruder exits. So state what you want. Take the room you were going to take anyway, but take it in daylight. And extend gentleness to the people adjusting to your weather — **you are a lot, and you are meant to be**. The ones who can meet you at depth were never scared off by the surface."
  },
  {
    title: "Pluto in the 2nd House",
    body: "Your relationship with resources is a story of death and rebirth — sometimes literally in the account balance. Money carries survival weight for you: losses land like verdicts, gains like reprieves, and somewhere back there you may have learned that having and safety were the same word. They are not, and proving that to your own nervous system is the work. Notice your track record first: **you can rebuild from nothing**, and you have.\n\nThat regenerative talent is the real asset. Skills survive crashes; character survives repossession; the worth that matters is the kind that walks out of every fire with you. The practice is letting value live in you rather than the vault — loosening the grip, giving deliberately, buying the small beautiful thing without a crisis of conscience. **What you own should not own you back.** When money becomes a tool instead of a verdict, this placement turns formidable: deep resourcefulness, patient accumulation, and nothing left to threaten you with."
  },
  {
    title: "Pluto in the 3rd House",
    body: "Your words carry more voltage than the standard sentence. You listen like an investigator, speak like someone who has already found the buried thing, and small talk starves you within minutes — you want the conversation under the conversation. Some early experience may have taught you that **language is power**: words used as weapons, or truths that had to be spoken in code. You learned to handle sentences like live wires because in your world, they were.\n\nThe practice is using the voltage to illuminate rather than interrogate. Your questions can open people or pin them, and the difference is consent — ask like a fellow traveler, not a prosecutor, and people will hand you truths they have never said aloud. Write the things that feel too honest to publish; that is exactly the register your voice was built for. **Say the unsaid thing kindly** and rooms change. People never forget what you said. Make that a responsibility you enjoy."
  },
  {
    title: "Pluto in the 4th House",
    body: "Your taproot goes down through complicated soil. Family life likely held buried intensities — power struggles, secrets, love with conditions attached — and you became the one who feels the house's undercurrents, the child who knew what was wrong before anyone said it. That perception was survival then. It is **excavation equipment now**.\n\nHere is the alchemy this placement offers: what you dig up, you free — and not only for yourself. By facing the family depths honestly — the therapy, the hard conversations, the naming of what everyone agreed not to name — you end cycles that outlasted generations, and you earn a home that is truly yours. Take the permission all the way: you are allowed to define family by safety rather than blood, to keep distances that keep you whole, to build a household where **no one has to go underground to survive**. The line of inheritance changes at you. That is not a burden. That is the point."
  },
  {
    title: "Pluto in the 5th House",
    body: "You do not dabble. Creation, romance, and play all run at full depth for you: art that exhumes something real, love affairs that rearrange your interior, joy with actual stakes. Lightness can feel like a foreign language you can order coffee in but never dream in — and that is fine, because your gift was never decoration. **You make things that transform their audience**, and you love in a register most people only visit.\n\nThe practice is letting pleasure be safe enough to survive. Intensity can turn every romance into a crucible and every hobby into a reckoning, and sometimes the radical move is play without a verdict at the end — the dance class, the absurd game, the fling that is allowed to just be sweet. Watch possessiveness in love; passion holds, control corrodes. And keep making the deep work. **Your joy has gravity**, and the people pulled into its orbit tend to leave changed, grateful, and more honest than they arrived."
  },
  {
    title: "Pluto in the 6th House",
    body: "Work, for you, is transformation disguised as routine. You reorganize whatever system employs you — quietly, thoroughly, down to the studs — and you cannot help it; inefficiency and pretense in a workplace register to you like a smell. Meanwhile the body keeps its own records: **every suppressed truth becomes a symptom** before the mind admits it, and your health history probably reads like a diary written in a second language.\n\nThe practice is letting the daily grind refine you instead of consuming you. Perfection can become compulsion here — the standards climbing forever, rest treated as evidence against you — so set an actual finish line each day and honor it like a ritual. Listen to the body early, while its messages are still whispers. And claim the gift: you regenerate through meaningful work, healing as you fix, growing as you serve. **Aim your intensity at systems worth transforming**, including your own habits, and the sixth house becomes your forge rather than your grind."
  },
  {
    title: "Pluto in the 7th House",
    body: "Your closest relationships are crucibles, and you knew that before anyone told you. You attract powerful partners — or partners through whom power gets negotiated — and every real bond eventually arrives at the same pair of questions: who controls what, and **can we survive being fully seen**? You can. That is precisely what this placement builds you for.\n\nThe practice is choosing people willing to transform alongside you, because you will not stay the same inside a committed bond and neither should they — partnership, for you, is a metamorphosis with a witness. Watch the twin traps: merging so completely you disappear, or gripping so tightly the other person becomes a project. Power struggles are information; they show you where the fear lives, yours and theirs. Bring the fear into language and the struggle becomes intimacy. **Loving you is a serious undertaking**, and the ones built for it consider that the best part."
  },
  {
    title: "Pluto in the 8th House",
    body: "Pluto sits in its own preferred territory here, and the deep end is simply where you live. Merging, mortality, shared resources, the psyche's basement — you navigate ground that sends others scrambling for the shallow steps, and you have likely been the one holding steady at bedsides, in aftermaths, during the conversations everyone else fled. **Crisis reliably regenerates you**; you come back from endings with more self, not less.\n\nThe discipline this placement demands is trust dispensed carefully but genuinely — carefully, because you know exactly what betrayal costs; genuinely, because a vault that never opens is just a tomb with better security. Let the tested few all the way in, including into your finances, your grief, your body's real history. And take the vocation seriously: the world is short on people who can sit with dying, debt, desire, and truth without blinking. **Power shared is power multiplied.** You did not survive the depths to hoard the map."
  },
  {
    title: "Pluto in the 9th House",
    body: "You do not adopt beliefs; you interrogate them under bright lights. Faith, for you, must survive demolition to earn residence, and your worldview has already died and been rebuilt at least once — possibly with a dramatic exit from whatever tradition raised you. That process was not a crisis of faith. It was **faith doing its actual work**: burning off the borrowed parts until only the load-bearing convictions remained.\n\nThe practice is guarding against the convert's certainty, because a rebuilt belief system can turn as rigid as the one it replaced, and zeal is just fear wearing a doctorate. Keep interrogating, gently, forever — including your own conclusions. Then teach. This placement makes the transformative educator, the one whose scars are the curriculum, and **people trust a guide who has been lost**. Your philosophy was earned in demolition and reconstruction. Hand it to others as tools, not commandments, and it liberates instead of converts."
  },
  {
    title: "Pluto in the 10th House",
    body: "Your ambition has an undertow. You are drawn toward roles with real stakes — power, influence, transformation at scale — and your career will likely die and resurrect at least once on the way there: the industry left, the reputation rebuilt, the pivot that looked like ruin and turned out to be molting. **You are not building a job; you are building a force**, and forces take longer.\n\nThe public watches you more closely than most, which is uncomfortable and useful in equal measure — use the scrutiny as an honesty device, because anything hidden in a life this visible tends to surface with interest. Lead transparently and the intensity reads as gravitas. The deeper practice is examining what you want power for; ambition aimed only at safety stays hungry forever, while ambition aimed at **changing what you once survived** becomes unarguable authority. Your influence is coming either way. Decide early whom it serves."
  },
  {
    title: "Pluto in the 11th House",
    body: "You join groups the way tectonic plates join continents — slowly, then with lasting consequence. Surface networking repels you: you want alliances with weight, causes with teeth, friendships that could survive an interrogation. When you do commit to a circle, you tend to become its quiet gravitational center — the one holding the group's real history, the one people call when it actually matters. **Your loyalty is geological.**\n\nThe practice is choosing your people like the future depends on it, because — for you — it does: the eleventh house is where tomorrow gets built, and Pluto here means your collectives transform things, for better or worse. Watch power dynamics inside chosen family and movements; you can spot manipulation instantly in others and excuse it too long in causes you love. Leave groups that require your silence. Stay loudly in the ones that do not. **A few unshakable allies outweigh any audience**, and building that handful is your life's quiet masterwork."
  },
  {
    title: "Pluto in the 12th House",
    body: "Your power works underground — sometimes even from you. Pluto in the twelfth stores intensity in the unconscious: old fears, inherited dreads, and strengths you have not formally met yet, all humming behind the wall. Life keeps arranging encounters with that hidden reservoir — the reaction bigger than its trigger, the dream that will not quit, the pattern that repeats until you finally turn around and look at it. **What runs you from the dark wants to be met**, not managed.\n\nSolitude, therapy, and dreamwork are your excavation tools, and this placement rewards the digging like no other: every fear named becomes fuel, every retrieved memory returns carrying a strength. What you bring up from your own depths becomes uncanny compassion — the kind that can sit with anyone's darkness without flinching, because you have inventoried your own. **Your gentleness has a basement full of proof.** That is why it holds. That is why people heal near you."
  }
];
