import type { Interpretation } from "./types";

/** Arrays are indexed by house: 0 = 1st house … 11 = 12th house. */

export const SUN_IN_HOUSE: Interpretation[] = [
  {
    title: "Sun in the 1st House",
    body: "Your life leads with you — not your résumé, not your relations, you. With the Sun in the 1st house, vitality sits right at the surface: the body, the name, the way you cross a room are all part of your statement of purpose. People read you fast and remember you long, because you are **your own first evidence**. For anyone whose selfhood has been contested — misread, renamed, told to shrink — this placement is a quiet insistence that being visibly yourself is not indulgence. It is the assignment.\n\nThe growth edge is authorship. A self this visible attracts feedback, and feedback can quietly become a script; before long you are performing the version of you that meets the least resistance. The practice is periodic reclamation: asking **who wrote this draft of me**, and revising anything you did not choose. You are permitted to change the answer publicly, more than once, without apology.",
  },
  {
    title: "Sun in the 2nd House",
    body: "With the Sun in the 2nd house, your sense of self is built rather than bestowed. Purpose runs through what you earn, make, keep, and value — money, yes, but also craft, self-respect, and the small durable proofs that your labor holds weight in the world. You feel most alive when you can point at something and say, **I grew this**. Livelihood is not a side plot for you; it is one of the main places your light becomes visible, and material independence is close to sacred.\n\nThe edge: in a world that prices people, it is dangerously easy to let the ledger grade your worth. The practice is learning to locate value **before the invoice clears** — naming what you carry that no market ever appraised. Your worth is the premise of the work, not its output. Build from that, and everything you make gets sturdier.",
  },
  {
    title: "Sun in the 3rd House",
    body: "You come alive mid-sentence. A 3rd house Sun locates vitality in language, questions, and the near world — siblings and sibling-figures, neighbors, the errand that becomes a conversation, the group chat that becomes a lifeline. Your mind is not an accessory to your identity; **thinking is how you shine**. You are the one who names what everyone was circling, the translator between rooms, the person for whom a good question is a form of devotion.\n\nThe growth edge is depth over coverage. Curiosity this bright can skim — collecting facts, tabs, and takes without letting any of them leave a mark. The practice is choosing, now and then, **one question worthy of changing you** and staying with it past the point of cleverness. Let an idea rearrange your furniture. That is when your gift stops being quickness and becomes wisdom with a fast engine.",
  },
  {
    title: "Sun in the 4th House",
    body: "Your light burns from inside the house. With a 4th house Sun, identity roots in origins — family of birth or family of choice, land, language, the private rooms where you are most unedited. You may look understated from the street while quietly holding the whole hearth together, because your purpose is foundational rather than performative: **you are the keel, not the sail**. Home, for you, is not backdrop. It is the work.\n\nThe edge is lineage. Every inheritance arrives with instructions, and some of yours were written for a person you are not. The practice — especially if the family you came from could not fully see you — is **claiming the inheritance while rewriting the instructions**: keeping the recipes, the resilience, the stories, and composting the scripts. You are allowed to build a home your ancestors never imagined and still call it theirs, and yours.",
  },
  {
    title: "Sun in the 5th House",
    body: "You were built to make things and mean it. A 5th house Sun ties vitality to creation in every register — art, romance, play, children if you choose them, projects with **your fingerprints pressed visibly into them**. Pleasure is not your reward for surviving the serious parts of life; it is your engine, the furnace everything else runs on. When you are creating, flirting, performing, or playing full-out, you are not escaping your purpose. You are standing in it.\n\nThe growth edge is the difference between joy and applause. A light this warm draws an audience, and audiences train you, subtly, to perform delight instead of feeling it. The practice is keeping some creations **unmonetized, unposted, unexplained** — made for the sheer animal pleasure of making. Delight that needs no witness is the root system; keep it alive and the visible blooms take care of themselves.",
  },
  {
    title: "Sun in the 6th House",
    body: "Devotion is your way of shining. With the Sun in the 6th house, purpose lives in craft, routine, and the unglamorous mastery of doing a thing well every single day — the tended process, the reliable hands, the work that holds because you held it. Your body keeps honest score here: **how you work becomes how you feel**, and vitality rises or falls with the shape of your days. You are the person institutions quietly depend on, often more than they admit.\n\nThe edge is the old bargain where usefulness stands in for worth. Service can be a joy or a hiding place, and only you can tell which one you are in. The practice: serve because it feeds you, rest **before you have earned it**, and let the daily rituals — meals, movement, medication, sleep — be acts of self-respect rather than maintenance on a machine. You are not your output.",
  },
  {
    title: "Sun in the 7th House",
    body: "You find yourself most clearly in the mirror of another. A 7th house Sun stakes identity on relationship — the beloved, the business partner, the collaborator, even the worthy rival who sharpens you. One-to-one is your native scale: you think better in dialogue, shine brighter in duet, and treat **committed relating as an art form**, whatever shape your commitments take. No script required — this house honors the partnership you actually build, not the one convention drew.\n\nThe growth edge is keeping your own pilot light on. When identity lives in the mirror, an empty mirror can feel like an emergency, and it becomes tempting to hand someone else the job of knowing who you are. The practice is simple to say and lifelong to do: **arrive as a whole person**, so connection is a meeting of two centers rather than a rescue. You are the other half of no one.",
  },
  {
    title: "Sun in the 8th House",
    body: "You are not here for the shallow end. An 8th house Sun draws vitality from what most people spend their lives avoiding — intimacy without armor, shared money and shared fate, grief, desire, power, the conversations held at 2 a.m. in lowered voices. You have likely already died a few times in this life, metaphorically speaking, and learned the secret of this placement: **you are the thing that survives the shedding**. Each ending has made you more specific, not less.\n\nThe growth edge is witness. Depth this practiced can calcify into secrecy, and secrecy will keep you safe the way a vault keeps money safe — untouched, and untouching. The practice is letting a few earned people see the basement rooms, and discovering that **being known is not the same as being captured**. Your transformations were never meant to be solo performances. Let someone hold the lantern sometimes.",
  },
  {
    title: "Sun in the 9th House",
    body: "Your identity has a passport. With the Sun in the 9th — the house where the Sun rejoices — you grow by going: across borders, into philosophies, toward whatever horizon promises a truer map. Study, travel, teaching, publishing, faith and its renovations all belong to you; so does the outsider's gift of **seeing every culture as one option among many**, including the one that raised you. Meaning is not a luxury in your chart. It is the food.\n\nThe growth edge is conviction held with open hands. A seeker this committed can quietly become a preacher, mistaking the current map for the territory. The practice is staying **a student inside your certainty** — teaching what you know while auditing your own curriculum. The truest thing you will ever offer anyone is not an answer. It is the visible, ongoing example of a person still willing to be changed.",
  },
  {
    title: "Sun in the 10th House",
    body: "You were always going to be seen; the open question is for what. A 10th house Sun aims vitality at vocation — the public work, the reputation, the contribution with **your name legible on it**. Ambition here is not vanity; it is orientation, the way a compass is not arrogant for pointing. You feel most alive when your effort lands somewhere visible and accountable, and people likely began projecting authority onto you before you felt ready to hold it.\n\nThe growth edge is choosing your own mountain. Public selves attract inherited summits — the career your family blessed, the pedestal your community assigned, the respectability that asked you to sand off your edges. The practice is a regular audit: **is this climb still mine?** You are permitted to be publicly excellent at something your lineage never dreamed of, and to redefine what authority looks like simply by being yourself in charge.",
  },
  {
    title: "Sun in the 11th House",
    body: "Your light is communal property, and you like it that way. An 11th house Sun finds purpose in the plural — friendships that function as infrastructure, coalitions, scenes, chosen family, the long collaborative project of **a future worth arriving at**. You think in decades and in networks; your gift is convening, connecting, and holding a vision steady enough that other people can build toward it. For anyone who had to leave one belonging to find another, this placement is the promise that your true kin are findable.\n\nThe growth edge is staying particular inside the collective. Groups reward harmony, and a self this communal can quietly dissolve into consensus, shining with everyone and as no one. The practice is remaining **a distinct voice in the chorus** — bringing your strangest, most specific self to the group, because that specificity is your actual contribution. The circle does not need more agreement. It needs you.",
  },
  {
    title: "Sun in the 12th House",
    body: "Some suns rise behind the mountain and still light the whole valley. A 12th house Sun works in the unseen registers — solitude, dreams, institutions, the long inner life, service performed where no camera reaches. Your vitality replenishes in retreat and leaks in constant company, and you may have spent years feeling like **a strong signal broadcast on a private frequency**: deeply influential, rarely credited. This is not failure to shine. It is a different physics of light.\n\nThe growth edge is refusing invisibility as an identity. What began as sanctuary — staying unseen, unneedy, offstage — can quietly become a cell whose door you forgot is unlocked. The practice is rhythmic: honor the retreats that restore you, then **let yourself be found** — by the friend, the collective, the work that needs your particular quiet. A hidden life can still be a chosen one. Choose it out loud, occasionally.",
  },
];

export const MOON_IN_HOUSE: Interpretation[] = [
  {
    title: "Moon in the 1st House",
    body: "Your feelings arrive before your words do, and everyone can tell. A 1st house Moon wears the inner weather on the surface — mood moves through your face, your posture, your appetite, and people experience your presence as unusually alive, unusually honest. You respond to life instinct-first, and your body is the most accurate journal you keep. This is not oversensitivity; it is **fluency in a language most people can barely read**.\n\nThe growth edge is choosing your broadcasts. Feelings this visible get handled by other people — soothed, judged, managed — before they finish forming, which can teach you to distrust them. The practice is a small privacy: letting a feeling **complete itself before it goes public**, so you meet it first. And permission, since you may need it in writing: your changeability is not instability. You are tidal. Tides are not broken; they are how the moon talks to the sea.",
  },
  {
    title: "Moon in the 2nd House",
    body: "Security, for you, is something you can hold. With the Moon in the 2nd house, comfort lives in the tangible — the savings cushion, the stocked pantry, the sweater with history, the room arranged exactly right. Your moods track your sense of provision more closely than you may realize: a healthy reserve settles your nervous system the way weather settles after rain. There is real wisdom here — **care made material** — especially for anyone who learned early that safety could vanish.\n\nThe growth edge is uncoupling your calm from the balance. Numbers fluctuate; if your peace fluctuates with them, the market owns your nervous system. The practice is building **steadiness you generate yourself** — routines, skills, the felt knowledge of your own resourcefulness — so that provision supports your security instead of defining it. You are allowed to feel safe before everything is stockpiled. You are the most renewable resource you own.",
  },
  {
    title: "Moon in the 3rd House",
    body: "You process feeling by talking it into shape. The Moon has its joy in the 3rd house, and it shows: conversation is not small talk for you, it is digestion — the sibling call, the voice memo, the notebook that hears everything first, the neighborhood walk where the knot finally loosens. Your heart and mind share one bloodstream, and your daily orbit of familiar people and routes is **the habitat your feelings live in**.\n\nThe growth edge is letting the words find the feeling, not replace it. A mind this fluent can narrate an emotion so skillfully that it never actually gets felt — analysis as a beautiful escape hatch. The practice is occasionally putting the story down and asking the body what it knows: **where does this live in me?** Write it, speak it, walk it. But every so often, let yourself be moved before you are articulate.",
  },
  {
    title: "Moon in the 4th House",
    body: "The Moon recognizes the 4th house the way you recognize a childhood smell: instantly, bodily, before thought. Your emotional life is rooted in place and lineage — you feel your feelings in kitchens and doorways, keep the family memory whether anyone asked you to, and tend people the way others tend gardens. Home is not where you relax; **home is how you metabolize your life**, and whoever gets to see you there gets the truest edition.\n\nThe growth edge is what to do with the blueprint. Every childhood home installs an emotional floor plan, and some of yours has rooms built for a person you never were. The practice — profound for anyone whose origins could not hold all of them — is **renovation without demolition**: keeping the warmth, the recipes, the loyalty, while building rooms your history never included. Chosen family counts. The nest you make can heal the nest you got.",
  },
  {
    title: "Moon in the 5th House",
    body: "Your heart wants to make something of itself, literally. With the Moon in the 5th house, emotion moves through creation — feelings become songs, dinners, love letters, elaborate birthday plots, games taken seriously in the best possible way. Romance and play are not diversions from your emotional life; they are **its native tongue**. You may also nurture the young — children of your own, other people's, or the younger self still living in you — with unusual instinctive warmth.\n\nThe growth edge is letting joy be a practice rather than a mood you wait for. When grief or flatness comes, your medicine is rarely stillness; it is expression — give the feeling **a color, a stanza, a stage**, and it starts to move. Permission, in writing: your delight is not frivolous. In a world that profits from your numbness, cultivating pleasure on purpose is a serious act, and you are gifted at it.",
  },
  {
    title: "Moon in the 6th House",
    body: "You steady yourself through ritual. A 6th house Moon finds comfort in the daily round — the tended body, the ordered desk, the small repeated offices of care that keep a life running: meds taken, plants watered, the walk at the same hour. Your feelings show up somatically first, **the body speaking before the mouth does** — the clenched jaw, the skipped meal, the shoulder that files complaints. Caring for someone, for you, mostly looks like doing something.\n\nThe growth edge is tending the tender, not just the tasks. Routine can be devotion or armor; a schedule can hold your life or hold it at bay. The practice is building days that include **your own name on the care list** — rest scheduled with the same seriousness as work, help received as gracefully as it is given. Your worth was never conditional on your usefulness. Let at least one daily ritual exist purely because it comforts you.",
  },
  {
    title: "Moon in the 7th House",
    body: "You feel in duet. A 7th house Moon reads the emotional temperature of a room through the person across from you — attuned, responsive, instinctively balancing whatever the other carries. Closeness is not preference here; it is **nourishment at the level of need**, and you are genuinely gifted at holding people, whatever forms your partnerships take. This house does not assume marriage or any script — it simply says: you, plus one, is where your heart does its deepest work.\n\nThe growth edge is being held without editing the need. Attunement this skilled can become one-directional — you become everyone's shore and no one's sea. The practice is stating your needs **before they become emergencies**, and choosing people who ask how you are and wait for the real answer. Belonging to someone should never require vanishing into them.",
  },
  {
    title: "Moon in the 8th House",
    body: "Your inner life has basements, and you have the keys. An 8th house Moon feels everything at full depth — trust, loss, desire, the currents running under what anyone says out loud. You register the unspoken in a room like weather on skin, and half-intimacy leaves you hungrier than solitude ever does. Likely you learned early that feelings could be dangerous territory, so you built **a fortress with excellent locks** — and you decide, person by person, who gets a key.\n\nThe growth edge is remembering what the fortress costs. Walls that keep out harm keep out healing with the same efficiency, and self-containment can quietly become self-exile. The practice is graduated trust: letting one earned person see one real room, then noticing that you survived it. **Your depth is not too much**; it is a birthright. The people who can meet it exist, and they are not obligated to be the ones who taught you to hide.",
  },
  {
    title: "Moon in the 9th House",
    body: "You are homesick for places you haven't been yet. A 9th house Moon finds emotional nourishment at a distance — the far city, the thick book, the philosophy that reorganizes everything, the teacher who feels like family within an hour. Restlessness is not your defect; it is **your compass reading true**, pointing at the horizon where your heart does its growing. You may feel more at home among strangers abroad than at some tables you were born to.\n\nThe growth edge is letting meaning metabolize feeling without bypassing it. A mind this good at the wide view can zoom out of a wound before it has been cleaned — turning grief into philosophy on contact. The practice is sequence: **feel first, frame second**. And the permission: you are allowed to outgrow the beliefs that raised you and call that faithfulness — to the truth, which is the only congregation you never left.",
  },
  {
    title: "Moon in the 10th House",
    body: "Your inner life happens in public more than most. With the Moon in the 10th house, feeling and vocation intertwine — you care visibly, your work carries your tenderness in it, and the world responds to that caring, sometimes by asking too much of it. You may find yourself mothering whatever you manage: the team, the classroom, the audience. Your reputation, whether you like it or not, includes **your heart on the record**.\n\nThe growth edge is a private hearth. When your nurture is professionally legible, it is easy to let the public role consume the personal need — to become the caretaker of everyone's weather while your own goes unreported. The practice is building **rooms the audience never sees**: relationships, rituals, and rest that exist entirely off the résumé. Even a lighthouse keeper needs a room without windows. Your care is a gift to the world; make sure the world is not its only address.",
  },
  {
    title: "Moon in the 11th House",
    body: "Your people are your habitat. An 11th house Moon feels safest inside a chosen circle — friends who function as family, the group chat that doubles as a nervous system, causes that hold your heart like a second home. You nurture communally and are nourished the same way, and for anyone whose given family missed the mark, this placement carries a specific promise: **belonging is buildable**. Your kin are not only inherited. They are also found, gathered, kept.\n\nThe growth edge is asking for particular care. In a circle, it is easy to be everyone's soft place and no one's priority — to tend the whole group and hope the tending returns by ambient osmosis. It rarely does. The practice is precision: **name the friend, name the need**, and let one or two bonds go deeper than the collective warmth. The group holds you best when a few hands in it know exactly where you ache.",
  },
  {
    title: "Moon in the 12th House",
    body: "You feel more than you can always account for. A 12th house Moon absorbs the room, the era, sometimes the sorrow of strangers — you are permeable in a way that makes you deeply kind and easily flooded, and much of your emotional processing happens offstage: in dreams, in solitude, in the long bath where the week finally surfaces. Your tenderness runs **deep and mostly underground**, like a river that towns downstream depend on without ever seeing.\n\nThe growth edge is telling your feelings apart from the ambient ones. A boundary, for you, is not a wall; it is a filter — the question **is this mine?** asked gently, often. Retreat is legitimate digestion, not avoidance, so take it without apology. But leave a lantern lit: one or two people who know the path in, so solitude stays a practice and never hardens into a hiding place. You deserve to be found on purpose.",
  },
];

export const MERCURY_IN_HOUSE: Interpretation[] = [
  {
    title: "Mercury in the 1st House",
    body: "Your mind is the first thing people meet. Mercury has its joy in the 1st house, and it shows: you speak in real time, think out loud, and wear curiosity like a face. Wit is not an accessory to your presence — **it is your presence**, the fastest and truest introduction you give. You likely narrate your own life a little as you live it, and people come to you when they need something named, translated, or talked all the way through.\n\nThe growth edge is the pause. A mind this quick can answer before the question finishes landing, and cleverness can become a reflex that stands guard in front of sincerity. The practice: **let a beat of silence** precede the good answer, and notice how much better it gets. Also, permission — your voice, in whatever register it lives, is part of your body. Changing it, claiming it, loving it: all of that is yours to author.",
  },
  {
    title: "Mercury in the 2nd House",
    body: "You think in concrete terms and speak in useful ones. With Mercury in the 2nd house, intelligence is practical — pricing the idea, drafting the budget, turning talk into something that holds weight. Your words themselves can become an asset: writing, negotiating, teaching a skill, naming a value so clearly that people pay for the naming. You distrust abstraction that cannot survive contact with a Tuesday, and honestly, **the world needs your kind of mind**.\n\nThe growth edge is trusting your tempo. Next to quicker talkers you may have learned to call yourself slow, when the truth is you are load-bearing: **you build sentences that last**, and lasting takes longer. The practice is double: defend your deliberate pace without apology, and occasionally spend a thought on something gloriously impractical — a poem, a wondering, an idea with no invoice attached. Not every word you make has to earn its keep. Neither do you.",
  },
  {
    title: "Mercury in the 3rd House",
    body: "Mercury is in home territory here, and everything about your mind confirms it. Thought runs quick, lateral, endlessly hungry — three tabs open in conversation, five more in your head — and language is your native element: the pun, the perfect text, the question that unlocks a stranger. Your daily orbit is your classroom; siblings, neighbors, and group chats form **your intellectual bloodstream**, and you learn the way other people breathe.\n\nThe growth edge is completion. A mind this generative starts brilliantly and abandons fluently — the drafts folder is a graveyard of geniuses. The practice is choosing fewer threads and **following one all the way through the needle**: the finished essay, the mastered skill, the conversation that goes past its natural exit into real depth. Your quickness is a given. What you are building now is stamina — and a fast mind with stamina is very nearly unstoppable.",
  },
  {
    title: "Mercury in the 4th House",
    body: "Your best thinking happens at home, often at odd hours. A 4th house Mercury reasons through memory and feeling — tracing every idea back to its roots before trusting it — and you likely serve as the family archivist: keeper of the stories, translator between generations, the one who remembers what was actually said. Your intelligence is **private, deep, and slow-brewed**, less a press conference than a kitchen-table conversation that changes someone's life.\n\nThe growth edge is publication, in the broadest sense. Insights that circulate only inside your own walls stay unfinished; the wisdom you mutter to the kettle deserves rooms beyond your own. The practice: **speak the private thought out loud** — in the meeting, the letter, the memoir you keep almost starting. And a permission for anyone rewriting their origins: you are allowed to retell the family story with yourself included accurately. The archive belongs to the archivist too.",
  },
  {
    title: "Mercury in the 5th House",
    body: "You think in play. A 5th house Mercury turns ideas into games, arguments into banter, and learning into something with stakes and sparkle — you persuade by delighting, and your best insights arrive mid-creation rather than mid-analysis: in the middle of the song, the joke, the flirtation, the bedtime story improvised past all reason. Your mind is **an instrument, not a filing cabinet**, and it sounds best when you are enjoying yourself.\n\nThe growth edge is commitment. Flirting with ideas is your gift; marrying one, now and then, is your growth — the craft mastered past its honeymoon, the project finished after it stops being fun and before it becomes wonderful again. The practice: **choose one plaything and go deep**, because depth is where your charm becomes authority. And permission: keep making things that are only for joy. The inner critic who calls that childish has never once made anything.",
  },
  {
    title: "Mercury in the 6th House",
    body: "Your mind loves a system it can improve. With Mercury in the 6th house, intelligence expresses through refinement — the better checklist, the cleaner workflow, the diagnosis nobody else caught because nobody else was truly looking. You notice what others skim past: the misplaced comma, the off rhythm in a colleague's step, the small wrongness that precedes the big failure. This is **craftsman's attention**, and workplaces run on people like you, usually without thanking them enough.\n\nThe growth edge is where the analysis points. A mind trained on flaws will eventually turn on its favorite subject — you — and your body hears every anxious sentence you think; the racing thoughts file themselves as tension, gut trouble, sleepless systems-checks at 3 a.m. The practice is aiming the skill deliberately: **audit the process, not your worth**, schedule the worry like a meeting so it stops attending all of them, and let good enough ship. Perfection is not a deliverable.",
  },
  {
    title: "Mercury in the 7th House",
    body: "Thinking, for you, is a two-player game. A 7th house Mercury sharpens through dialogue — you discover your own position by hearing it answered, and you make a superb negotiator, editor, or devil's advocate, able to inhabit another mind so fully that its owner feels finally understood. Partnership of every kind runs on conversation for you: **the talk is the relationship**, and silence between you and someone you love is data you take seriously.\n\nThe growth edge is authorship of your own opinions. A mind this responsive can drift into echo — polished, agreeable, and secretly unsure where the borrowed views end and yours begin. The practice: before the conversation, **write down what you think**; after it, notice what changed and choose the changes consciously. You can honor another mind without subletting your own. The best duet requires two distinct instruments — stay one of them.",
  },
  {
    title: "Mercury in the 8th House",
    body: "You ask the questions people flinch at, kindly. An 8th house Mercury is a researcher of the underneath — motives, secrets, finances, grief, the sentence someone almost said. Surfaces bore you; subtext feeds you, and your mind naturally does the work most cultures outsource to therapists, detectives, and priests. In conversation you offer something rare: **a mind that does not look away**. People tell you things they have never said aloud, because they can feel you can hold it.\n\nThe growth edge is discretion in both directions. Words carry surgical weight in intimate rooms, so wield yours the way a good surgeon holds a blade — precisely, and only to heal, never to win. And practice reciprocity: you excel at excavating others while keeping your own archive sealed. **Speak one true thing about yourself** for every depth you sound in someone else. Intimacy is a trade route, not a one-way expedition.",
  },
  {
    title: "Mercury in the 9th House",
    body: "Your mind thinks in maps, not streets. A 9th house Mercury reaches for the big pattern — the philosophy under the news cycle, the grammar of a foreign language, the theory that finally explains the scattered facts. You are a natural teacher and a lifelong student, usually in the same conversation, and you carry **a translator's instinct for scale**: taking the huge idea and finding the doorway a beginner can walk through.\n\nThe growth edge is grounding. Vision without particulars floats; the audience nods and retains nothing. The practice is anchoring every big claim to **one specific, touchable example** — the story, the case, the Tuesday it happened to a real person — because that is how ideas travel farther than you do. And keep auditing your own syllabus: the beliefs you teach most confidently are due for review on a schedule. A mind this broad stays honest by staying enrolled.",
  },
  {
    title: "Mercury in the 10th House",
    body: "Your voice was built for the record. With Mercury in the 10th house, thinking and speaking are vocational instruments — the strategy memo, the public talk, the sentence people repeat in rooms you have already left. Your words carry consequence early and unusually far; you may become **the named voice of something larger than yourself**, and communication itself can be the career: writing, teaching, advocacy, translation between the top floor and the ground floor.\n\nThe growth edge is saying what you actually think. Visibility rewards caution, and a careful reputation built from borrowed, focus-grouped opinions is a rented house — impressive and never yours. The practice: **put your real position on the record**, at least once per season, especially where it costs a little. And guard an unpublished mind: journals, drafts, thoughts under no one's review. The public voice stays alive only if a private one keeps feeding it.",
  },
  {
    title: "Mercury in the 11th House",
    body: "You think best in the plural. An 11th house Mercury lights up in groups — brainstorms, forums, organizing meetings, the friend network that functions as a distributed brain. Your gift is synthesis: you hear ten voices and find the through-line no single speaker saw, and your ideas naturally aim at the future — **the world as it could be run**, not just as it is. You collect people through conversation and connect them like a switchboard with opinions.\n\nThe growth edge is protecting your strangeness. Consensus is warm, and a mind this collaborative can start pre-editing its weirdest thoughts to fit the room — but the odd notion you almost didn't say is usually **your actual contribution**. The practice: bring the unpolished idea to the group; let them sharpen it rather than sanding it yourself in advance. And notice which circles make you smarter versus merely agreeable. Choose the ones that argue with you lovingly.",
  },
  {
    title: "Mercury in the 12th House",
    body: "Your mind works in the dark like a photographer. A 12th house Mercury thinks in images, intuitions, and connections that surface whole after quiet — you often know things long before you can explain them, and your best ideas arrive sideways: in the shower, at the edge of sleep, on the empty morning walk. Words may lag behind knowing, which the loud world misreads as slowness. It is not. It is **development time**, and what develops is worth the wait.\n\nThe growth edge is building channels for a wordless intelligence. Uncaptured, these insights evaporate by breakfast; graded against quicker minds, they go silent entirely. The practice: keep the notebook by the bed, the voice memos, the poem, the prayer — **give the knowing somewhere to land** — and stop auditioning your intelligence in formats built for other brains. Some minds are wells, not fountains. Depth was never a deficit.",
  },
];

export const VENUS_IN_HOUSE: Interpretation[] = [
  {
    title: "Venus in the 1st House",
    body: "Charm is your handshake. A 1st house Venus makes warmth, taste, and a certain magnetism part of how you enter every room — people soften around you before you have said much, doors open a beat earlier, strangers confide. Beauty here is not vanity; it is **vocabulary**: how you dress, adorn, and carry yourself is a genuine language, and you are fluent. For anyone composing a self outside the standard catalogs, this placement is an ally — your presentation is art, and art is self-determination.\n\nThe growth edge is being loved past the entrance. A welcome this graceful can become a lobby you never let anyone leave — pleasant, lovely, and guarded. The practice is letting chosen people see **the unbeautiful hours**: the grief, the mess, the unphotogenic opinions. You will learn the difference between being admired and being known, and once you taste the second, the first becomes merely decorative.",
  },
  {
    title: "Venus in the 2nd House",
    body: "You have a gift for the good material world. Venus in the 2nd house loves texture, comfort, and quality — the perfect cup, the well-made coat, the room that feels like an exhale — and often knows how to fund them, because your taste and your income tend to speak the same language. Pleasure, in your chart, is **a value and not a guilty one**: you understand in your body that beauty is not extra. It is nourishment with better lighting.\n\nThe growth edge is the direction of worth. In a culture that prices everything, it is easy to let your things certify you — to feel diminished in lean seasons and inflated in fat ones. The practice is remembering the hierarchy: **you are the treasure the treasury exists to serve**. Enjoy abundance without being owned by it, share it without keeping score, and notice that your realest wealth — taste, warmth, the ability to savor — travels with you at every income.",
  },
  {
    title: "Venus in the 3rd House",
    body: "You fall for minds first. A 3rd house Venus flirts in wordplay, courts by conversation, and finds the daily neighborhood quietly full of romance — the bookshop, the banter, the message composed and recomposed until it lands just right. Affection, for you, needs articulation to feel real: **saying the sweet thing out loud** is not decoration on the love; it is the love, arriving. You keep friendships alive through sheer conversational devotion, and your letters — texts, notes, comments — are small works of art.\n\nThe growth edge is depth beneath the delight. Charm this verbal can keep every connection at the sparkling surface, where nothing is risked and nothing quite lands. The practice: past the banter, offer **one sentence with no armor in it** — the plain, unclever truth of what someone means to you. Wit opens the door; sincerity is what walks through. You are gifted at both. Use both.",
  },
  {
    title: "Venus in the 4th House",
    body: "Your love has an address. Venus in the 4th house makes home the center of pleasure — the beautiful table, the sheltering room, affection expressed as sanctuary offered. You love oldest and deepest: tenderness with roots, devotion with history, and the people you cook for know exactly who they are. Whatever family means to you — given, chosen, or lovingly rebuilt from scratch — you have a gift for making **a place where people finally exhale**.\n\nThe growth edge is letting the sanctuary circulate. A haven this lovely can close in on itself, hospitality reserved for the already-admitted while the drawbridge quietly stays up. The practice: **set an extra place** — invite the new friend into the inner rooms, let someone see the home mid-mess, and notice that the welcome deepens rather than breaks. And a permission worth framing: the home you build now, on your own terms, can be more truly ancestral than the one you inherited. Peace is also an heirloom. Start it.",
  },
  {
    title: "Venus in the 5th House",
    body: "Romance is your natural climate. Venus has her joy in the 5th house, and it shows: you love with flair — the grand gesture, the handmade gift, delight taken seriously as an art form. Whatever you create carries charm; whoever you love gets celebrated visibly, and pleasure in your hands becomes generous, warm, almost civic: **joy that recruits**. Dating, making, playing, adoring — these are not your distractions. They are your genius.\n\nThe growth edge is loving the ordinary Tuesday. A heart tuned to fireworks can mistake calm for boredom and drama for depth, wandering off just as real devotion begins its quieter second act. The practice: bring the artistry to the unremarkable stretch — **court the long middle** of a love, a craft, a friendship, where the audience is gone and the meaning concentrates. Fireworks start things beautifully. What you are learning is that embers, tended, are the more impressive fire.",
  },
  {
    title: "Venus in the 6th House",
    body: "You love in acts, not announcements. Venus in the 6th house shows devotion through service — the refilled prescription, the fixed hem, the calendar quietly rearranged around someone's hard week. Care, in your hands, is **logistics with a heartbeat**, and work itself can be a pleasure when the craft is beautiful: you beautify systems, workplaces, daily routines, turning maintenance into something close to ceremony. The people you love are, measurably, better maintained than they were before you.\n\nThe growth edge is receiving. Givers this fluent often go quietly unfed, having taught everyone around them that they need nothing — and usefulness can start to feel like the rent you pay for being loved. It never was. The practice: **let someone tend you** without narrating apologies, ask for the specific care you want, and rest in front of witnesses. You were lovable before you were helpful. The people worth keeping already know that.",
  },
  {
    title: "Venus in the 7th House",
    body: "Partnership is where your grace concentrates. A 7th house Venus is built for the duet — you harmonize, negotiate sweetly, and make others feel like finer versions of themselves in your company. Committed relating genuinely suits you, in whatever architecture you choose: this house holds marriages and it holds every bond two people design for themselves, and yours will be **designed, not defaulted**. You may also draw beautiful collaborators all your life — the co-author, the business partner, the friend who is practically a spouse.\n\nThe growth edge is honesty over harmony. A peacemaker this skilled can keep a peace by swallowing truths, until the relationship is smooth, pleasant, and quietly fictional. The practice: **say the disruptive true thing** while it is still small, and trust real love to survive real information. A kept peace built on your silence is only a slower conflict. The partnership that can hold your honesty is the one that deserves your grace.",
  },
  {
    title: "Venus in the 8th House",
    body: "You do not want pleasant; you want profound. An 8th house Venus loves at depth — merged finances, merged histories, the intimacy that requires removing more than clothes. Loyalty, once given, is nearly geological, and you offer partners something rare: **a love that does not flinch** at grief, desire, debt, diagnosis, or truth. Shallow connection leaves you lonelier than solitude, so you would rather have one fathoms-deep bond than a harbor of acquaintances.\n\nThe growth edge is trust without trials. Intensity can shade into testing — engineering small crises to prove the love is real, mistaking turbulence for depth and calm for indifference. The practice: **let love prove itself slowly**, in daylight, through ordinary reliability, and notice that steady is not shallow. Also, keep something sovereign: merge hearts, histories, even bank accounts if you choose, but hold one room of self unmerged. You remain yours even inside a profound us. That is what makes the us profound.",
  },
  {
    title: "Venus in the 9th House",
    body: "Your heart has wanderlust. Venus in the 9th house falls in love with horizons — foreign voices, thick books, the person who doubles as a doorway to another world. Shared belief is your real aphrodisiac: you want **a co-adventurer, not just a companion**, someone to argue philosophy with at midnight and board the early train with anyway. Love across distances, cultures, and differences is not a complication in your chart; it is frequently the whole point, and your affections have always been bigger than your hometown.\n\nThe growth edge is loving the mapped territory. A heart tuned to discovery can go restless the moment a person or place becomes familiar, mistaking knownness for the end of wonder. The practice: **learn the second geography** — the deeper strangeness inside the person you already know, the neighborhood layer under the one you have seen. Familiarity is not the death of the journey. Done right, it is the visa to the interior.",
  },
  {
    title: "Venus in the 10th House",
    body: "Grace is part of your résumé. A 10th house Venus brings charm into career — you are the diplomat, the tastemaker, the one whose presence opens doors that credentials alone cannot, and work touched by beauty becomes **your public signature**: art, design, advocacy, or peacemaking may literally be the job, or beauty may simply be how you do whatever the job is. People trust you visibly, early, and often before you have decided whether they should.\n\nThe growth edge is the gap between the polished self and the resting one. A public grace this reliable can become a uniform you forget how to take off, and reputations, however glowing, cannot hold your hand. The practice: keep loves that are **off the record entirely** — the friendship with no networking value, the art no client sees, the self that exists after the notifications stop. Be admired at work. Be known at home. Do not let the first replace the second.",
  },
  {
    title: "Venus in the 11th House",
    body: "Friendship is your art form. An 11th house Venus loves in networks — the gathered table, the group chat that never sleeps, romance that often begins as camaraderie and keeps friendship as its spine. You beautify whatever community holds you, and your ideals themselves are lovely: **a fairer, warmer future** is not an abstraction to you; it is a party you are actively planning. For hearts that found their people rather than inheriting them, this placement is home ground — chosen family is your masterpiece.\n\nThe growth edge is depth inside the breadth. A circle this wide can keep every bond at pleasant, the affection real but evenly distributed into weightlessness. The practice: **choose a few and go past pleasant** — the friendship that survives a hard conversation, the closeness with logistics and history and repair in it. Intimacy needs fewer people and more hours. Your community is the garden; make sure a few roots go deep enough to hold it.",
  },
  {
    title: "Venus in the 12th House",
    body: "You love the way tide loves shore — enormously, and half in secret. A 12th house Venus feels affection as something oceanic: compassion for strangers, devotion that asks nothing back, beauty found in solitude, music, dreams, the hour before everyone wakes. Your tenderness extends to people who will never know they received it, and there is genuine holiness in that — **love as a private practice**, kept like a monastery keeps a garden.\n\nThe growth edge is visibility and reciprocity. This placement can romanticize the hidden thing — the unavailable person, the unspoken devotion, the beautiful renunciation — until secrecy itself starts to feel like proof of love. It is not; it is only proof of hiding. The practice is simple and enormous: **let your love be visible, and let it be answered**. Choose people who can actually arrive. The sanctuary of your heart deserves at least one guest who stays, sees the whole altar, and worships back.",
  },
];

export const MARS_IN_HOUSE: Interpretation[] = [
  {
    title: "Mars in the 1st House",
    body: "You move first and explain later. A 1st house Mars puts the engine right behind your eyes — direct, physical, quick to start and quicker to defend, with a presence people feel as momentum before they learn your name. Your body wants **action as a first language**: walking off the anger, building the thing today, saying the hard sentence while others are still drafting theirs. Courage, for you, is less a virtue summoned than a reflex managed.\n\nThe growth edge is aim. Heat this available will spend itself on whatever is nearest — the slow line, the wrong argument — unless you point it deliberately at what deserves it. The practice: give the fire **a daily physical job** through training, making, or moving, so it arrives at conflicts already exercised, and pause one breath between impulse and launch. That single breath is the difference between force that reads as courage and force that reads as collision. You get to choose, every time.",
  },
  {
    title: "Mars in the 2nd House",
    body: "You fight for what you can hold. Mars in the 2nd house drives you to earn, build, and defend your ground — a steady, stubborn engine that works longer than anyone expects and takes threats to your livelihood or your worth personally, because they are personal. Your effort converts directly into material reality: **you make survival into structure**, and independence — the paid-off debt, the skill no one can repossess — is your favorite trophy.\n\nThe growth edge is what the engine is proving. Work can be building, or it can be endless testimony that you deserve to exist, and only you can hear the difference. The practice: aim the persistence at **building rather than proving** — set the finish lines yourself, celebrate crossings instead of moving them, and let some hours produce nothing but rest. Your worth predates your output. Defend it the way you defend everything else you own: fiercely, and as a matter of settled fact.",
  },
  {
    title: "Mars in the 3rd House",
    body: "Your weapon of choice is a sentence. A 3rd house Mars debates for sport, thinks at speed, and treats a good argument as a form of respect — you sharpen ideas by striking them together, and your quickest wit arrives exactly when a conversation heats up. Words come out hot, sometimes sharper than intended, and you likely learned young that **your voice is a power tool**: it can build a case, cut a path, or nick whoever is standing too close.\n\nThe growth edge is precision over volume. The point you make calmly is the one that actually lands; the one you make loudly gets remembered as noise, however right it was. The practice: **slow the send** — the message, the retort, the reply-all — by one honest rereading, and pick your battles like a sniper rather than a sprinkler. Your mind is a genuinely formidable instrument. Spend it on arguments worth winning, with people worth persuading.",
  },
  {
    title: "Mars in the 4th House",
    body: "Your fire burns on the home front. Mars in the 4th house defends family, territory, and roots with a ferocity the outside world rarely sees — you will work to exhaustion for the people under your roof, whoever you have chosen to put there, and threats to your foundations wake something ancient in you. Some of that heat is inherited: old household angers, **battles your lineage never finished**, still warm in the walls you grew up inside.\n\nThe growth edge is tending the hearth-fire honestly. Unacknowledged anger at home does not disappear; it smolders — sarcasm in the kitchen, silence at dinner, the renovation that is really a war. The practice: name the old grievances out loud, to a therapist, a journal, or the family members who can hear it, and **let the fight end with you** where it should. Your fierce protection is a gift. Aimed truly, it warms the house for generations instead of scorching it.",
  },
  {
    title: "Mars in the 5th House",
    body: "You create like it's a contact sport. A 5th house Mars pours drive into art, romance, and play — you pursue what delights you openly, court boldly, and compete at board games as if honor were on the table. Passion is your proof of life: the half-finished canvas attacked at midnight, the crush declared instead of endured, **desire treated as a verb**. There is nothing lukewarm in your joy, and people find it either alarming or magnetic, frequently both.\n\nThe growth edge is uncoupling delight from victory. When play becomes another scoreboard, losing poisons the fun and winning only resets it — and creativity made competitive stops being restorative. The practice: keep some arena where you are **gloriously mediocre on purpose** — the sport you play badly and love, the art with no audience — so joy remembers it never needed judges. Make the thing because making is the prize. That is the win no one can take.",
  },
  {
    title: "Mars in the 6th House",
    body: "Mars has its joy in the 6th house, and yours shows up gladly in the daily grind. You attack the task list, perfect the technique, and treat work as a worthy opponent — you likely outpace whole teams without noticing, and idle days register as physical discomfort, an engine idling in a closed garage. Your drive is at its best here: **effort with a craft to hone**, motion with a purpose, the body used and therefore quiet.\n\nThe growth edge is who the war is against. A worker this relentless can turn the campaign inward — grinding through illness, treating rest as desertion, making every imperfection a court-martial. The practice: give the body **motion it enjoys**, not just labor it survives; let maintenance count as achievement; and retire the idea that effort is owed as penance. You are the worker and the workplace. A good foreman protects the crew — especially when the crew is you.",
  },
  {
    title: "Mars in the 7th House",
    body: "You spark against other people, in both senses. A 7th house Mars brings heat into partnership — passionate alliances, productive friction, and a real talent for fighting alongside someone as fiercely as you occasionally fight with them. Conflict is intimacy's raw material here: the partners and collaborators who work for you are the ones who can **meet your fire without flinching**, and a relationship with no friction at all tends to read, to you, as a relationship with no pulse.\n\nThe growth edge is owning the anger as yours. Unclaimed, this placement projects — you keep meeting your own temper wearing other people's faces, drawn to combative partners who conveniently carry the heat for two. The practice: **claim the first spark** — say I am angry before it becomes you always — and learn fair fighting as a craft: clean openings, no archives dredged, repair afterward as non-negotiable. Fought fair, your fire does not burn partnerships down. It forges them.",
  },
  {
    title: "Mars in the 8th House",
    body: "Your will works underground, like a root splitting stone. An 8th house Mars is strategic, patient, and unafraid of the crises that send others running — you fight best where the stakes are naked: trust, money, survival, truth. Emergencies clarify you; while a room panics, something in you goes quiet and begins operating. You have **a talent for the unbearable**, and the people who have been through real fire with you never forget who held.\n\nThe growth edge is power owned in the open. Until you claim your force directly, it tends to move sideways — power struggles that find you, contests over money or control, intensity leaking where honesty would have served. The practice: **want what you want out loud** — name the stakes, negotiate in daylight, and spend your depth on chosen battles rather than inherited ones. Owned, your intensity becomes the rarest kind of strength: the calmest person in any storm, and part of the reason it passes.",
  },
  {
    title: "Mars in the 9th House",
    body: "You crusade. A 9th house Mars puts muscle behind belief — defending ideas, chasing horizons, booking the flight while everyone else is still weighing the pros. Conviction gives your drive its direction: you will fight harder for a principle than for a paycheck, and injustice reads to you as a personal summons. At your best you are **courage with a compass** — the advocate, the pilgrim, the one who actually goes.\n\nThe growth edge is righteousness, which is conviction gone rancid. A warrior of belief can slide from fighting for the truth into fighting for being right, and the two feel identical from the inside. The practice: **audit the crusade regularly** — is this still true, or merely still mine? — and keep one genuine friendship with someone who disagrees with you well. Fight for your truths with everything you have. Just let them remain open cases, the way every honest truth is.",
  },
  {
    title: "Mars in the 10th House",
    body: "Ambition, in you, is load-bearing. Mars in the 10th house climbs — your drive aims straight at achievement, authority, and a public mark, and you would rather lead than wait to be led. Obstacles read as instructions; being underestimated reads as fuel. You are built for **visible, accountable effort**: the career as a mountain range rather than a single mountain, and a reputation for getting things done that begins forming remarkably early.\n\nThe growth edge is choosing summits that feed the climber. A drive this strong will conquer whatever peak is placed in front of it — including inherited ones, prestige for its own sake, victories that arrive hollow at altitude. The practice: before each ascent, ask **who am I becoming on the way up**, and audit yearly whether the mountain still means anything. Also: rest is not descent. Even the strongest climbers acclimatize. Choose meaningful mountains, and your ambition becomes indistinguishable from purpose.",
  },
  {
    title: "Mars in the 11th House",
    body: "You fight for the group photo, not the portrait. An 11th house Mars channels drive into collective aims — organizing the effort, championing the cause, pushing friends toward the futures they keep postponing. You make an electric ally and a formidable movement-builder: **the friend who actually shows up** with the truck, the plan, the fury on your behalf. Shared purpose multiplies your force; alone you are strong, but in a coalition you are weather.\n\nThe growth edge is choosing your battles rather than inheriting them from the room. Circles hand their fiercest member the sword by default, and you can wake up mid-campaign in a war you never personally examined. The practice: before enlisting, ask **is this fight mine, and why** — your fire deserves your own reasons. And let the group fight for you occasionally; a champion who cannot be defended becomes a resource, not a member. You belong to the circle too.",
  },
  {
    title: "Mars in the 12th House",
    body: "Your strength moves like an undertow — real, but hard to see from shore. A 12th house Mars acts behind the scenes: you fight for the voiceless, labor in institutions and back rooms, and often cannot fully explain what fuels you, only that something does. Your finest victories may be **wins no one ever sees** — the crisis quietly averted, the person privately carried, the battle with yourself that ended in mercy.\n\nThe growth edge is anger given honest work. Unclaimed, this placement's fire turns inward as exhaustion and self-sabotage, or leaks sideways at strangers; you may not even register the anger until the body files its report. The practice: **assume the anger exists and give it a channel** — service, art, disciplined physical practice, advocacy for those who cannot advocate for themselves. Named and employed, the hidden warrior becomes tidal: a quiet, enormous power that moves whole coastlines without ever raising its voice.",
  },
];
