import type { Interpretation } from "./types";

export const JUPITER_IN_SIGN: Interpretation[] = [
  {
    title: "Jupiter in Aries",
    body: "Your faith grows by moving. With Jupiter in Aries, belief isn't something you inherit or reason your way into — it's something you discover mid-leap, when the doubt hasn't caught up yet. You learn what you trust by acting on it: the move to a new city, the name you claim, the project you start before anyone gives permission. **Courage is your teacher**, and your enthusiasm has a way of unlocking rooms — people find their own nerve by standing near yours.\n\nThe growth edge is pacing, not restraint. Nobody needs you smaller; they need you able to stay. Practice letting one horizon ripen before the next one calls, and notice that **finishing is also a form of daring** — often the scarier one. You have permission to want big and to want first. Just let some of what you start become somewhere you actually live."
  },
  {
    title: "Jupiter in Taurus",
    body: "Abundance, for you, has weight and texture. Jupiter in Taurus grows the slow way — compounding, rooting, ripening — and your generosity usually arrives as something a person can hold: a meal cooked without occasion, money lent without ceremony, a couch that has saved more lives than anyone admits. You trust what accumulates through tending, and **your steadiness is itself a kind of wealth** that people lean on more than they say.\n\nThe growth edge is the difference between accumulating and arriving. Enough is a real place; you're allowed to notice when you're standing in it. The practice is **pleasure without a permission slip** — letting the body, the garden, the good bread count as spiritual life rather than its reward. What you build slowly, you get to enjoy slowly. That's not indulgence. That's the whole point of the harvest."
  },
  {
    title: "Jupiter in Gemini",
    body: "Your faith multiplies by asking. Jupiter in Gemini sits in the sign opposite its home turf, and the old texts call that detriment — but lived from the inside, it means **meaning comes to you in plural**. Ten curiosities bloom where one belief might have stood. You collect languages, frameworks, half-finished courses, and conversations that rearrange your furniture, and you make the big questions feel talkable instead of towering.\n\nThe friction is real: breadth can become a way of never being pinned down, never having to say this one, this is mine. The growth edge is **choosing a few questions worth living inside**, not just visiting — letting depth accumulate in two or three places while the curiosity keeps roaming everywhere else. You have permission to be a person of many minds. Just build at least one of them a home."
  },
  {
    title: "Jupiter in Cancer",
    body: "Jupiter is exalted in Cancer, and it shows: generosity comes to you like breathing. You grow by taking people in — the friend between apartments, the kid nobody else claimed, the chosen family assembled one dinner at a time. **Care is your philosophy and memory is your scripture**; you remember what people love, what hurt them, what they said they wanted back when they didn't believe they could have it. Abundance gathers wherever you make room at the table, and the table keeps getting longer.\n\nThe growth edge is circulation. Nourishment that only flows outward eventually runs the well dry, and martyrdom is a poor inheritance to pass on. The practice is **letting yourself be fed** — receiving with the same grace you give, asking before the need becomes an emergency. Belonging you help build is allowed to hold you too. That isn't taking. That's how the exaltation completes itself."
  },
  {
    title: "Jupiter in Leo",
    body: "You believe in big-heartedness the way others believe in gravity. Jupiter in Leo expands through play, praise, and the courage to be seen — your optimism performs, in the best sense, warming whatever room it enters. You give lavishly: attention, celebration, the exact compliment someone has been starving for. And **your visibility is a public service**, whether or not anyone frames it that way — every time you take up space as yourself, somebody watching learns it can be survived, even enjoyed.\n\nThe growth edge is letting the applause be a byproduct rather than the fuel. When recognition runs late — and it will, sometimes — the practice is **generosity that doesn't check the mirror**: creating because the making delights you, loving loudly because that's your native volume. You have permission to be magnificent on an ordinary Tuesday, unwitnessed. The gold doesn't stop being gold when the lights are off."
  },
  {
    title: "Jupiter in Virgo",
    body: "You grow in increments, and you distrust growth that skips them. Jupiter in Virgo carries an honest tension — the planet of more housed in the sign of enough, done correctly — and the old texts call it detriment. But watch what you actually do: you make big ideas usable. **Refinement is your form of abundance**. The sprawling vision becomes a checklist, the movement becomes a mutual-aid spreadsheet, the healing becomes a practice someone can do on a Wednesday. That translation is rare and it matters.\n\nThe growth edge is letting good-enough ship. Perfectionism will tell you that expansion must wait until the details are worthy; it's lying, and it will keep you small forever if you let it. The practice is **improving in public** — releasing the draft, teaching the half-mastered skill, trusting that refinement can continue past the beginning. Your care is the gift. It doesn't need to be flawless to be nourishing."
  },
  {
    title: "Jupiter in Libra",
    body: "Meaning arrives for you in pairs. Jupiter in Libra grows through relationship — the right conversation partner can double your world overnight, and your best thinking happens out loud, in the space between two minds. You have a gift for **fairness at scale**: widening the circle where others draw lines, making the room bigger instead of guarding the door, believing beauty and justice are related disciplines. People trust you to hear both sides because you actually do.\n\nThe growth edge is the uncosigned decision. Sometimes expansion requires a choice no one else will bless in advance — and waiting for consensus can quietly become a way of outsourcing your own life. The practice is **taking a side and surviving it**: naming your preference before polling the room, letting a relationship wobble under an honest no. Balance isn't the absence of your weight. It includes you, fully placed."
  },
  {
    title: "Jupiter in Scorpio",
    body: "You don't want a wider world; you want a deeper one. Jupiter in Scorpio finds abundance underneath — in the truths people avoid, the intimacies that cost something, the resources everyone else overlooked because they wouldn't look down. Your faith is **forged, not inherited**: whatever you believe, you believe because it survived the worst night of your life. That gives your trust real weight. When you say I've been there, the words hold.\n\nThe growth edge is circulation over vaulting. What you excavate multiplies when it's brought into the light — the hard-won insight shared, the shame composted into someone else's permission slip. The practice is **letting depth become generosity**: telling the truer story, teaching from the scar rather than guarding it. You have permission to keep some rooms private. But the treasure was never meant to stay buried; you were meant to be the one who knows the way back down."
  },
  {
    title: "Jupiter in Sagittarius",
    body: "Jupiter is home here, and you can feel it: the horizon behaves like an invitation addressed to you. Meaning is your native appetite — travel, study, cosmology, the bigger story behind the story — and luck genuinely does seem to find you mid-journey, on the road you took instead of the sensible one. **Your hunger for meaning is the compass**, not a flaw to manage. You were built to ask what it's all for, and to go find out in person.\n\nThe growth edge is the difference between a search and a sermon. Truth held too tightly stops breathing; the moment you're certain, you've stopped traveling. The practice is **staying a student on purpose** — letting new evidence reopen old conclusions, letting people surprise your philosophy. You have permission to believe hugely and revise freely. The faith that can update itself is the only kind that lasts the whole trip."
  },
  {
    title: "Jupiter in Capricorn",
    body: "Your optimism wears work boots. Jupiter is in fall in Capricorn — the old astrologers considered it a hard seat for the planet of plenty — and yes, hope has to be earned here, audited, load-tested. You don't trust promises; you trust plans. But look at what that skepticism builds: **belief with a foundation under it**. When you finally say this will work, whole rooms reorganize around your confidence, because everyone knows you don't say it lightly.\n\nThe growth edge is letting yourself want more than the proven. Scarcity logic will call every dream a liability and every rest a risk; it kept someone in your lineage alive once, and it doesn't know the emergency is over. The practice is **hoping ahead of the evidence**, just slightly — one commitment made before the guarantee arrives. You have permission to want abundantly. Wanting is not a debt you'll be called on."
  },
  {
    title: "Jupiter in Aquarius",
    body: "Your faith is wide-angle. Jupiter in Aquarius grows through the collective — ideas that belong to everyone, futures nobody has built yet, friendships that double as movements. Abundance, for you, means **access rather than accumulation**: the open-source fix, the resource list passed hand to hand, the door propped so the next person doesn't have to knock. You think in systems and believe in people-plural, and your outsider vantage is precisely what lets you see what the room is missing.\n\nThe growth edge is staying warm inside the big idea. Humanity is easiest to love at a distance and hardest at the group chat; ideals can become a very sophisticated way of avoiding one particular person's needs. The practice is **loving at close range** — one friend, one meal, one unglamorous act of showing up that no framework gets credit for. The future you're building is made of exactly those Tuesdays."
  },
  {
    title: "Jupiter in Pisces",
    body: "Jupiter rules Pisces in the old language, and the generosity here is oceanic. You grow through compassion, imagination, surrender — faith less like a doctrine and more like **water finding its level**, moving toward whoever is lowest and needs it most. Strangers tell you their whole story in line at the pharmacy. Art expands you; so does grief, honestly held. You understand that mercy is not a reward for the deserving but a climate, and you carry that climate with you.\n\nThe growth edge is a shoreline. Boundless giving eventually stops being giving and becomes dissolving — and you cannot be anyone's ocean if you've evaporated. The practice is **compassion with edges**: hours that end, a no that holds, help that doesn't require your disappearance. You have permission to be finite. The tide is not less holy for having a coast; the coast is what makes it a tide at all."
  }
];

export const SATURN_IN_SIGN: Interpretation[] = [
  {
    title: "Saturn in Aries",
    body: "Saturn is in fall in Aries, and the friction is real: the part of you built to charge got issued a governor. Early on this can feel like driving with the brake down — hesitation right at the moment of ignition, anger that arrives late or sideways, a strange shyness about wanting things first and out loud. The instinct isn't missing. It's **being tempered, not extinguished** — apprenticed to timing.\n\nWhat matures here is rare: courage with follow-through. Most people can start; you're learning to start and stay, to lead at a temperature you can sustain past the adrenaline. The practice is small, frequent acts of self-assertion — ordering first, naming the preference, taking up the space before you've fully justified it. **Your anger is information**, not a liability to manage into silence. By the second half of life, patience stops feeling like a cage and reveals itself as what it always was: your weapon."
  },
  {
    title: "Saturn in Taurus",
    body: "Security is your curriculum. Saturn in Taurus builds slowly and doubts quickly — you may fear there's never quite enough even with the pantry full, and the body can hold that vigilance as tension it never agreed to carry. Somewhere along the line, resources felt conditional: money, comfort, maybe safety in your own skin. So you learned to build for permanence, and **what you build actually holds** — friends borrow your steadiness the way they'd borrow a truck.\n\nThe mastery on offer is stewardship rather than hoarding: resources tended across decades, comfort earned into something no one can repossess. The practice is recalibrating the gauge — measuring wealth by steadiness instead of by the anxious count, spending a little on pleasure to prove the sky stays up. **The scarcity story loses its narrator** the moment you notice you've already survived. You're allowed to live in the house, not just guard it."
  },
  {
    title: "Saturn in Gemini",
    body: "You take words seriously — sometimes so seriously they jam. Saturn in Gemini often begins as doubt about your own voice: the sense that you must triple-check before speaking, that your quickness is suspect, that everyone else got a fluency you were denied. Maybe school made an example of you; maybe your way of thinking simply didn't match the room's tempo. Whatever the origin, **the doubt was never a verdict** — it was an apprenticeship you didn't know you'd enrolled in.\n\nWhat it matures into is precision: you become the person whose sentences hold weight because each one was checked, the writer people trust, the explainer of hard things. The practice that gets you there is saying the imperfect thing sooner — the rough draft aloud, the question you fear is stupid. **Fluency is built, not bestowed**, and every stumble is a brick. Your voice is a structure. Structures take time, and then they last."
  },
  {
    title: "Saturn in Cancer",
    body: "Saturn is in detriment in Cancer, and the story usually starts early: somewhere, softness learned to wear armor. Perhaps care came with conditions, or home was a place you managed rather than rested in, so you became competent at nurture-as-logistics while keeping your own tenderness in a locked drawer. The walls went up around the very thing you wanted most — **belonging** — and walls, famously, don't distinguish between threats and guests.\n\nThe work of a lifetime here is installing doors. You have a genuine gift for making care reliable: rituals of family, chosen or given, that don't evaporate when moods shift — the standing dinner, the holiday invented from scratch, the home built on decision rather than luck. The practice is **letting being held count as strength**: asking for comfort in words, receiving it without immediately reciprocating. The fortress can become a hearth. Same stones, warmer architecture."
  },
  {
    title: "Saturn in Leo",
    body: "The stage is yours; the stage fright came bundled. Saturn in Leo — the planet of scrutiny in the sign of shining — can make visibility feel like an exam you must pass before you're allowed to be seen enjoying yourself. Maybe your early light got dimmed by someone who found it inconvenient, and you concluded that radiance must be earned, deferred, justified. So you rehearse. You over-prepare. You wait to be excellent before you let yourself be visible.\n\nHere's what the placement actually builds: **earned radiance that outlasts every natural spotlight**. Your creative authority is laid rep by rep, each risk of being seen setting another course of brick, until the confidence is structural — no one can revoke what you constructed yourself. The practice is shining before you feel ready: the open mic, the outfit, the idea pitched at eighty percent. **Joy is not a performance review**. You're allowed in the light while still learning it."
  },
  {
    title: "Saturn in Virgo",
    body: "Your standards arrived before your confidence did. Saturn in Virgo doubles the precision — an eye that catches every flaw, including and especially yours — and turns work into both refuge and courtroom. You're the one who reads the footnotes, tests the method, fixes the thing quietly before anyone notices it was broken. Turned outward, this is mastery: **craft that simply holds**, the quiet authority of work no one has to double-check.\n\nTurned inward, the same instrument corrodes. The inner auditor never files a final report; there is always another flaw, and a life can be spent in revisions. So the discipline you actually need — and it is a discipline, requiring the same rigor you bring to everything — is **mercy, applied on schedule**. Rest before the list is done. Praise counted as data, not noise. Let useful be the standard instead of immaculate. The work was never the problem. The sentence you serve alongside it is."
  },
  {
    title: "Saturn in Libra",
    body: "Saturn is exalted in Libra, and the work it does here is judgment in the oldest, best sense: the careful weighing of what is actually fair. You take commitment seriously — contracts, vows, the precise cost of a promise — and you're constitutionally unable to pretend an imbalance isn't there. Others treat harmony as a mood; you build it like a **load-bearing wall**, and relationships in your orbit tend to become more honest because you're in them.\n\nThe maturation this placement asks for is learning that a firm no is also an act of justice. Fairness that always resolves in the other person's favor isn't fairness — it's self-erasure with good manners. The practice is **putting your own weight on the scale**: naming your terms early, letting a bond survive your honest disagreement, ending what can't be made equitable. You were built to be a keeper of right relationship. That includes the one with yourself."
  },
  {
    title: "Saturn in Scorpio",
    body: "You hold intensity the way an engineer holds high voltage: respectfully, with protocols. Saturn in Scorpio usually learns early that trust is expensive — that what you reveal can be used, that merging has terms nobody reads aloud — so you ration disclosure and keep the deepest rooms locked. People sense the depth in you anyway. It's why they bring you their unsayable things: **you can hold what would break lighter containers**.\n\nThe mastery available here is profound — intimacy with structural integrity, emotional depth that doesn't buckle under pressure, loyalty that means something because you've counted its cost. But control kept past its usefulness becomes the cage, and vigilance can outlive every threat it was built for. The practice is **scheduled vulnerability**: one truth told before it's forced out of you, one person given the tour of a locked room. Trust, extended deliberately, is not naivety. From you, it's the highest engineering."
  },
  {
    title: "Saturn in Sagittarius",
    body: "Your beliefs must pass inspection. Saturn in Sagittarius refuses inherited faith — every philosophy you hold, you hold because it survived your testing, and everything handed down got sent to the lab first. From the outside this can look like doubt or contrarianism. It's actually rigor: you've watched people get hurt by unexamined certainty, maybe been hurt by it yourself — the doctrine that had no room for you, the promised meaning that didn't deliver — and you decided **truth should have to earn its keep**.\n\nWhat you become, in time, is the rare thing: an honest authority on meaning, whose optimism has a foundation under it. Students and seekers trust you precisely because you won't sell them certainty. The practice is letting yourself believe before the audit is fully complete — **faith as a working hypothesis**, lived provisionally, revised freely. Conviction doesn't require perfection. It requires enough evidence to take the next step, and you've had that for a while."
  },
  {
    title: "Saturn in Capricorn",
    body: "Saturn is home in Capricorn, and you carry its architecture in your posture. Responsibility found you young — maybe too young — and you learned to be the reliable one before you learned what you liked for breakfast. But the dividend is real: **time is your ally** in a way it is for almost no one else. You build careers, reputations, whole selves designed to stand for decades, and the things you commit to at thirty are still standing at sixty, weathered and worth more.\n\nThe lesson here was never work harder; you had that mastered by adolescence. The lesson is noticing when the structure is strong enough to hold you, too — when the scaffolding can come down and someone can actually live in the building. The practice is **rest without a permission slip**, delegation without dread, ambition pointed at what you'd want even if no one were keeping score. You've paid the entrance fee several times over. Come inside."
  },
  {
    title: "Saturn in Aquarius",
    body: "In the old system Saturn rules Aquarius, and you can feel the pairing: ideals with load calculations. You don't just imagine better systems — you draft them, stress-test them, and commit to them for the long haul, which makes you invaluable to every collective you join. Your detachment is **method, not coldness**: the ability to step back from the group's weather and see its structure is exactly what lets you fix what everyone else only complains about.\n\nThe growth edge is remembering the people inside the diagram — including yourself. Principles can become a fortress; being the perennial observer can quietly calcify into being the perennial outsider, even in rooms that would gladly hold you. The practice is **belonging on purpose**: joining as a member and not only as the architect, letting a community see you unfinished, needing something. The system you're most responsible for maintaining is the web of your own attachments. Give it the same rigor."
  },
  {
    title: "Saturn in Pisces",
    body: "You're building a container for the sea. Saturn in Pisces gives form to what usually escapes it — grief, compassion, imagination, the ambient sorrow of the world that you pick up like a radio picks up static. The task can feel like fencing fog, and early on the porousness may have read as weakness: too sensitive, too much, too easily flooded. It was never weakness. It was **an aptitude waiting for its architecture**.\n\nThe mastery here is real and specific: boundaries that make empathy sustainable, art with a spine, spiritual practice with a schedule. The mystic who keeps office hours does more good than the one who dissolves. So the practice is structure in service of the sea — named feelings, kept hours, a discipline that returns you to shore before the tide decides for you. **Structure is how compassion becomes usable**, how the flood becomes irrigation. You're allowed to be both boundless and bounded. That's the whole assignment."
  }
];

export const URANUS_IN_SIGN: Interpretation[] = [
  {
    title: "Uranus in Aries",
    body: "Your rebellion starts things. Uranus in Aries breaks patterns by simply leaving — a genius for the clean start, the abrupt pivot, the door invented on the way out of the room. You and your cohort woke up early to the idea that the self is not assigned but authored: identity as an act of initiative, life as something you begin again as many times as necessary. **Daring first is your public service** — others locate their own nerve by watching you spend yours.\n\nThe refinement this placement asks for is direction. Rupture is a skill you've mastered; the growth edge is making sure each break serves a trajectory and not just an exit, that the fire clears ground for something you actually intend to plant. The practice is naming what you're for, not only what you're done with. **Freedom with a destination** is still freedom — it just accumulates instead of evaporating."
  },
  {
    title: "Uranus in Taurus",
    body: "You revolutionize slowly, which is still revolution. Uranus in Taurus is the earthquake in the garden — sudden change arriving through the most fixed things: money, land, food, values, **the body itself as a site of invention**. Your generation is rewriting what security even means when the old containers stop holding, and you personally carry the tension in miniature: craving stability while being sent, again and again, to disrupt it.\n\nThe genius here is rebuilding foundations others assumed were permanent — new economics, new relationships to ground and flesh, ownership reimagined as stewardship. The practice is befriending the tremor instead of bracing against it: when the quake comes for something you were gripping, ask what it's freeing your hands for. **Stability isn't the absence of change; it's the ability to re-root**. You're allowed to love the garden and still let lightning redesign it. Some soil only becomes fertile after the shaking."
  },
  {
    title: "Uranus in Gemini",
    body: "Your mind runs on a faster current. Uranus in Gemini electrifies language — ideas arrive in flashes, connections leap categories without a passport, and the way you phrase a thing can change what a whole room is able to think. You belong to a cohort rewiring how information itself moves, and in your own life it shows up concretely: **the reframe that frees someone**, the question nobody else thought was askable, the joke that smuggles in the truth.\n\nBoredom is your only real hazard — a mind like this left unstimulated will disassemble something just to watch the parts. The practice is feeding the signal deliberately: strange inputs, cross-disciplinary reading, conversations above your current altitude. And patience with the lag, because **the world catches up to your sentences eventually** — usually about the time you've moved on to the next one. Keep the receipts. Say the early thing anyway. Being ahead only looks like being wrong for a while."
  },
  {
    title: "Uranus in Cancer",
    body: "You're rewriting what home means. Uranus in Cancer disrupts the inherited blueprint — family done differently, roots that stay portable, belonging built on invention rather than obligation. Maybe the household you came from ran on rules that didn't fit anyone in it; maybe you've moved enough times to know that **home is a verb**, something you do rather than somewhere you're owed. What looks like restlessness from the outside is actually research.\n\nThe finding, when it comes, tends to be original: chosen family with its own holidays, a nest that travels, care structured around freedom instead of surveillance. Your liberty and your need for shelter were never at war — you're designing the architecture that holds both, and others will borrow the blueprints. The practice is letting yourself land somewhere before it's perfect: **belonging is built by staying** a little longer than the escape reflex prefers. Roots don't have to be chains. Yours can be wings that rest."
  },
  {
    title: "Uranus in Leo",
    body: "Your individuality refuses the standard costume. Uranus in Leo electrifies self-expression — creativity that startles, romance that breaks form, a heart that treats originality as a birthright rather than a brand. The friction is honest and lifelong: wanting to be adored and needing to be free, craving the warm center of attention while refusing every script that usually earns it. **You'd rather be genuinely strange than approximately loved**, and that instinct is correct.\n\nThe art is finding the audience that loves the lightning — the people who don't flinch when you reinvent, who applaud the new self instead of mourning the old one. They exist; your job is to stop auditioning for the ones who don't. The practice is expressing before the concept is respectable: the weird project, the unsanctioned joy, love declared in your own grammar. **Your shine is not negotiable**, only its witnesses are. Choose them accordingly."
  },
  {
    title: "Uranus in Virgo",
    body: "You see the flaw in the system before the system does. Uranus in Virgo brings genius to the practical — reinventing how work works, how health heals, how details assemble into function. Your cohort dismantled the idea that the standard workday, the standard diet, the standard body were laws of nature, and you carry that instinct personally: an eye that spots the broken process and **hands that can't help but fix it**.\n\nThe friction is that your improvements can read as criticism to slower rooms — the suggestion heard as an accusation, the innovation received as an insult to how it's always been done. They're not criticism. They're **care delivered at high frequency**, and the practice is translation: leading with the shared goal, letting people keep their dignity while you upgrade their tools. And turn the genius homeward sometimes. The routines that run your own life deserve the same brilliant renovation you give everyone else's."
  },
  {
    title: "Uranus in Libra",
    body: "You're redesigning partnership from inside it. Uranus in Libra questions every default — who commits, how, on what terms, whether the old templates deserve their tenure — not to avoid love but to make it honest. Convention fits you like a borrowed suit; your cohort normalized leaving what didn't work and inventing what wasn't offered, and you personally have a gift for **relationships that breathe**: closeness without capture, devotion that doesn't require anyone's disappearance.\n\nThe practice is keeping the freedom mutual and spoken. Innovation in love only works as a shared document — space taken without explanation reads as exit, and revolutions announced mid-argument read as escape hatches. So negotiate in daylight: name the design, revisit the terms, let your person be a co-author rather than a subject of the experiment. **Honest structure is the radical act**. The couple form isn't sacred, but the consent inside whatever you build instead — that is."
  },
  {
    title: "Uranus in Scorpio",
    body: "Uranus runs hot in Scorpio — some traditions even call it exalted here — and the awakening is wired straight into the depths. You break taboos the way others break silence: because **something true is trapped under there**, and you can hear it knocking. Sex, death, power, money, the merged and the forbidden — the rooms most people seal off are precisely where your electricity goes to work, and your cohort dragged whole categories of the unspeakable into daylight.\n\nSudden endings and reinventions punctuate your story, and it's worth saying plainly: each one liberated something, even the ones that arrived as catastrophe. Your genius is **transformation without permission slips** — you don't wait for the culture to approve your becoming. The practice is choosing some ruptures on purpose, before pressure chooses them for you: the honest conversation early, the small controlled burn instead of the wildfire. Voltage this high wants a conduit. Build one, and you become the storm that powers the grid."
  },
  {
    title: "Uranus in Sagittarius",
    body: "Your beliefs come with an ejector seat. Uranus in Sagittarius liberates meaning itself — faiths examined mid-flight, philosophies swapped when the old map stops matching the road, the sacred found in places no institution licensed. You and your cohort scattered spiritual authority to the winds, and personally you carry the gift of **waking people from certainty**: one good question from you and a lifelong dogma develops a crack that lets the light in.\n\nThe gift is truth that stays alive; the hazard is a horizon addiction that never lets anything ripen. The practice is landing occasionally — long enough to build on one belief, to let a philosophy be tested by ordinary time rather than abandoned at the first plateau. **Commitment is not the death of freedom**; it's freedom choosing a direction long enough to arrive somewhere. You're allowed to keep the ejector seat. Just notice how rarely you actually need it once the flying is yours."
  },
  {
    title: "Uranus in Capricorn",
    body: "You dismantle from the inside. Uranus in Capricorn learns the structure first — the rules, the ladder, the load-bearing assumptions — then renovates while everyone is still in the building. Authority doesn't intimidate you; **unexamined authority offends you**, and your cohort came of age watching institutions crack, which taught you both their fragility and their blueprints. Your revolution wears a suit, arrives on time, and reads the bylaws before rewriting them — which is exactly why it works.\n\nThe growth edge is remembering that you're allowed to build, not only to renovate. Perpetual critique of structures can become its own cage, a way of always working on the house and never living in one. The practice is **constructing the alternative** — the organization, the practice, the career that runs on your actual values — and letting it be imperfect at launch. The old world doesn't fall to arguments. It falls to working prototypes, and you were born to ship them."
  },
  {
    title: "Uranus in Aquarius",
    body: "Uranus is home here, and the signal comes through clean. Your originality isn't a phase or a pose — it's the operating system. You think in futures, organize in networks, and treat every consensus as a first draft; your cohort wired the world together and then immediately started questioning the wiring. In your own life it means **the outsider vantage is your instrument**: you see the group's blind spot precisely because you've never fully dissolved into any group.\n\nThe discipline worth keeping is both-and: stay strange and stay connected. Detachment this fluent can drift into exile without noticing — brilliance broadcasting from orbit, admired and unheld. The practice is **letting particular people matter**: one friendship deep enough to be inconvenient, one community you commit to past its first disappointment. The future you can see so clearly is only worth building if you're in it, warm-blooded and belonging. Bring yourself along. That's the radical part."
  },
  {
    title: "Uranus in Pisces",
    body: "Your awakenings arrive like weather — sudden clarity out of fog, intuition striking with the force of fact, the dream that solves what the meeting couldn't. Uranus in Pisces electrifies the imagination: compassion that disrupts, art that arrives ahead of its own explanation, spiritual insight that skips the institutional queue entirely. You loosen what was stuck by dissolving it, and your cohort quietly rewired how a whole era imagines, grieves, and believes.\n\nThe practice is treating the flashes as data. A knowing this sudden is easy to dismiss — too weird, too sourceless, no citation available — but **your intuition has a track record**; audit it and see. Keep a channel open on purpose: the notebook by the bed, the walk without a podcast, the studio hours guarded like appointments. And ground the lightning somewhere real — **make the vision touchable** as a song, a practice, a kindness with a date on it. Revelation wants a body. Lend it yours."
  }
];

export const NEPTUNE_IN_SIGN: Interpretation[] = [
  {
    title: "Neptune in Aries",
    body: "You dream in first person. Neptune in Aries spiritualizes the will itself — the self as a quest, courage as a form of devotion, identity as something glimpsed in vision before it's built in fact. Inspiration hits you like a starting gun: the calling arrives whole, luminous, urgent, and your gift is that you actually move on it while others are still journaling about theirs. **The dream and the deed live close together** in you.\n\nThe subtle work is discernment, because not every summons is sacred — some callings belong to the soul, and some are adrenaline wearing a halo. The practice is a short waiting period between vision and launch: three days, one trusted friend, a single honest question — who does this serve? What survives that small delay is usually real. **Your longing is a compass, not an emergency**. Follow it with your eyes open, and the quest becomes a life instead of a chase."
  },
  {
    title: "Neptune in Taurus",
    body: "The sacred, for you, is touchable. Neptune in Taurus finds transcendence in the material world — a garden at dusk, bread rising, weight in the hands, **the body as an honest altar**. You don't need the dimmed room and the incense to reach the numinous; it's in the produce aisle if the light is right. This is a genuine spiritual aptitude, and a countercultural one: matter isn't the opposite of spirit in your cosmology. It's the medium.\n\nThe blur to watch is the dream of security — money, land, comfort imagined so vividly that the fantasy of what they'll finally deliver floats free of arithmetic. Enchantment around resources can leak: the purchase that promises transformation, the number that keeps moving. The practice is **groundedness as mysticism**: real budgets, real soil, pleasure taken in what's actually here rather than what's perpetually almost. Tend what you can touch. The holiness you're reaching for has been in your hands the whole time."
  },
  {
    title: "Neptune in Gemini",
    body: "Language is your fog and your lantern. Neptune in Gemini makes the mind porous — poetry comes easily, metaphors arrive unbidden, and the membrane between what you know and what you've beautifully imagined stays permanently thin. You can enchant a room mid-sentence; you can also enchant yourself, which is where it gets interesting. **Words, in your hands, are spells**, and spells work whether or not the caster is paying attention.\n\nThe devotion this placement asks for is precision in service of the magic, not instead of it. Check the facts you most want to be true — those are exactly the ones the fog gathers around. Cite the source, notice when a story has improved in the retelling, let I don't know be a complete sentence. None of this dims the gift; it grounds the wire so more current can run. **The lantern only works because it has glass around the flame**. Keep yours clean, and your sentences will light real roads."
  },
  {
    title: "Neptune in Cancer",
    body: "You carry an idealized home somewhere behind the sternum — a belonging so complete it may never have existed and never stops mattering. Neptune in Cancer makes care itself mystical: family as sanctuary, memory as sacrament, the kitchen table as the true chapel. You feel the ache of the almost-home in old songs and other people's holidays, and that ache is not pathology. It's **homesickness for a place you're meant to build**.\n\nThe practice is anchoring the vision in the household you actually have — imperfect, particular, alive — rather than holding out for the shimmering one that keeps receding. Nostalgia can embalm; better to let memory compost into ritual you can serve tonight: the soup, the standing call, the door that opens without notice. And notice who is real at your table, chosen or given, versus who exists mainly in the mist. **Sanctuary is made of maintenance**, not longing. Feed the actual people. The dream-home materializes exactly that way, one meal at a time."
  },
  {
    title: "Neptune in Leo",
    body: "You dream theatrically, and the dreams are contagious. Neptune in Leo drapes glamour over creation itself — romance at cinematic scale, art that wants an audience, a self imagined in golden light before it's lived in ordinary daylight. This is a real gift: **enchantment is a service**, and your ability to make life feel like it matters, like it's lit and scored and worth watching, lifts everyone in range. People remember evenings with you the way they remember films.\n\nThe refinement is remembering the person under the glow — yours and everyone else's. Idealized love falls hardest when the footage runs out; idealized selves exhaust the actor. The practice is **letting the unlit version be loved**: showing someone the untheatrical Tuesday self, loving them after you've seen theirs, making art about what's true and not only what's radiant. The glamour is real magic. It just isn't the whole spell. The rest of it is presence, which needs no lighting rig at all."
  },
  {
    title: "Neptune in Virgo",
    body: "You keep looking for the sacred in the small, which is exactly where it hides. Neptune in Virgo runs an honest tension — boundless dream, exacting standards, the sign of its detriment asking the ocean to file paperwork — and it can spend years anxious that neither side is being served: the mysticism feels sloppy, the work feels meaningless, and the ideal of health or order keeps dissolving on approach. The resolution isn't choosing a side. It's the synthesis the placement was always pointing at: **work as prayer**.\n\nDevoted craft is your spiritual technology — service as the practical face of compassion, the checklist as liturgy, care rendered so precisely it becomes indistinguishable from love. The practice is releasing the fantasy of the perfected system, body, or routine, and consecrating the imperfect one you're actually living in. **Holiness doesn't require flawlessness**; it requires attention, and you have attention in rare supply. Sweep the floor like it matters. It does. That was the secret the whole time."
  },
  {
    title: "Neptune in Libra",
    body: "You dream of love the way composers dream of resolution. Neptune in Libra idealizes the meeting point — the perfect understanding, the frictionless we, the relationship that redeems everything before it. Your cohort was handed one script for partnership and dissolved it in longing for something truer, and you personally carry the high vision: **love as a work of art**, connection that means something beyond logistics and habit. That vision raises what you'll reach for, and reaching high is not the mistake.\n\nThe mistake is grading actual humans against the mirage. The practice is loving particular people — whose imperfections are the texture of intimacy, not the flaw in it — and noticing when you're relating to your projection instead of the person breathing next to you. Disillusionment, when it comes, is not the death of the dream; it's **the dream getting accurate**. What remains after the shimmer burns off is rarer than the fantasy: someone real, choosing you, on an unremarkable day. That's the resolution the whole song was building toward."
  },
  {
    title: "Neptune in Scorpio",
    body: "Your imagination goes where the lights don't. Neptune in Scorpio dissolves the boundary at the deepest layer — merging, mystery, the erotic and the transcendent sharing one root system. You sense what's hidden almost involuntarily: the tension under the dinner party, the grief behind the joke, the want nobody has confessed yet. Your cohort dragged the underworld into art and conversation, and you personally carry **porousness as an instrument** — tuned, it's insight bordering on the psychic; unattended, it's undertow.\n\nSo attend to it. The practice is distinguishing your water from other people's: whose dread is this, whose desire, whose despair did you absorb at the grocery store? Cleansing rituals matter here more than for almost anyone — the shower that's also a ceremony, the walk that returns you to your own perimeter. And honor the gift's direction: **depth is for retrieval, not residence**. Dive, bring back the pearl, surface. The ones who love you would like to see you in daylight too."
  },
  {
    title: "Neptune in Sagittarius",
    body: "You're thirsty for a meaning big enough to live inside. Neptune in Sagittarius dissolves the borders between faiths — pilgrimages, philosophies, far horizons shimmering with promise, the sense that the truth is out there and slightly to the left of wherever you're standing. Your cohort globalized the sacred, sampling freely across traditions, and you personally carry **the seeker's sincerity**: your questing isn't tourism. You genuinely want to know what it's all for, and that want has shaped your whole route.\n\nThe practice is holding each answer loosely without holding it cynically. The shimmer on the horizon is real — but so is the road, and the road keeps going, and a faith that only exists at a distance never gets to feed you. Let something be true enough to practice: the tradition kept imperfectly, the ethic applied on ordinary days, **the pilgrimage that includes coming home**. Meaning isn't hiding at the next border. It's walking beside you, waiting to be lived instead of pursued."
  },
  {
    title: "Neptune in Capricorn",
    body: "You dreamed early about how things should be run, then watched how they actually are. Neptune in Capricorn dissolves easy faith in institutions — governments, companies, churches, all the towers that promised solidity and delivered fog. Your cohort inherited that disillusionment as an atmosphere; you carry it personally as a quiet, load-bearing question: **is anything actually trustworthy at scale?** The danger is that the question hardens into cynicism, which feels like wisdom and functions like surrender.\n\nChoose visionary instead. Disillusionment literally means the removal of illusion — which makes it a qualification, not a wound. You see through the false structures precisely so you can build true ones: the organization worth its mission statement, the career with integrity load-tested into it, **the institution you wished existed, made real**. The practice is small and concrete: run the meeting the way power should work. Keep the promise at the scale you control. The dream of good structure isn't naive. Unbuilt, it's just early."
  },
  {
    title: "Neptune in Aquarius",
    body: "You dream in plural. Neptune in Aquarius pours the ideal into the collective — utopias, networks, the conviction that technology or community might finally redeem us. Your cohort came of age as the world wired itself together, and the longing underneath it all is genuinely beautiful: **belonging at the scale of everyone**, no one outside the circle, the future as a shared work of imagination. Your compassion scales, and that is rarer than it sounds.\n\nThe dissolution to watch is the one between connection and its simulation — a thousand contacts and no one to drive you to the airport, ideals so wide they never land on a particular Tuesday. The practice is keeping the dream particular too: one friend, one need, **one act of care that no ideology gets credit for**. Let the utopia have a street address. The collective you're dreaming of is assembled entirely out of specific people being specifically loved — start there, and the vision stops being a mirage and starts being a neighborhood."
  },
  {
    title: "Neptune in Pisces",
    body: "Neptune is home in Pisces, and the tide comes all the way in. Your imagination has no fence line — compassion, artistry, and longing move through you like weather through open country, and the membrane between you and everything else runs thinner than most people can conceive. This is **the mystic's placement**, genuinely: dreams that inform, art that channels, empathy that borders on communion. You didn't choose the porousness. You get to choose what it's for.\n\nThe one necessity is a practice that returns you to shore. Boundlessness without a container becomes flooding — absorbed sorrows mistaken for your own, escapism dressed as transcendence, the self misplaced in someone else's weather. So keep dry land deliberately: named feelings, kept hours, a body fed and rested, one or two people who can tell when you've drifted and will row out to get you. **The shoreline is what makes the ocean survivable** — and survivable, your depth becomes the gift it was always meant to be: mercy, with a witness attached."
  }
];

export const PLUTO_IN_SIGN: Interpretation[] = [
  {
    title: "Pluto in Aries",
    body: "Your will has been to the underworld and back. Pluto in Aries transforms the act of asserting itself — anger composted into drive, survival instinct refined into leadership, the raw I want and I will excavated from wherever it was buried and returned to you with interest. Somewhere in your story, the right to take up space was contested. What grew back is stronger than what was suppressed: **a will with roots**, not just heat.\n\nYou regenerate by daring again after the defeat — that's the signature move, and it never stops working. The practice is aiming it: rage is fuel, and fuel wants an engine, so give yours a build-site instead of just a battlefield. And learn the deeper definition this placement is teaching — power isn't the first strike or the loudest claim. It's **the capacity to begin as many times as it takes**, which no one can confiscate. You've already proven you have it. Now you get to choose what it's for."
  },
  {
    title: "Pluto in Taurus",
    body: "Your deepest lessons run through what you hold. Pluto in Taurus transforms security itself — worth, ownership, the body's stubborn wisdom — and the tension is honest: a nature built to keep, assigned the curriculum of release. What you grip hardest is precisely what life keeps prying open: the savings, the certainty, the version of safety that turned out to be a beautifully furnished cage. **Loss, here, is a teacher with terrible manners** and an excellent syllabus.\n\nThe transformation on offer is a new definition of having. What survives your letting-go is truly yours — the worth that isn't an account balance, the security that lives in your competence and your people rather than your possessions, the body inhabited instead of merely maintained. The practice is voluntary release in small denominations: give something away before it's taken, loosen one grip a year. **The vault worth filling is the one inside you**, and nothing that belongs in it can be repossessed."
  },
  {
    title: "Pluto in Gemini",
    body: "Information is never neutral in your hands. Pluto in Gemini gives words their full weight — curiosity that excavates, questions that open what politeness kept shut, an instinct for the fact that reroutes the whole conversation. You understand, at a level most people never reach, that **naming a thing changes it**: the diagnosis, the confession, the word for what you are that turns a lifetime of static into signal. You've likely lived that power from both ends.\n\nSo use it knowingly. A mind this penetrating is either a searchlight or a scalpel, and the ethical work is choosing per occasion — illumination for the lost, precision for what needs cutting, and restraint for the moments when someone isn't ready for their truth to be said aloud. The practice is aiming your questions at what actually matters: not gossip's small excavations but **the buried stories that free people once they're spoken**. Language is your underworld and your ladder out of it. Speak accordingly."
  },
  {
    title: "Pluto in Cancer",
    body: "Your roots go down through generations. Pluto in Cancer works the deepest soil — family patterns, inherited loyalties, the fierce and complicated business of belonging — and you can feel it in the tides of your own household: love and control braided together, care that sometimes gripped too hard, silences that were themselves a kind of inheritance. **What was survival for the people before you can become choice for you.** That single sentence is the whole curriculum.\n\nThe transformation on offer is conscious lineage: keeping the devotion, retiring the defenses. You get to audit what was handed down — the recipes and the resilience, yes, but also the vigilance, the scarcity, the rule that love must be earned through worry — and decide what crosses into the next generation on your watch, whether that generation is children, chosen family, or simply the people you feed. The practice is **tenderness without the armor it came wrapped in**. The lineage doesn't end with you. It gets edited by you, and that's holier."
  },
  {
    title: "Pluto in Leo",
    body: "Your creative self runs on core power. Pluto in Leo makes expression existential — being seen isn't decoration, it's **a claim on existence itself**, and somewhere in you lives the conviction that to go unwitnessed is a kind of erasure. Pride, ambition, and radiance braid together at depth here: the art you make, the love you declare, the self you present are all charged with more voltage than the occasion strictly requires. That's not vanity. That's the underworld routing itself through the heart.\n\nThe work is sovereignty without empire: shining because it's true, not because the dark feels like death. Watch for the moments when the need to be seen starts making your choices for you — the room worked instead of enjoyed, the self curated past recognition. The practice is **creating from the core rather than for the crowd**: one piece of work, one act of love, done at full intensity with no audience at all. When the radiance survives the empty theater, you'll know it's really yours. It is. It always was."
  },
  {
    title: "Pluto in Virgo",
    body: "You transform through the disciplines of the useful. Pluto in Virgo turns work, health, and service into sites of profound remaking — compulsion refined into craft, criticism deepened into healing, the daily routine revealed as the place where a whole life quietly gets rebuilt. Your cohort remade medicine, labor, and the meaning of a body that works differently; you personally carry the x-ray eye: **you can find what's broken from any distance**, in a system, a schedule, a self.\n\nThe evolution is learning that repair doesn't require perfection first — including your own. The critical instrument, turned inward without mercy, will file you under broken and keep you there indefinitely, working off a debt that was never real. The practice is **service from wholeness rather than penance**: helping because you're good at it, not because you're proving you deserve to exist. Fix things, yes — it's your genius. But you were never one of the broken things. You were always the healer, learning the difference."
  },
  {
    title: "Pluto in Libra",
    body: "Relationship is where your depths get negotiated. Pluto in Libra brings power into the space between people — contracts rewritten, imbalances named, the pleasant surface pulled back so the real terms can be seen. You feel the undertow in every partnership: who accommodates, who decides, what the smile is holding down. Your cohort put marriage itself on trial and rebuilt commitment from the studs; you personally carry the gift and burden of **seeing the actual deal beneath the stated one**.\n\nYou transform partnerships by refusing the false ones — and that refusal, however it's arrived, has probably cost you. It was still right. The practice now is building the true ones: intimacy where power is spoken about out loud, where fairness is **excavation rather than etiquette**, where both people get to be their full weight without apology. Conflict, handled at your depth, isn't the death of harmony — it's how harmony stops being a performance. You didn't come here for pleasant. You came here for real, together."
  },
  {
    title: "Pluto in Scorpio",
    body: "Pluto is home here, and you've never pretended the depths don't exist. Death, desire, betrayal, rebirth — you metabolize what others euphemize, and your cohort was born straight into the era of everything the culture couldn't say: epidemic grief, transformed intimacy, power named as power. Personally, it means **crisis clarifies you** where it scatters other people. Intensity isn't a phase you went through; it's your native weather, and small talk has always felt like holding your breath.\n\nThe lifelong art is regeneration on purpose: choosing your transformations before circumstance chooses them for you. You will shed selves — that's not in question — so the practice is conscious molting: ending the era deliberately, grieving with ceremony, letting people witness the becoming instead of just the aftermath. And extend your own medicine inward — **the compost always becomes soil**, including yours. You are proof that a person can go all the way down and come back generative. Keep coming back. That's the whole vocation."
  },
  {
    title: "Pluto in Sagittarius",
    body: "You put belief itself through the fire. Pluto in Sagittarius transforms meaning — dogmas dismantled, truths tested at depth, faith rebuilt from the studs after the old structure failed inspection. Your cohort watched grand narratives implode in real time and learned early that certainty can be weaponized; you personally carry the aftermath as a gift: **convictions that cost you something**, and therefore carry unusual force. When you say you believe a thing, people can hear the fire it survived.\n\nThe vigilance to keep is that certainty is a tool, and every tool can become a weapon — including yours, including the hard-won ones. The practice is holding truth with open hands: strong beliefs, loosely gripped, revised in public when the evidence asks. And notice the deeper invitation — after the dismantling, you're allowed to actually believe again. Not the borrowed faith, but **the one forged in your own fire**: tested, scarred, and finally, unmistakably yours. Cynicism was the chrysalis. It was never meant to be the destination."
  },
  {
    title: "Pluto in Capricorn",
    body: "You see how power actually works — the scaffolding behind the announcement, the interest behind the policy, the quiet room where the real decision happened. Pluto in Capricorn transforms structures: careers, institutions, authority itself dismantled and rebuilt closer to true. Your cohort arrived as the towers were being audited by history, and you carry that audit personally: ambition runs deep in you, and **so does the investigation** — you can't unsee a rotten foundation once you've spotted it, including in things you built.\n\nThat's the assignment, actually. The practice is constructive: **build the thing that would survive your own scrutiny** — the career with nothing buried in the basement, the leadership that doesn't require anyone's diminishment, the institution-sized promise actually kept. Power is not the corruption; unexamined power is. You're allowed to want authority, to hold it, to enjoy it — provided you keep auditing your own floors with the same rigor you turn on everyone else's. Do that, and what you build becomes the standard the old structures fall against."
  },
  {
    title: "Pluto in Aquarius",
    body: "Your transformations happen at network scale. Pluto in Aquarius works on the collective's deep code — who belongs, who decides, what the future is allowed to cost, and who gets billed for it. You feel the group's shadow and its promise with equal clarity: the movement's liberating surge and its purity spiral, the technology's reach and its grip. That double vision is the gift — **you can't be recruited by anything you can see all the way through**, which makes you dangerous to every system running on unexamined consensus.\n\nThe charge is to use that sight to redistribute power, not merely to critique it. Analysis without construction curdles into a very intelligent despair, and the future doesn't need more accurate cynics. The practice is **building the structures you'd want to be governed by** — the collective with real accountability, the tool that gives capability away, the friendship network that functions as infrastructure when institutions fail. Revolution, at your depth, isn't an event. It's an architecture. Draft it like you mean to live there, because you do."
  },
  {
    title: "Pluto in Pisces",
    body: "You dissolve what was never solid to begin with. Pluto in Pisces transforms at the root of the root — illusions surrendered, ancestral griefs composted, the boundary between self and everything grown thin enough for grace to pass through. This is depth work of the spiritual kind: not the excavation of one buried thing but **the slow release of the water table itself**, collective sorrows and collective mercies moving through individual lives, yours very much included. You feel history in your body. That's not a malfunction; it's instrumentation.\n\nThe practice is anchoring it in compassion with hands. Transcendence untethered drifts into escape, and dissolution without direction just makes fog — so let the oceanic feeling arrive somewhere real: help with a name and a date on it, grief tended in an actual room, forgiveness enacted rather than merely felt. **Grace wants a body to work through**, and it has chosen a porous one on purpose. Keep yours fed, rested, and reachable. The dissolving isn't the end of the self. It's the self, finally, in solution — available everywhere it's needed."
  }
];
