import type { Interpretation } from "./types";

export const SUN_IN_SIGN: Interpretation[] = [
  {
    title: "Sun in Aries",
    body: "The Sun is exalted in Aries, and you can feel it: your vitality runs on ignition. You are the one who says the thing first, starts the project before the plan is finished, walks into the room the rest of the group is still discussing. **Beginning is your native gift** — not recklessness, but the willingness to be first through the door and find out what is on the other side. Life feels most like yours when something honest is at stake.\n\nThe growth edge is aim. A fire this ready will burn for whatever is nearest, and not every nearby fight deserves you. The practice is choosing your battles the way you would choose a name: deliberately, because **it has to fit the life you are actually building**. You do not need to soften. You need to point all that courage at what you love, and let the rest go unfought."
  },
  {
    title: "Sun in Taurus",
    body: "You were built for the long game. A Taurus Sun draws vitality from what can be touched and tended: the meal cooked slowly, the friendship in its second decade, work that leaves something standing when you walk away. In a culture that mistakes speed for worth, **your steadiness is a form of resistance**. You root where others rush, and people can feel the ground get more solid when you arrive.\n\nThe edge is telling the difference between the patience that builds and the comfort that keeps you smaller than you are. Some of what you are holding is foundation; some is just familiar weight. The practice is a periodic, honest audit — **keep what still feeds you, release what only fills you** — and trusting that your gift for permanence will rebuild anything worth having. You do not lose yourself by changing. You prove yourself durable."
  },
  {
    title: "Sun in Gemini",
    body: "Your life force is curiosity itself. A Gemini Sun stays alive by asking — you are the bridge between people and ideas that would never otherwise meet, the one who can translate the engineer to the artist and back before dessert. **You contain more than one self, and all of them are real.** In a world that demands people pick a single lane and stay in it, your multiplicity is not indecision; it is range.\n\nThe practice is depth by choice. Let one question hold you long enough to change you, not just entertain you. Follow one thread past the point where it stops being novel and starts being yours. Boredom will whisper that the next thing is better; sometimes it is right, and sometimes it is just afraid of the intimacy of staying. **You get to be many things and still go deep.** Both are true. Both are yours."
  },
  {
    title: "Sun in Cancer",
    body: "You shine the way the tide moves — in rhythms, not straight lines. A Cancer Sun finds its purpose in protecting what it loves: a home, a history, a chosen family gathered one person at a time. You remember birthdays and grief anniversaries and the exact thing someone said years ago, because **your memory is an act of devotion**. People heal in your kitchen without quite knowing why.\n\nThe work is letting the shell open on your terms. Your tenderness is a strength, and it becomes a hiding place only when nothing is ever allowed in — when you feed everyone and let no one feed you. The practice is receiving: letting someone see the tired version, the unfinished version, the you that is not hosting. **Care that flows both directions is the home you have been building all along.** You deserve to live in it, not just staff it."
  },
  {
    title: "Sun in Leo",
    body: "The Sun is home in Leo, and it shows. You carry a warmth that changes the temperature of a room — a heart that wants to make life more beautiful for everyone in it, and the generosity to actually do the work. **Creating is how you stay alive**, whether the canvas is art, a dinner table, a look, or a life assembled from scratch when the script you were handed did not fit. Your visibility gives other people permission to take up space.\n\nThe edge is the audience. When your shine depends on applause, silence starts to feel like a verdict, and it never was one. The practice is shining because it is your nature — the sun does not check who is watching before it rises. **Your radiance is not a performance to be graded; it is a fact to be lived.** Let it warm the people who showed up, and do not dim for the ones who did not."
  },
  {
    title: "Sun in Virgo",
    body: "You come alive in the details other people skip. A Virgo Sun finds purpose in refinement — making things work better, cleaner, truer — and offers that skill as a quiet form of devotion. You are the one who reads the fine print, remembers the allergy, fixes the thing before anyone knew it was broken. **Your attention is your love made visible**, and the people who receive it are safer than they realize.\n\nThe growth edge is turning that discerning eye on yourself with mercy. The same vision that finds the flaw in the system will find one in you every single day, and it is not always telling the truth. The practice is letting good work be enough — shipped, imperfect, real — and extending to yourself **the tenderness you show every broken thing you have ever repaired**. You were never a project to be completed. You are the craftsperson, not the flaw."
  },
  {
    title: "Sun in Libra",
    body: "The Sun is in fall in Libra, and that friction is worth naming honestly: you see yourself most clearly in relation — the friend, the partner, the room you can read in a single glance — which means the solo self can feel strangely out of focus. This is real, and it is not a defect. **You were given relationship as your medium**, the way other people are given stone or sound, and your instinct for fairness makes you the person everyone trusts to hold the middle.\n\nThe work is a self that does not blur to keep the peace. A clear yes and a clear no make you more lovable, not less; harmony you had to vanish for was never harmony. The practice is small and radical: state a preference before polling the room. **Your own weight belongs on the scale.** Balance that erases you is not balance — it is absence, beautifully arranged."
  },
  {
    title: "Sun in Scorpio",
    body: "You were never going to live on the surface. A Scorpio Sun draws power from depth — the truths people avoid, the intensity most water down, the capacity to end what is finished and begin again on the other side of it. **You transform; it is what you are for.** You have likely already survived versions of yourself that other people would call a whole life, and that shedding is not damage. It is your method.\n\nThe practice is trusting a few souls with the whole story. Your privacy is intelligent — it has protected you — but a vault with no visitors eventually becomes a tomb. The permission this placement grants: you are allowed to be fully known and still be safe. **Intimacy is not surveillance.** Choose your witnesses carefully, then actually let them witness. The depth you carry was never meant to be carried alone."
  },
  {
    title: "Sun in Sagittarius",
    body: "Your vitality lives at the horizon line. A Sagittarius Sun runs on meaning — the next journey, the bigger question, the faith that life is going somewhere worth the ride even when the current mile is mud. You teach by enthusiasm and heal by perspective; **you are the person who reminds the room that the map is bigger than this**. Your honesty, blunt as it sometimes lands, is a kind of respect: you tell people the truth because you believe they can grow.\n\nThe growth edge is the harvest. Leaving is easy for you — the next horizon always glitters — but some truths are only found by staying long enough to reap what you planted. The practice is finishing: the degree, the manuscript, the conversation at the hard part. **Not every act of freedom looks like departure.** Sometimes the wildest thing you can do is remain, and let the meaning ripen."
  },
  {
    title: "Sun in Capricorn",
    body: "You understood early that time is a material, and you build with it. A Capricorn Sun finds purpose in mastery — the slow, deliberate climb toward something that will outlast the applause, the reputation assembled brick by kept promise. Often this placement carries an early seriousness: you may have been the responsible one before anyone asked if you wanted the job. **Your discipline is real architecture**, and people stand inside what you have built whether they thank you or not.\n\nThe work is remembering the summit was supposed to have a view. Achievement can become a treadmill dressed as a mountain — always another quarter, another proof. The practice is letting joy count as an accomplishment: rest that is not earned, pleasure that is not productive, **a life that belongs to you and not just to your résumé**. You have spent years proving yourself. You are allowed to enjoy the person you proved."
  },
  {
    title: "Sun in Aquarius",
    body: "The Sun is in detriment in Aquarius, which describes a real tension: the planet of the singular self, placed in the sign of the collective. In practice, you shine at an angle no one else occupies. You see the pattern from outside it — the future arriving early, the rule that deserves breaking, the group that needs someone brave enough to differ. **Standing apart is your genius**, and for many people with this placement it was also the first fact of life: you knew early that the standard-issue script was not yours.\n\nThe ache underneath is belonging. The practice is letting people close without fearing they will make you ordinary — they cannot; your difference is structural, not a costume that intimacy could remove. **You can be fully known and remain entirely yourself.** Find the ones who love the angle you shine at. That is not compromise. That is your actual constellation."
  },
  {
    title: "Sun in Pisces",
    body: "Your edges were drawn in watercolor. A Pisces Sun lives close to the current beneath things — imagination, compassion, the quiet sense that everything is connected and everyone is carrying something. You feel the whole room and dream in full color; strangers tell you their lives in checkout lines because something in you reads as safe harbor. **Your porousness is an instrument, not a flaw** — artists, healers, and mystics are built from exactly this.\n\nThe work is choosing where the water goes. Without banks, a river becomes a flood, and you can spend a lifetime dissolved into other people's needs and other people's dreams. The practice is a shoreline: hours that are yours, art that is yours, a no that holds. **Boundaries do not make you less loving — they make your love a place people can actually swim.** The sea stays beautiful when it knows where it ends."
  }
];

export const MOON_IN_SIGN: Interpretation[] = [
  {
    title: "Moon in Aries",
    body: "Your feelings arrive like weather with no warning system — sudden, total, honest, gone. An Aries Moon needs motion to metabolize emotion: you feel better after the run, the confrontation, the decision, not after the brooding. **Your anger burns clean** — fast up, fast out, no residue — which is rarer and healthier than the slow poison most people carry. When you love someone, they know, because subtlety was never the point.\n\nThe practice is the pause: three seconds between the spark and the flame, long enough to ask whether this fire is yours to light. Not suppression — you should never be talked out of your own aliveness — just aim. And a permission: **needing things immediately does not make you too much.** It makes you honest about hunger in a world that teaches people to starve politely. Find the ones who can meet your weather. They exist."
  },
  {
    title: "Moon in Taurus",
    body: "The Moon is exalted in Taurus, and your inner life shows why: feelings that settle deep, hold steady, and rarely lie to you. You are the calm other people borrow in a crisis — the friend whose kitchen feels like a nervous system regulating in real time. **Comfort is real medicine for you**: the body, the meal, the familiar blanket, the playlist worn soft with use. You soothe through the senses, and you can teach others to do the same.\n\nThe edge is change. Because your feelings settle so thoroughly, endings can register as violence even when they are actually doors. The practice is letting the new thing in before the old thing has finished leaving — trusting that **your gift for steadiness travels with you**; it was never stored in the furniture. Not everything that shifts is a loss. Some of it is the ground rearranging itself to hold you better."
  },
  {
    title: "Moon in Gemini",
    body: "You feel in language. A Gemini Moon processes emotion by naming it — talking it through, writing it down, turning the ache into a sentence you can finally look at from the outside. The friend who gets your late-night voice memo essay knows: **articulation is how you digest**. Restlessness, for you, is often the heart asking for new input, and one good conversation can genuinely repair your whole day.\n\nThe practice is dropping below the words sometimes. Some feelings arrive before vocabulary and deserve to exist unexplained for an hour — grief especially, and joy, which flattens when narrated too soon. Try letting a feeling sit in the body before it goes to the pressroom. **Not everything needs a caption to be real.** And a permission: your way of feeling is not shallow because it is verbal. Language is your depth. It just moves fast."
  },
  {
    title: "Moon in Cancer",
    body: "The Moon is home in Cancer, and you feel it as native fluency: emotions that move in tides — deep, cyclical, exquisitely tuned to the people you love. You remember everything the heart ever recorded, and your care is specific: the right soup, the right silence, the text that arrives exactly when someone was about to give up. **You are the home other people did not know they were homesick for.**\n\nThe work is tending your own waters as devotedly as you tend everyone else's. A tide this responsive can spend a lifetime shaped by other people's moons. The practice is asking, each day, one unglamorous question — what do I need? — and treating the answer as seriously as you would treat anyone else's. **The past can inform you without steering**, and your softness does not require a permanent shell. It requires a home. Build one where you also get to rest."
  },
  {
    title: "Moon in Leo",
    body: "Your heart wants an audience it can trust. A Leo Moon feels safest when love is warm, expressive, and a little theatrical — the birthday actually celebrated, the affection said out loud, the good news met with real fanfare. This is not vanity; **celebration is nourishment for you**, the way quiet is nourishment for someone else. You give loyalty like sunlight: generously, visibly, without keeping score until suddenly you notice no one clapped back.\n\nThe edge is the direct ask. When your need for recognition goes unspoken, it tends to turn into dimming — withdrawing your shine and hoping someone notices the dark. They usually do not; people cannot read an eclipse. The practice is saying it plainly: I need to be celebrated, witnessed, chosen out loud. **Asking for the spotlight you need is not needy — it is accurate.** The people worth your warmth will be honored to bring the applause."
  },
  {
    title: "Moon in Virgo",
    body: "When you love people, you fix things for them. A Virgo Moon soothes itself through order — the tidied room, the solved problem, the plan that finally clicks into place — and being useful is how you say the tender thing you cannot always say directly. Your care is precise: **you notice what people need before they have noticed it themselves**, and you meet it without ceremony.\n\nThe practice is letting yourself be cared for without earning it first. Somewhere along the way, this Moon often learns that love is a job performance — that you are kept for what you do, not what you are. That was a lie told by circumstance, not a law. Let someone bring you soup badly. Let the mess exist without reading it as your failure. **You are not the household's error log.** You are a person, allowed to be tended, allowed to be imperfect, allowed to rest mid-task."
  },
  {
    title: "Moon in Libra",
    body: "You can feel a room go off-key before anyone speaks. A Libra Moon needs harmony the way lungs need air, and you do quiet, skillful work to restore it — smoothing the edge in a conversation, translating between people who have stopped hearing each other. **Attunement is your first language**, and every relationship you touch is gentler for it.\n\nThe edge is trusting that honest friction is survivable. Peace kept at your own expense is not peace — it is conflict postponed, with interest, and the bill usually arrives in your body. The practice is staying in the room when disagreement starts: saying the true thing at moderate volume and discovering, over and over, that the relationship holds. **You are allowed to be a person, not just an atmosphere.** The people who love you want your actual weather — including the storms you have been rescheduling for years."
  },
  {
    title: "Moon in Scorpio",
    body: "The Moon is in fall in Scorpio, and the friction is real: feelings this deep were never going to be casual. You feel everything, all the way down, and you learned early to keep that private — reading what others hide as easily as breathing, while remaining unread yourself. **Your loyalty, once given, is total.** Loving you is like being handed something rare: it comes with weight, and it does not expire.\n\nHold the difficulty tenderly: this placement often grows from years when vulnerability genuinely was not safe, and your vault was wisdom, not pathology. The work now is distinguishing then from now. Trust does not have to be all-or-nothing; it can be issued in small denominations to people who keep earning it. **Let one person hold the unedited version.** Your depth only becomes a burden when it is carried entirely alone — witnessed, it becomes the most honest intimacy there is."
  },
  {
    title: "Moon in Sagittarius",
    body: "Your heart needs open sky. A Sagittarius Moon metabolizes feeling through movement and meaning — the long drive, the sudden trip, the philosophy that turns pain into perspective before the tears have dried. **Optimism is your emotional home base**, and it is mostly genuine: you really do believe the story bends toward somewhere better, and your faith is contagious in rooms that have run out of their own.\n\nThe practice is staying present for the heavy feelings too, because some of them carry the map. When grief or fear shows up, this Moon reaches for the exit — the joke, the flight, the reframe — and sometimes that is medicine, but sometimes it is just leaving. Try sitting with one hard feeling for ten minutes before you widen the lens. **Meaning made too early is escape wearing wisdom's clothes.** The horizon will still be there after you have felt this."
  },
  {
    title: "Moon in Capricorn",
    body: "The Moon is in detriment in Capricorn, and that describes something true: you learned to feel with the door closed. Emotion, in your early world, may have seemed like a liability — so you built composure instead, managing your inner life the way you manage everything: competently, privately, on a need-to-know basis. **There is real dignity in your restraint.** You are the one who functions in the emergency, and people lean on that spine.\n\nBut needs unspoken do not become needs unfelt; they become weight, carried alone, mistaken for character. Hold your own history gently here — the door was closed for reasons that made sense once. The practice now is opening it a crack for one trusted person: being seen before you have it handled. **Being witnessed mid-struggle is not weakness — it is the one competency you have not let yourself practice.** Start small. It counts."
  },
  {
    title: "Moon in Aquarius",
    body: "You watch your own feelings from a small observation deck — noticing, naming, analyzing at a merciful distance. An Aquarius Moon finds safety in perspective: where others drown in a feeling, you study its currents, which makes you the steadiest presence in everyone else's storm. **Your detachment is a skill, not a deficiency** — plenty of people would pay for the clarity you carry by default, and your friendships run on a loyalty that never requires anyone to perform normalcy.\n\nThe practice is descent. Understanding a feeling and having it are different events, and some things — grief, love, belonging — only transform you from the inside. The permission this Moon grants: **you can climb down without losing the deck.** The observation post will still be there after you have wept. Let the feeling happen in your body, not just your notes. That is not losing objectivity. That is finishing the experiment."
  },
  {
    title: "Moon in Pisces",
    body: "You absorb the emotional weather of every room you enter. A Pisces Moon is porous by design — empathic, dreamy, moved by music and strangers and things you cannot name — and that openness is a rare instrument: you comfort people without being told what is wrong, because **you already felt it arrive**. Your inner life is oceanic, half memory, half imagination, all real.\n\nThe work is learning which feelings are actually yours. A sponge this fine can spend days carrying a sadness that belongs to a coworker, a partner, the news. The practice is a gentle sorting ritual — asking, when a mood descends, where did this enter? — and building a shoreline: sleep, water, art, solitude that refills instead of empties. **Your sensitivity is the gift; the boundary is what makes it usable.** With banks, your sea carries people home. Without them, it just carries you off."
  }
];

export const MERCURY_IN_SIGN: Interpretation[] = [
  {
    title: "Mercury in Aries",
    body: "Your mind moves like a struck match. Mercury in Aries thinks by deciding — fast conclusions, blunt questions, a genius for cutting through an hour of noise to the point everyone was avoiding. In meetings, group chats, crises, **you are the one who says the unsayable thing first**, and half the room exhales because someone finally did. Debate does not stress you; it sharpens you.\n\nThe practice is letting other people finish their sentences. Your speed is real, but occasionally the slow thought was carrying something yours missed — and a mind this quick can win arguments it should have lost. Try trading a little velocity for accuracy: ask one more question before ruling. And the permission: **your directness is a gift, not a character flaw.** In a world of hedged emails and vague feedback, people trust you precisely because they never have to decode you."
  },
  {
    title: "Mercury in Taurus",
    body: "You think the way stone is carved — slowly, deliberately, and for keeps. Mercury in Taurus distrusts the hasty take, preferring to turn an idea over until it proves itself in the hand. You may speak later than others in the room, but **when you finally weigh in, people write it down**. Your knowledge is embodied: you learn by doing, remember by touching, explain with examples you can practically taste.\n\nThe edge is keeping one hinge on every conclusion. A mind built for permanence can mistake familiarity for truth, defending a position mostly because it is furnished and lived-in. The practice is a standing question — what would change my mind? — asked honestly, once in a while, about the things you are most certain of. **Slow thinking is not lesser thinking**; it is how anything durable gets made. Just leave a door in the wall for new evidence to walk through."
  },
  {
    title: "Mercury in Gemini",
    body: "Mercury is home in Gemini, and your mind runs on its native quicksilver — fast, lateral, endlessly connective. You collect ideas the way other people collect keepsakes; you can talk to the mechanic, the poet, and the toddler in one afternoon and leave all three feeling understood. **Words obey you**, and your curiosity has no dress code: everything is interesting if you look at it from the right angle.\n\nThe practice is choosing a few threads to follow all the way down. A mind this quick can live on appetizers forever — competent at forty things, transformed by none. Depth is where your cleverness ripens into wisdom, and depth requires the one thing novelty cannot provide: repetition. Pick a question worthy of years. **You do not have to narrow who you are — just deepen where you dig.** The butterfly can keep its wings and still learn one garden completely."
  },
  {
    title: "Mercury in Cancer",
    body: "You think in tides and remember in detail. Mercury in Cancer processes the world through feeling first — you know something is true partly by how it lands in the body, and your memory keeps what mattered, not just what happened. **You listen the way few people can**: not waiting to speak, actually receiving. Old conversations stay searchable in you for decades, which makes your comfort strangely precise.\n\nThe edge is checking, now and then, whether the mood is reading the facts or writing them. On a raw day, this mind can find evidence for any fear it is carrying; the data did not change — the tide did. The practice is a timestamp: noticing what emotional weather you are in before you interpret the text, the silence, the meeting. **Your intuition is real instrumentation** — it just needs calibrating, like every fine instrument. Trust it most when you have also fed and rested the body it lives in."
  },
  {
    title: "Mercury in Leo",
    body: "When you speak, something in the room sits up. Mercury in Leo thinks in story — warm, confident, built to be told aloud — and your conviction gives ideas a pulse that other people's bullet points never find. You explain by lighting things up: **you do not just transfer information, you make people care about it**, which is the rarer skill by far. Teaching, performing, rallying, toasting — this is your mind at home.\n\nThe practice is staying curious after you have taken the stage. Being compelling and being right are different talents, and a voice this persuasive can occasionally out-argue its own doubts. Invite the question that might unseat you; thank the person who pushes back well. Your authority grows, not shrinks, every time you admit you had not thought of something. **A generous mind is more magnetic than a certain one** — and generosity, luckily, is already your default setting."
  },
  {
    title: "Mercury in Virgo",
    body: "Mercury is both at home and exalted in Virgo — the strongest placement it has — and it shows: yours is one of the sharpest minds in the zodiac. You see the flaw in the plan, the pattern in the chaos, the one sentence hiding inside the bloated paragraph. **Precision is your love language for ideas.** Where others gesture, you specify; where others estimate, you check. Whole systems quietly run on people like you.\n\nThe edge is mercy — for drafts, for people, and above all for yourself. An eye this exact will find error everywhere, including in the mirror, and error-hunting turned inward becomes a weather system of self-criticism that no accomplishment can clear. The practice is version tolerance: letting things be finished rather than perfect, letting the first draft exist so the second one can. **Perfectionism is not high standards; it is fear wearing a lab coat.** Your actual standards are met more often than you admit."
  },
  {
    title: "Mercury in Libra",
    body: "You think in dialogue, weighing every idea against its opposite until the scales tell you something. Mercury in Libra gives you a rare fairness of mind — you can argue the other side honestly, and **people trust your judgment because you visibly did the weighing**. You are the friend consulted before hard conversations, the colleague who makes the memo sound reasonable to both camps.\n\nThe practice is the verdict itself. At some point the weighing must end and the choosing begin, and for you that moment can keep receding — one more perspective, one more poll of the group chat. Deciding will sometimes disappoint someone; this is survivable, and it is not cruelty. **A fair process still requires a conclusion.** Try smaller stakes first: pick the restaurant, name the preference, ship the answer. Your beautifully balanced mind was always meant to land somewhere."
  },
  {
    title: "Mercury in Scorpio",
    body: "Your mind does not skim; it excavates. Mercury in Scorpio thinks like an investigator — reading subtext, noticing what was left out of the story, holding a question in the dark until it confesses. **People rarely realize how much you have already understood** by the time they finish their first sentence. You are built for research, therapy rooms, forensics of every kind: anywhere the truth is buried and someone has to be willing to dig.\n\nThe edge is remembering that not every silence hides a motive, and some things are exactly what they seem. A detective's mind, left running on loved ones, turns intimacy into an interrogation nobody passes. The practice is asking instead of deducing: giving people the chance to tell you, before the case file closes. **Your penetrating sight is a gift when it comes with a door** — one people can walk through voluntarily, carrying their own version of the story."
  },
  {
    title: "Mercury in Sagittarius",
    body: "Mercury is in detriment in Sagittarius, and the trade it describes is real: the messenger planet, placed in the sign of the big picture, swaps precision for vision. You think in horizons — the thesis, the moral, the punchline that makes the whole story land — and **you make big ideas feel possible** in a way detail-people never quite manage. Your mind wants to know what it all means, and honestly, someone in the room should.\n\nHold the friction kindly: your leaps are usually right in direction and occasionally wrong in detail, and that is a feature to manage, not a flaw to be ashamed of. The practice is partnership and proofreading — let someone you trust check the math, read the contract, mind the fine print while you mind the point. **Vision and accuracy are a team sport.** Your job is the shape of the map; hire out the millimeters."
  },
  {
    title: "Mercury in Capricorn",
    body: "Your thoughts arrive pre-organized. Mercury in Capricorn thinks in structures — the plan, the sequence, the realistic path from here to done — and you say more in one measured sentence than most people manage in a speech. **People bring you problems because you end them.** You are the one who turns the brainstorm into a timeline, the panic into a checklist, the someday into a date on the calendar.\n\nThe edge is making room for the impractical idea that has not proven itself yet — some of those are the future, auditioning badly. A mind this rigorous can dismiss the dream at the door for lacking credentials. The practice is a probation period: let the wild thought live for a week before you evaluate it, and notice how many impossible things you have already built. **Skepticism is your strength; cynicism is its shadow.** Keep the first. The second costs more than it saves."
  },
  {
    title: "Mercury in Aquarius",
    body: "You think in systems and speak in lightning. Mercury in Aquarius sees the whole circuit board where others see a single wire — which is why your ideas often sound wrong for exactly the number of years it takes everyone else to catch up. **Your detachment is clarity**: you can examine a belief, including your own, without your ego holding the scalpel. Orthodoxy has never once impressed you.\n\nThe practice is translation. A mind ahead of schedule can get lonely broadcasting on frequencies no one is tuned to yet, and being right early feels remarkably like being wrong if you cannot build the bridge. Meet people where they currently think; walk them one step at a time toward the view. And a permission: **thinking differently was never the problem** — for you or anyone raised to believe their angle of vision needed correcting. The future is drafted by exactly this kind of mind."
  },
  {
    title: "Mercury in Pisces",
    body: "Mercury is in both fall and detriment in Pisces — the tradition calls this a hard seat for the messenger, and the friction is real: linear logic is not your native mode, and standardized tests were probably never going to measure you. But here is what the textbook underplays: **you arrive at truths sideways** — through a feeling, an image, a dream, a metaphor that turns out to be more accurate than the spreadsheet. Yours is a poet's instrument, and poets are not failed accountants.\n\nThe work is anchoring. Intuitive knowing evaporates without a container, so build one: write it down when it comes, say it plainly even when plainness feels like a betrayal of the mystery, finish the sentence out loud. **Your knowing survives daylight — let it out into some.** The gap between what you perceive and what you can prove is not a deficit. It is your entire vocation, waiting for translation."
  }
];

export const VENUS_IN_SIGN: Interpretation[] = [
  {
    title: "Venus in Aries",
    body: "Venus is in detriment in Aries, and the friction is honest: the planet of merging, placed in the sign of the self. In practice, you love at first spark — desire that announces itself, pursuit without apology, **a bravery in affection most people never risk**. You would rather be refused than wonder, and there is a cleanness to that which the slow-burn romantics will never understand. You keep courtship alive years into a relationship, because for you, wanting is a verb.\n\nThe workable tension is what comes after the winning. The chase has an ending; love, at its best, does not, and the middle miles can read as boredom when they are actually depth changing costumes. The practice is discovering that **the slow middle holds its own kind of fire** — the intimacy of being re-chosen on an ordinary Tuesday. Stay long enough to find it. It will surprise you more than novelty ever did."
  },
  {
    title: "Venus in Taurus",
    body: "Venus is home in Taurus, and your love wears its native luxury — unhurried, loyal, rich with the senses. You show devotion through presence: the meal cooked from scratch, the hand held in the hard waiting room, the years accumulated like rings in wood. **What you love, you keep**, and being loved by you feels like tenure — a security most people have never once experienced in another person.\n\nThe edge is loosening the grip just slightly, so holding on never hardens into holding still. People grow; the relationship that lasts is the one that lets them, and possession is loyalty's counterfeit. The practice is trusting that what is truly yours does not require a fist to stay. And a permission this placement deserves: **your desire for pleasure is not indulgence — it is wisdom.** The body is not a distraction from the sacred. For you, it has always been the address."
  },
  {
    title: "Venus in Gemini",
    body: "For you, conversation is a form of touch. Venus in Gemini falls for minds first — the banter, the running joke with seventeen callbacks, the person who keeps surprising you at year five the way they did at week one. **Wit is your love language**, and your affection is fundamentally companionable: you want a co-conspirator, someone to narrate the world with, not a statue to admire across a table.\n\nThe practice is staying through the quiet chapters. Not every season of a good love is interesting — some are administrative, some are grief, some are just two people refilling — and a heart wired for novelty can misread those as endings. They are load-bearing. Try finding the newness inside the familiar person: everyone is several people over a lifetime, **including the one you already chose**. Curiosity, aimed at the same face for decades, turns out to be the rarest romance there is."
  },
  {
    title: "Venus in Cancer",
    body: "You love the way home feels at the end of a long day. Venus in Cancer gives tenderly and remembers everything — the anniversary, the small preference, the exact way someone takes their tea after a bad shift. **Caring for people is your art form**, and your love builds actual shelter: chosen family, open kitchens, the address where everyone lands when their life falls apart. Being loved by you is being kept.\n\nThe edge is voicing your own needs as gently as you meet everyone else's. This placement can slide into feeding the whole table and calling its own hunger hospitality — then aching when no one guesses. Mind reading is not a fair test of love, and it is the only test your people keep failing. The practice is the plain request: I need this, said out loud, without apology. **You deserve the same shelter you are.** Let someone build a room for you."
  },
  {
    title: "Venus in Leo",
    body: "You love in full color, and you are not sorry. Venus in Leo brings romance its proper theater — generosity, celebration, loyalty with a crown on it. When you adore someone, they feel like the only person ever adored in the history of adoration; **your attention is a spotlight that makes people become more themselves**. Anniversaries are events. Compliments are specific. Devotion, in your hands, is an art with production values.\n\nThe practice is receiving with the same drama you give. Grand givers often go quietly unfed, performing delight while keeping their own wish list unread — and then the resentment arrives dressed as pride. Let people celebrate you back, extravagantly, imperfectly. Tell them how. And the deeper permission: **your worth does not dim on the days no one is applauding.** The sun in an empty field is still the sun. You were never shining for the audience anyway — remember?"
  },
  {
    title: "Venus in Virgo",
    body: "Venus is in fall in Virgo, and the friction deserves tenderness: the planet of ease, placed in the sign of improvement. Your love speaks in acts of service — the errand run, the prescription refilled, the problem quietly solved before it was mentioned. **Devotion this precise is rare**, and the people you love are held by a hundred small competencies they will never fully count. You do not say it with roses; you say it with the calendar reminder about their appointment.\n\nThe tender part: an eye trained on what could be better eventually turns on itself, and you can end up believing love must be earned through ceaseless usefulness — that unimproved, you are unlovable. That was never true. The practice is **letting yourself be loved as-is, mid-draft, unoptimized**, and noticing that real affection was never conditional on the fixing. You are not a service. You are the person the service was hiding."
  },
  {
    title: "Venus in Libra",
    body: "Venus is home in Libra, and it shows in everything you touch — the eye for beauty, the instinct for grace, the way relationship itself is your medium the way paint belongs to a painter. **You make people feel considered**, which is rarer than making them feel wanted: you remember their objections, honor their preferences, design the evening around what will actually delight them. Partnership completes a circuit in you, and there is no shame in that wiring.\n\nThe edge is bringing your whole opinion to the table. Agreeableness is a talent, but performed long enough it becomes a mask even you cannot get behind, and being adored for your accommodations is lonelier than being argued with by someone who knows you. The practice is the stated preference, the visible disagreement, the unedited want. **Being agreeable is not the same as being known** — and you deserve to be known."
  },
  {
    title: "Venus in Scorpio",
    body: "Venus is in detriment in Scorpio, which is the tradition's way of saying: this heart does not do lite versions. You never really tried casual — intimacy for you means the unedited archive, secrets included, loyalty that would hold in a hurricane. **You love at full depth or not at all**, and for the person who can meet it, being chosen by you is the most honest thing that ever happens to them.\n\nThe workable tension is trust. A heart that has been burned learns to test — small provocations, strategic silences, withheld pieces, watching how the other person handles the dark. But some tests break the very thing they were checking. The practice is letting love prove itself over time instead of under trial, and letting yourself be as findable as you are perceptive. **Depth was never the problem. Armor on the depth is.** Choose someone strong-hearted, then put the tests down."
  },
  {
    title: "Venus in Sagittarius",
    body: "You fall for the ones who make the world bigger. Venus in Sagittarius wants a co-adventurer — someone to travel with, laugh with, argue philosophy with at midnight in a parking lot — and your love comes with more honesty and less claustrophobia than most people have ever been offered. **Freedom is your romance**: you do not want to own anyone, and you cannot breathe when someone tries to own you.\n\nThe practice is learning that commitment, freely chosen, can be the widest country of all. Somewhere this placement often picked up the idea that devotion means shrinking — that the door must stay cracked or the self suffocates. But the right love is not a smaller life; it is a bigger expedition with better company. **Staying can be an adventure too**, when you stay out of desire rather than obligation. Look for the one who packs a bag when you say let's go. Then go together, for years."
  },
  {
    title: "Venus in Capricorn",
    body: "You love like an architect — slowly, structurally, with the decades in mind. Venus in Capricorn trusts demonstrated devotion over declared devotion: show up on time, keep your word, be the same person in February that you were in October, and you have said more than a sonnet could. **What you build together is the romance** — the home, the business, the reputation, the shared spine of a life. Your love has load-bearing walls.\n\nThe edge is letting tenderness show before it feels certain. A heart this careful can withhold the soft data — the I miss you, the I was scared — until the relationship has passed every inspection, but some proof only arrives after the risk. The practice is one unearned tenderness per week: affection given on spec. And the permission: **you are allowed to want comfort, not just respect.** Being held is not an inefficiency. It is the point of the building."
  },
  {
    title: "Venus in Aquarius",
    body: "You fall for the friend first — the mind, the cause, the person who is genuinely unlike anyone else you have met. Venus in Aquarius loves with room to breathe: your affection asks no one to shrink, perform, or match a template, and **convention was never a requirement for your heart**. You are built for the loves that do not come with preprinted forms — chosen family, long collaborations, partnerships that invent their own shape as they go.\n\nThe practice is closeness itself. Perspective is your gift, but it can become a permanent buffer — caring deeply from one respectful step back, intellectualizing the very intimacy you want. Letting someone matter enough to unsettle you is the frontier. And the permission, stated plainly: **a love that had to be invented is not lesser than one that came with instructions.** Yours may hold more honesty than every template it declined. Difference, here, is the inheritance."
  },
  {
    title: "Venus in Pisces",
    body: "Venus is exalted in Pisces, and your heart is the evidence — love without a visible floor, compassion that asks for no credentials, romance touched with something almost devotional. **You love people as they could be**, and sometimes that vision heals them: plenty of souls first believed in their own goodness because you saw it out loud. Your tenderness does not check status, history, or deserving. It just arrives.\n\nThe growth edge is loving what is actually there, too. A heart this boundless can pour itself into potential for years while the present-tense person declines to show up — mistaking rescue for romance and depletion for devotion. The practice is discernment without hardening: choose partners who hold water, so your tenderness lands somewhere that can keep it. **Boundless love still deserves a worthy vessel.** Compassion for everyone must include the person offering it — that is not selfishness; that is the completed circle."
  }
];

export const MARS_IN_SIGN: Interpretation[] = [
  {
    title: "Mars in Aries",
    body: "Mars is home in Aries, and your drive shows it — pure ignition, zero preamble. You act while others deliberate; you volunteer for the hard conversation, the cold plunge, the first draft, the front of the line. **Your anger burns clean**: fast up, fast out, no residue, no three-week sulk. Courage is not your achievement — it is your default setting, and people organize themselves around that fact whether they admit it or not.\n\nThe practice is aim. A force this direct changes the world in exact proportion to how well you choose its target, and an unaimed week can leave you exhausted from battles that were never yours. Ask, before the charge: is this mine? does winning it build anything? And the permission underneath: **your intensity does not require an apology.** It requires a worthy project. Find one the size of your fire, and the restlessness resolves itself."
  },
  {
    title: "Mars in Taurus",
    body: "Mars is in detriment in Taurus, and the trade is real: speed for staying power. Your force moves like a glacier — slow to start, and then nothing on this earth stops it. **You win through sheer duration**, outlasting every rival who sprinted past you in the first mile, and your work has a finished quality the sprinters never manage. Your anger is slow too, which is mercy right up until the day the ground finally moves — and everyone remembers where they were.\n\nHold the friction kindly: the difficulty starting is not laziness, it is a heavy engine that needs a real reason to turn over. The practice is beginning before you feel fully ready, since readiness, for you, tends to arrive mid-stride rather than beforehand. Set the smallest possible first step and take it badly. **Momentum is your superpower — but only after ignition.** Everything downstream of starting, you already dominate."
  },
  {
    title: "Mars in Gemini",
    body: "Your weapon of choice is the sentence. Mars in Gemini fights with wit and wins with words — the fast rebuttal, the reframing that dismantles an argument before it finishes standing up, the email that ends the dispute in four lines. **Your drive runs on variety**: three projects at once is not chaos for you, it is traction, and the cross-pollination between them is where your best work actually comes from.\n\nThe practice is the finish line. A force this quick can start brilliantly forever — the graveyard of your abandoned drafts could staff a small museum — and the world only gets to keep what you complete. Choose which pursuits deserve your whole attention and carry those all the way home; let the rest be sketches without shame. And one caution held gently: **words can cut deeper than you meant at the speed you throw them.** Aim the blade like the tool it is."
  },
  {
    title: "Mars in Cancer",
    body: "Mars is in fall in Cancer, and the friction deserves to be named tenderly: the planet of direct action, placed in the sign of indirect tides. Anger and desire for your own sake tend to move sideways here — surfacing as mood, withdrawal, the dish set down slightly too hard — rather than as statement. But cross the people under your protection and the water reveals its other face: **you become formidable in a way no one saw coming.** You fight hardest, and best, for what you love.\n\nHold your own history gently: many people with this placement learned early that direct wanting was not safe. It is now, or it can be. The growth edge is the direct ask — **wanting something out loud is not a betrayal of anyone.** Practice on small things: the restaurant, the day off, the hug. The tide is allowed to know, and say, its own direction."
  },
  {
    title: "Mars in Leo",
    body: "You pursue like it is a performance and mean every minute of it. Mars in Leo runs on heart: your drive needs a purpose it can be proud of, and when pride and effort finally align, **your stamina is theatrical in the best sense** — sustained, visible, warming everyone in the cast. You fight openly or not at all; scheming has always struck you as beneath the dignity of a real contest.\n\nThe edge is separating the work from the applause. When recognition goes quiet, this Mars can stall — mistaking an empty room for a verdict on the goal itself — and some of your worthiest projects will have long unwitnessed middles. The practice is a private standard: doing the thing magnificently on the days nobody claps, because you were watching, and your opinion was always the review that mattered. **Perform for the self you respect.** The audience tends to find that person eventually."
  },
  {
    title: "Mars in Virgo",
    body: "Your force is a scalpel, not a hammer. Mars in Virgo channels drive into craft — the refined process, the flawless execution, the work done so well it argues for itself and wins. **You attack problems, rarely people**, which makes you the safest fierce person most of your colleagues know. Your discipline lives in the details: the checklist honored, the practice repeated, the skill compounded daily until it looks like magic from the outside.\n\nThe practice is scale. Precision can become a comfortable hiding place — endlessly sharpening the tool to avoid the big, gradeable swing — and your standards will happily generate infinite preparation if you let them. Lift your exactness off the details sometimes and aim it at the bold move: the application, the launch, the ask. **You are more capable of boldness than your standards let you admit.** Perfect technique was always meant to be spent on something that matters."
  },
  {
    title: "Mars in Libra",
    body: "Mars is in detriment in Libra, and the shape of the friction is elegant: the warrior planet, placed in the sign of peace. You fight best on someone else's behalf — you will go to war for the overlooked colleague, the mistreated friend, the stranger in line — **while your own wants wait politely at the back of the queue**. Even your conflict has good manners: you argue in complete sentences and leave the bridge standing.\n\nHold it kindly: this pattern usually began as intelligence, not weakness — advocacy for others was the acceptable outlet for a force you were not sure you were allowed to use for yourself. You are allowed. The practice is naming what you desire before weighing what everyone else needs, and letting a conflict exist on your own behalf without a committee's approval. **Your side of the scale counts too.** Fairness that excludes you was never fair."
  },
  {
    title: "Mars in Scorpio",
    body: "Mars rules Scorpio in the old books, and your will carries that inheritance — strategic, relentless, powered by reserves most people never have cause to discover in themselves. **You do not chase; you commit** — and then you simply do not stop, through plateaus and setbacks that scatter everyone else. Your force works underground: research, endurance, the long game played so quietly that your victories look sudden to people who were not paying attention.\n\nThe edge is release. A grip this strong holds everything — including the grudge, the sunk cost, the war that already ended — and unreleased battles keep drawing power from the living ones. The practice is a deliberate opening of the hand: naming what is finished and letting it be finished, so all that magnificent force stays pointed at the future. **Your intensity is cleanest in the open.** Say the ambition out loud. Let them watch you achieve it."
  },
  {
    title: "Mars in Sagittarius",
    body: "Your drive needs a horizon or it starts pacing the cage. Mars in Sagittarius is the crusader's placement — you fight for ideas, chase meaning at full gallop, and carry **a conviction so contagious it recruits people mid-sentence**. When you believe in the mission, your effort is enormous and joyful; when you do not, no salary on earth can extract it from you. That integrity of effort is rarer than talent.\n\nThe practice is follow-through past the exciting part. Causes have unglamorous middles — the paperwork after the protest, the maintenance after the launch — and this Mars is built for the charge, not the occupation. Either finish what you start or partner with the finishers, honestly and early. And keep the aim high in the other sense too: **a fight without meaning will poison you faster than losing.** Choose battles that point somewhere. Then ride."
  },
  {
    title: "Mars in Capricorn",
    body: "Mars is exalted in Capricorn — the tradition's highest rating for this planet — and yours is the discipline other people's ambition wishes it had. You convert desire into strategy and strategy into the long, unglamorous execution that actually summits mountains. **Your anger is cold, controlled, and rarely wasted**: instead of exploding, you build the thing that makes the obstacle irrelevant. Revenge, for you, has always looked like results.\n\nThe edge is remembering to want things, not only to achieve them. A machine this effective can end up running other people's programs flawlessly — the promotion you did not want, the metric no one questioned — and summiting mountains that were never yours. The practice is a periodic audit of the goal itself: whose voice assigned this? does the climb still belong to me? **Mastery in service of your own desire is the whole point.** The view was always supposed to be yours."
  },
  {
    title: "Mars in Aquarius",
    body: "You fight for the principle, coolly and at scale. Mars in Aquarius aims its force at systems — the outdated rule, the broken structure, the future that needs someone stubborn enough to start building it early and alone. **Rebellion is your craft, not your mood**: where others rage at symptoms, you redesign causes, and your defiance comes with blueprints attached. Group efforts sharpen you; you organize both the walkout and the alternative.\n\nThe practice is the personal fight. It is possible to defend humanity's dignity all day and leave your own unguarded — to be tireless for the collective and strangely passive when the boundary being crossed is yours. You count among the people you serve. Defend your own needs with the same cool clarity you spend on the cause. And a permission: **being contrary is not a character flaw** — every future that arrived on time was dragged there by someone who would not comply."
  },
  {
    title: "Mars in Pisces",
    body: "Your drive moves in currents, not straight lines. Mars in Pisces acts when inspired and drifts when not — but inspired, **you accomplish in a weekend what schedules could not extract from you in a month**. Your force is tidal and strange: you disarm opposition rather than defeat it, win by empathy and timing, slip past defenses that stop the battering rams. Artists, healers, and quiet revolutionaries run on exactly this engine.\n\nThe work is building small structures for the tide — not a cage, a harbor. Rituals and deadlines gentle enough to actually keep: the same desk, the same hour, the candle lit before the work begins. The current arrives more often when it knows where to find you. And hold this without shame: **your rhythm is not brokenness; it is weather**, and weather can be sailed. Stop comparing your ocean to their treadmill. Learn your own tides, then use them."
  }
];
