import type { Interpretation } from "./types";

export const RISING_SIGN: Interpretation[] = [
  {
    title: "Rising in Aries",
    body: "You arrive before your explanations do. With Aries rising, Mars steers the self you show the world, and people read you as **motion first, deliberation second** — the one who asks the blunt question, takes the stairs two at a time, says yes before the sentence finishes. Your directness is sometimes mistaken for carelessness, but it is closer to respect: you refuse to waste anyone's time, including your own. Your face shows its weather honestly, and that honesty is a door people learn to trust.\n\nThe growth edge is the pause — not to blunt your instinct but to aim it. **One breath before the leap changes nothing about your courage** and everything about where it lands. You have permission to be a beginner in public, to start what you may not finish, to want what you want out loud. **Going first was never the problem**; forgetting to bring yourself along gently is."
  },
  {
    title: "Rising in Taurus",
    body: "You come into a room the way weather settles: unhurried, and it reads as strength. With Venus ruling your ascendant, you meet the world through the senses — texture, tone, the warmth or chill of a space — and your steadiness gives people **somewhere solid to put their weight**. You build trust slowly and keep it for decades. You know that a body is not a project to be fixed but a home to be furnished, and you furnish yours **on your own terms and your own timeline**.\n\nThe edge to work is the grip. Not everything worth loving needs holding, and change is not theft — sometimes it is delivery. Practice releasing one small certainty at a time and noticing that the ground stays under you anyway. **Your permission is to want comfort without apologizing for it.** Pleasure, for you, is not a detour from the path; it is the pavement."
  },
  {
    title: "Rising in Gemini",
    body: "Curiosity reaches the door a half-step ahead of you. With Mercury ruling your rising, you meet the world as a question worth asking, quick to name what others are still forming, fluent in more than one register of yourself. You are a **translator between worlds** — a gift that runs especially deep for anyone who has lived between categories and learned to speak several dialects of belonging. People leave conversations with you feeling smarter, lighter, more possible.\n\nThe growth edge is depth: letting one thread run long enough to knot into something that holds you back. **Your multiplicity is not indecision** — it is range, and range is an inheritance, not a flaw to outgrow. The practice is choosing one conversation, one craft, one person's story, and staying past the point where novelty fades. What you find there is not boredom. **It is the second, better beginning.**"
  },
  {
    title: "Rising in Cancer",
    body: "Yours is the only ascendant the Moon itself rules, and it shows: you read a room the way tide reads shore, **instantly and without trying**. People feel gathered in your presence before you have said a word — colleagues confide in you, strangers hand you their sorrows on trains. The shell is real too, and it is not a failure of openness. It is **architecture you built for good reasons**, and it has kept tender things alive.\n\nThe practice is checking, now and then, that the shell is a door and not a wall. Attunement flowing only outward becomes a kind of hiding. So name one need out loud this week — small is fine — and let someone meet it imperfectly. **You are allowed to be the one held**, not only the one holding. The people who love you have been waiting for the invitation."
  },
  {
    title: "Rising in Leo",
    body: "Warmth is your handshake. With the Sun ruling your rising, you enter rooms the way morning enters a kitchen, and people turn toward it whether they meant to or not. This is not vanity — it is **a talent for making others feel more possible**, because your visible delight in being yourself gives everyone nearby quiet permission to be bigger too. You were built to be witnessed, and there is nothing shallow about that need; fire has always required air.\n\nThe growth edge lives in the unwatched hours: learning that **you are still radiant when nobody is looking**, that your worth does not switch off with the stage lights. Practice doing one generous, creative thing in complete privacy and letting it count. Your permission is simple and total: **take up the room you actually take up.** Shrinking never made anyone else taller."
  },
  {
    title: "Rising in Virgo",
    body: "You meet the world already noticing — the crooked frame, the word that almost fits, the small kindness everyone else walked past. Mercury rules your rising and is exalted in this sign, so your perception is not just quick but **precise in a way that borders on devotion**. Usefulness is your first language of love: you show care by fixing, refining, remembering the detail nobody asked you to hold. It is a genuine and undervalued art.\n\nThe edge is letting yourself be seen mid-process, not only once the thing is polished. The same blade that sharpens into self-criticism can soften into craft, and **craft forgives drafts**. Practice sharing something unfinished with one safe person and surviving it. Your permission: **you are lovable at eighty percent** — at forty, even. The people worth keeping never needed the perfect version. They needed you, annotated and in progress."
  },
  {
    title: "Rising in Libra",
    body: "You arrive tuned to a room's balance and adjust for it without thinking. With Venus ruling your ascendant, grace is your first language: people find you easy to meet, hard to ruffle, and quietly essential to any peace that holds. Your gift is real — you can feel **the exact weight that will level a tilted situation** — and it makes you the person both sides trust. But accommodation has a cost when it edits you out of your own scenes.\n\nThe practice is stating a preference before you have polled the room. Start small: the restaurant, the film, the honest no. **Your wanting will not break the peace** — it will make the peace honest, which is the only kind that lasts. You have permission to be a full participant in your own life, not its gracious host. **Beauty includes you.** Build accordingly."
  },
  {
    title: "Rising in Scorpio",
    body: "You enter quietly and miss nothing. With Mars as your traditional ruler working underground, a Scorpio ascendant meets the world with **a held gaze and a closed hand**, revealing itself in layers, on its own schedule. People sense your depth long before you confirm it, and the ones who earn your trust discover it is total — a loyalty with no expiration date. Privacy, for you, is not secrecy. It is **sovereignty over your own becoming**, and anyone who has had to protect a truth while it grew understands exactly why.\n\nThe growth edge is timing: letting a few chosen people earn access sooner, before the fortress finishes its walls. Disclosure, practiced deliberately, is not exposure — it is strength choosing its witnesses. Try telling one trusted person one true thing a season early. **What survives being seen becomes unshakable.**"
  },
  {
    title: "Rising in Sagittarius",
    body: "You greet the world like it owes you a good story, and mostly it delivers. With Jupiter ruling your rising, openness is your first move: candor, humor, a visible appetite for whatever is over the next hill. Rooms feel bigger with you in them because **your faith in possibility is contagious** — not naïve, but load-bearing. You have a knack for arriving in the middle of someone's stuck chapter and reminding them the book is longer than this page.\n\nYour work is staying for the middle chapters of your own story, not just the bright beginnings. The horizon will keep — it always does — while the thing in front of you ripens only if tended. Practice finishing one pursuit all the way to its unglamorous end. **Commitment is not a cage for you; it is a longer journey in one direction**, and that is the adventure you have not fully tried yet. **Depth is a distance too.**"
  },
  {
    title: "Rising in Capricorn",
    body: "Composure meets the world a beat before your warmth does. With Saturn ruling your ascendant, you carry **a quiet authority people trust with real things** — plans, secrets, weight. You were likely called an old soul early, handed responsibility before you asked for it, and you have been growing younger ever since, which is Saturn's strange mercy: the life gets lighter as you go. What looks like reserve is actually care taken seriously.\n\nThe growth edge is letting the deadpan wit and the tenderness out sooner — they are the fastest bridges you have, and people are hungrier for them than you think. And hear this plainly: **you do not have to earn your rest with suffering.** The ledger is not real. Practice one unproductive pleasure a week, logged nowhere, justified to no one. **The mountain will still respect you in the morning.**"
  },
  {
    title: "Rising in Aquarius",
    body: "You watch the world from one honest step outside it before joining in. With Saturn as your traditional ruler, an Aquarius ascendant reads as original without effort, because your angle on things is simply not the common one — and that angle is **an inheritance, not an accident**. People who grow up outside the standard scripts often develop exactly this: the clear sight of the observer, the loyalty to principles over crowds. Others come to you for the view, and the view is good.\n\nThe invitation is to come down from it sometimes and be plainly, warmly among — to let belonging happen without treating it as assimilation. **You can join without dissolving.** Practice choosing one gathering, one group, one person, and showing up as a member rather than a witness. Your difference does not evaporate in company. **It becomes useful there.**"
  },
  {
    title: "Rising in Pisces",
    body: "The membrane between you and the world is thin, and that is your instrument, not your flaw. With Jupiter as your traditional ruler, Pisces rising absorbs the feeling of a place before its facts arrive; people often cannot say why they trust you so quickly, only that they do. You are **porous by design** — a gift for artists, healers, and anyone whose work is knowing what a room actually needs. Your softness reads as welcome because it is one.\n\nThe practice is boundaries, and it helps to reframe them: a boundary is not a betrayal of your openness — **it is the maintenance that keeps the welcome open**. Untended, porousness becomes flooding. So learn where you end, not to shut others out but to have a self to offer. **Discernment is a form of devotion.** The sea has a shore, and the shore is why anyone can visit."
  }
];

export const MOON_NAKSHATRA: Interpretation[] = [
  {
    title: "Moon in Ashwini",
    body: "Your Moon opens the zodiac at a gallop. Ashwini's symbol is the **horse's head**, and its presiding deities are the Ashvins — twin physicians who ride in at dawn, arriving before anyone thought to call for help. That is your emotional signature: you recover fast, forgive fast, and your instinct to mend what hurts in other people fires before the request is made. There is a bright, **deva-natured swiftness** to your inner life; feeling moves through you like light over open country, and stagnation troubles you more than difficulty ever has.\n\nThe practice this star asks for is deliberate slowness — not punishment, but deeper medicine. **Begin your mornings with movement before words**: walk, stretch, meet the first light the way the twins do, then let one act of help each day be quiet, unhurried, unannounced. Speed is your gift. Choosing when not to spend it is your mastery."
  },
  {
    title: "Moon in Bharani",
    body: "Bharani's symbol is the **womb**, and its deity is Yama — not death as ending, but death as the keeper of thresholds, the one who ensures every passage is honored. Your Moon can therefore hold what most people flee: grief, desire, hard truths, the whole weight of things being born and things completing. The elephant is this star's animal, and you carry its temperament — **slow to anger, impossible to move once resolved**, tender toward the small. Creative heat runs fierce in you, and it gestates in the dark before it shows.\n\nThe practice is threshold-keeping. Once a month, sit with one ending — a habit, a season, a version of yourself — and thank it formally before letting it go. **Honor Yama by keeping one small vow exactly as spoken.** What you are growing does not owe anyone an early arrival, and neither do you."
  },
  {
    title: "Moon in Krittika",
    body: "You feel in clean lines. Krittika's symbol is the **razor's edge and the flame**, its deity is Agni, god of fire, and your Moon carries both: you can burn away what is false in a conversation before most people notice it was there. Yet remember what this star is actually famous for — the Krittikas, the Pleiades, **nursed the god of war as their own child**. Your sharpness exists in service of protection. The cut and the cradle are the same instinct wearing different clothes.\n\nThe practice is tending fire deliberately so it never has to tend itself. **Light a lamp or candle at dusk** and sit with it for a few breaths; cook for someone regularly, since feeding people is Agni's oldest ritual. Aim the blade at problems, never at persons — including the one in the mirror — and keep the hearth warm for everyone who finds it."
  },
  {
    title: "Moon in Rohini",
    body: "The Moon is exalted in Rohini and it shows: this is the placement of **things ripening exactly as they should**. The star's symbol is the ox-cart laden with harvest, its deity is Prajapati, the creator himself, and the story says the Moon loved Rohini best of all his wives — so your feeling nature savors: food, beauty, affection, the slow fattening of good things. You draw people in like a lit window at dusk, and whatever you tend, grows. The serpent is this star's animal: **magnetic, patient, close to the earth**.\n\nThe tender spot is possessiveness — love holds best when the hand stays open. As practice, keep something growing: a plant, a sourdough, a garden bed, and on Monday evenings offer the Moon something lovely — flowers, milk, a moment of stillness. **Tend without gripping**, and abundance stops being something you guard and becomes something you host."
  },
  {
    title: "Moon in Mrigashira",
    body: "Your Moon is a **deer at the forest's edge**: gentle, alert, always scenting something finer just beyond the clearing. That is Mrigashira's literal symbol — the deer's head — and its deity is Soma, the Moon-god and the nectar of immortality itself, which explains the shape of your longing: you are not chasing things, you are chasing **the taste of the sublime**, in ideas, places, people, the perfect phrase. The search itself nourishes you; a life without a quest reads to you as a room without windows.\n\nThe practice is learning to recognize arrival. When you have found a good meadow, graze a while before scanning the treeline. **Walk in the evening under the visible moon** when you can, and end the day with something sipped slowly — warm milk, tea, sweetness taken without hurry — a small rite of Soma. The nectar is sometimes already in the cup."
  },
  {
    title: "Moon in Ardra",
    body: "An Ardra Moon feels weather move through it. The star's symbol is the **teardrop** — or the diamond, for they are the same shape — and its deity is Rudra, the howling storm, the wild early form of Shiva who destroys precisely so the air can come clean. You feel more than most people and understand more because of it; your griefs are not malfunctions but **rain that real growth has always required**. After your storms, the view is scrubbed and honest, and what you rebuild is truer than what stood before.\n\nThe practice is honoring the storm instead of apologizing for it. When a hard feeling has passed through, **offer water** — pour some at a plant's roots, stand in the rain a moment, wash your face slowly and deliberately. Rudra is soothed by acknowledgment, not suppression. Your tears are the teardrop becoming the diamond. Let them finish their work."
  },
  {
    title: "Moon in Punarvasu",
    body: "Punarvasu means **the return of the light**, and your Moon carries that promise like a spare key. The symbol is a quiver of arrows — what is shot forth comes back to be used again — and the deity is Aditi, the boundless mother of the gods, whose lap is the open sky itself. So you begin again with uncommon grace: losses do not stay losses long in your hands, homes can be rebuilt anywhere, and **people borrow hope from you** the way neighbors borrow sugar.\n\nThe practice is keeping a portion of that renewal for yourself. Make a small ritual of return: the same cup each morning, the same chair, the same walk — a fixed point that says the light comes back here first. When something lost is restored to you, **name it aloud in gratitude to the wide sky**. Aditi hears. Boundlessness begins with noticing."
  },
  {
    title: "Moon in Pushya",
    body: "The sages called Pushya the most nourishing of the twenty-seven stars, and your Moon proves them right daily. Its symbol is the **cow's udder and the opening lotus**, its deity is Brihaspati, priest and teacher of the gods — so your care is not just warm but wise: you feed people literally, emotionally, and with counsel that lands. Folks arrive at your table hungrier than they knew. The goat is this star's animal, **sure-footed on ground that would turn others back**, and your steadiness is exactly that kind.\n\nThe one discipline Pushya asks: let yourself be tended too, without earning it first. As practice, **cook a pot of something generous and deliberately keep a portion for yourself** — first serving, not last. Offer milk or white flowers on Thursdays, Brihaspati's day, and let one person feed you this month. Nourishment that only flows outward eventually runs the well dry."
  },
  {
    title: "Moon in Ashlesha",
    body: "An Ashlesha Moon sees underneath. The symbol is the **coiled serpent**, and the presiding deities are the Nagas — the wise snakes who guard treasure at the roots of the world. You sense what coils beneath the surface of people and situations: motives, fears, the sentence not being said. That penetrating gaze can heal or entangle depending on the intention it is paired with, and you have likely felt both edges. There is also the serpent's other secret, the one people forget: **snakes are the only creatures who must shed to grow**.\n\nSo make shedding your practice. Seasonally, write down the skin you have outgrown — a role, a resentment, an old defense — and release the page: burn it safely, bury it, tear it into water. Pair it with slow **serpent breath: long exhales, longer than the inhales**. Used to free people, starting with yourself, your sight becomes **rare and genuine medicine**."
  },
  {
    title: "Moon in Magha",
    body: "Your Moon sits on ancestral ground. Magha's symbol is the **royal throne**, and its deities are the Pitris — the ancestors themselves, everyone whose living made your living possible. You feel lineage the way others feel weather, and dignity matters to you at the bone level: not vanity, but the knowledge that you are a link in a chain and the chain is watching with love. And hear this — **lineage includes the chosen kind**. The elders of your communities, the ones who survived so you could be legible: they are your Pitris too.\n\nThe practice is remembrance. Once a week, **speak the names of your ancestors aloud** — blood, chosen, or both — and light a small lamp for them. Offer the first bite or the first pour. You are meant to inherit and to hand down. **Rule your corner of the world the way you wish it had been ruled for them.**"
  },
  {
    title: "Moon in Purva Phalguni",
    body: "This Moon knows rest is not a reward but a birthright. Purva Phalguni's symbol is the **front legs of the bed** — the swinging hammock, the couch of pleasure — and its deity is Bhaga, god of delight and good fortune, distributor of the portion that is rightfully yours. You have a genius for enjoyment: beauty, romance, art, the afternoon deliberately unscheduled, and your ease relaxes whole rooms. In a world that treats rest as something to be earned by depletion, **your capacity for pleasure is quietly radical**.\n\nThe art is pairing delight with follow-through so the party has somewhere to land. As practice, **appoint one small luxury each Friday** — Venus's day and this star's ruler — and take it without guilt, as an offering to Bhaga rather than a theft from productivity. Then finish one thing you started while happy. **Joy that completes itself becomes fortune.**"
  },
  {
    title: "Moon in Uttara Phalguni",
    body: "An Uttara Phalguni Moon is the friend people call from the airport at two in the morning. The symbol is the **back legs of the bed** — the support that bears the weight — and the deity is Aryaman, keeper of alliances, hospitality, and honorable contracts. You take loyalty seriously the way some people take religion: your word is architecture, and people build lives on it. There is a solar steadiness underneath your kindness, **generosity with a spine**, and the ox's patient temperament: you pull the load all the way home.\n\nThe practice is hospitality made rhythmic rather than reactive. **Choose two or three bonds and tend them on schedule** — the standing call, the remembered date — because Aryaman is honored by faithfulness in small forms. Greet the morning sun when you can. And choose commitments carefully, knowing your nature: **you are constitutionally unable to abandon them**, so let them deserve you."
  },
  {
    title: "Moon in Hasta",
    body: "Your Moon lives in the hands. Hasta's symbol is the **open palm**, and its deity is Savitar, the golden-handed sun of dawn who sets all things in motion; the star grants skill you can watch — the deft fix, the quick craft, the joke placed exactly where it lands. You are resourceful in ways that look like luck but are actually **dexterity of heart and hand working together**. What you handle improves. People pass you their tangled things, literal and otherwise, because your fingers seem to remember solutions your mind has not met yet.\n\nThe practice is daily making. **Touch one thing into being every day** — bread, a mended hem, a tidied drawer, six honest lines of writing — and offer the work to the morning light, Savitar's hour, when your hands are surest. When a problem seems too big to hold, **break it into what one pair of hands can do today.** That is not a smaller life. It is how yours works."
  },
  {
    title: "Moon in Chitra",
    body: "Chitra is the **bright jewel**, and your Moon cuts its whole life to catch light. The deity here is Tvashtar — Vishvakarma, the celestial architect who builds the gods their weapons and palaces — so your eye for design is not decoration but structure: you see how rooms, sentences, identities, and futures are made, and how they could be made better. The tiger is this star's animal, and it shows in your temperament: **elegant, self-possessed, unwilling to be rushed through your own becoming**. You may have built yourself more deliberately than most people ever build anything.\n\nThe practice is honoring the architect with material. **Keep one corner of your home composed like an offering** — fresh flowers, clean lines, an object you love — and rework it with the seasons. Make something with visible craft each month. Build things worthy of your taste, and **never apologize for having taste**. It is your blueprint showing."
  },
  {
    title: "Moon in Swati",
    body: "A Swati Moon bends and does not break. The symbol is the **young shoot swaying in wind**, and the deity is Vayu, the wind itself — breath, movement, the sacred air that goes everywhere and belongs nowhere. You have learned to move with forces larger than you while keeping your rooting anyway, and independence is your quiet religion: you flourish when nobody is steering, and you can make a home out of open sky. What looks like restlessness is actually **an instinct for self-determination** that has probably saved you more than once.\n\nThe practice belongs to the breath, Vayu's own element. **Take your breathing outside daily** — even five minutes of wind on skin, long slow exhales, counts as prayer here. And let the wind carry you toward people sometimes, not only away: the shoot that sways alone still grows in a field. **Freedom shared is still freedom.** It is just warmer."
  },
  {
    title: "Moon in Vishakha",
    body: "Your Moon can see the archway from miles off. Vishakha's symbol is the **triumphal gate** — some say the potter's wheel — and its deities are Indra and Agni together: sovereign will and sacred fire pointed at a single aim. When you fix on a goal, obstacles start negotiating. This is the star of purpose, and its tiger temperament gives you **patience that is really just slow ferocity**: you will circle a summit for years and still take it. Victory genuinely suits you, and people feel braver marching next to you.\n\nThe practice is presence along the way, because a life spent entirely at the finish line is a life mostly unlived. **Mark the milestones, not just the summit**: at every halfway point, stop, pour a little water on the earth, and name what the road has already given you. The gate will still be there. **You are allowed to taste the mile you are in.**"
  },
  {
    title: "Moon in Anuradha",
    body: "An Anuradha Moon blooms where it is planted, even in difficult soil. The symbol is the **lotus rising through mud**, and the deity is Mitra, god of friendship, whose whole divine job is keeping bonds alive across distance and difference. So your genius is devotion that travels: you build loyalty between people, cultures, and positions that should not get along but somehow do around you. The deer is this star's animal — **gentle, watchful, easily underestimated** — and like the deer, your softness has never once meant weakness.\n\nThe practice is friendship kept as a discipline. **Reach across one distance regularly** — the far-flung friend, the estranged-but-loved, the person unlike you — and let the reaching be its own devotion, expecting nothing back. Tradition says success finds Anuradha far from where it started, so do not fear the leaving. **The mud you grew through is not your shame. It is your root system.**"
  },
  {
    title: "Moon in Jyeshtha",
    body: "Jyeshtha means **the eldest**, and your Moon carries the eldest's mandate whether or not you were born first: protect, provide, hold the umbrella over whoever is getting rained on. The star's symbols are the **circular amulet and the umbrella** — emblems of rank worn in service — and its deity is Indra, chief of the gods, who won his throne and then had to learn what thrones are actually for. Authority finds you early and often. The weight is as real as the honor, and you have felt both.\n\nThe practice is letting seniority soften into shelter rather than harden into control. **Give protection quietly** — the anonymous help, the door held without ceremony, the power spent on someone who can never repay it. That is Indra at his best. Guard against the eldest's loneliness by letting one or two people out-rank you in your own heart. **Even the chief needs somewhere to set the crown down.**"
  },
  {
    title: "Moon in Mula",
    body: "A Mula Moon digs. The name means **root**, the symbol is a bundle of roots tied together, and the deity is Nirriti — goddess of dissolution, the one who un-makes what was never sound. Your feeling nature will not settle for the surface version of anything: you pull at foundations until the real cause comes up in your hands, in yourself most of all. What you uproot does not grow back, which is precisely the point. This is **demolition in service of truth**, and it is holy work, though rarely comfortable for bystanders.\n\nThe practice is grounding the digger. **Sit directly on the earth regularly** — grass, sand, stone — and eat root vegetables in season, small homage to the ground that holds you. Before uprooting anything, ask once: is this actually dead, or just dormant? **Aim your power at what is genuinely finished**, and treat what is still living — including your tenderest hopes — with a gardener's mercy."
  },
  {
    title: "Moon in Purva Ashadha",
    body: "They call this the **invincible star**, and your Moon believes it. Purva Ashadha's symbol is the winnowing fan, which separates grain from husk by throwing everything into the air, and its deities are Apas, the sacred waters — so you run on early conviction and irresistible flow: you declare the victory first, then rise to meet your own announcement, and your persuasion moves around every no like a river around stones. The monkey is this star's animal, and its temperament is yours: **quick, clever, impossible to keep discouraged**.\n\nThe practice is letting water witness your word. **Speak your commitments near water** — a river, the ocean, even a filled bowl — and then let follow-through move the way water does: not by force, but by never stopping. Offer a little water to the earth when a promise is kept. You inspire before you prove; that is your sequence, not your flaw. **Just make sure the proving always arrives.**"
  },
  {
    title: "Moon in Uttara Ashadha",
    body: "Your Moon plays the long game and wins it. Uttara Ashadha means **the later victory** — the one that lasts — its symbol is the elephant's tusk, and its deities are the Vishvadevas, all the gods at once, which is why this star favors aims so worthy that heaven itself has no objection. You are slow to commit and nearly unstoppable after; the mongoose, this star's animal, is small but famously defeats serpents through **pure, patient persistence**. Your endurance is not stubbornness. It is integrity with a timeline.\n\nThe practice is the single daily step. **Choose one worthy aim and touch it every day at the same hour** — ten minutes counts — because consistency is the offering the Vishvadevas honor most. Rise with the sun when you can; this star loves the disciplined dawn. Choose summits, not hills, and forgive the years it takes. **What you build slowly, nobody can take quickly.**"
  },
  {
    title: "Moon in Shravana",
    body: "Shravana is the star of the **sacred ear**, and your Moon listens the way other people speak. Its deity is Vishnu, the preserver, whose three great steps crossed the whole universe — and your understanding crosses distances the same quiet way: through attention, study, the story heard all the way to its end. People tell you things they have never said aloud, and that is not accident; it is **your work arriving to find you**. Wisdom traditions were carried for centuries by ears like yours before anything was written down.\n\nThe practice is deep listening as devotion. **Keep a daily pocket of silence** — no input, just the world sounding — and once a week, listen to an elder or a teacher without planning your reply. Chanting, or simply humming something sacred to you, tunes the instrument. **What you truly hear, you preserve.** That is Vishnu's own job description, and you share it."
  },
  {
    title: "Moon in Dhanishta",
    body: "A Dhanishta Moon keeps time for everyone in earshot. The symbol is the **drum** — the mridanga that the gods themselves dance to — and the deities are the eight Vasus, elemental gods of abundance: earth, wind, fire, water, sky, sun, moon, stars, all lending their wealth to whatever you commit to. So your gift is rhythm in the widest sense: music, timing, the felt pulse of when to move and when to lie fallow. The lion is this star's animal, and it gives your generosity **a confident, unhurried gait**.\n\nThe practice is rhythm made deliberate. **Keep a beat somewhere in your week** — a drum, a playlist you move to, footsteps counted on a walk — as an offering to the pulse that runs through you. And play in ensembles, not just solos: give something away each month, since the Vasus multiply what circulates. **Your beat is what lets other people find theirs.**"
  },
  {
    title: "Moon in Shatabhisha",
    body: "They call Shatabhisha the **hundred healers**, and your Moon holds all of them behind a veil. Its symbol is the empty circle — the container, the boundary around sacred space — and its deity is Varuna, lord of the cosmic waters and keeper of the deepest laws, the ones that operate whether or not anyone is watching. You are private, perceptive, and drawn to what actually fixes people: medicine, systems, hard truths that sting before they cure. Solitude is not your exile. **It is your clinic**, where you refill what the world drains.\n\nThe practice is water taken seriously. **Make bathing a small ceremony** once a week — salt, intention, the day rinsed off deliberately — and drink water like it matters, because for you it does; Varuna honors those who honor his element. Then set a return time from every retreat and keep it. **The healing was never meant for an audience of one.**"
  },
  {
    title: "Moon in Purva Bhadrapada",
    body: "This Moon runs hot beneath a calm face. Purva Bhadrapada's symbols are the **sword and the two-faced figure** — one face turned toward the ordinary world, one toward the fire behind it — and its deity is Aja Ekapada, the one-footed goat of flame, an intensity that stands on a single point and burns straight upward. You are built for transformation: yours first, then everyone's within radius. The same heat that can lift a whole life toward meaning can scorch it chasing extremes, and you have likely felt the difference in your own hands.\n\nThe practice is giving the flame a wick. **Sit with a single candle** some evenings and let your eyes rest on it — one flame, one point, the mind gathering instead of scattering. Choose one purpose per season and feed it your intensity on purpose, as tapas, disciplined offering. **Fire with a hearth warms a house. Fire without one is just weather.**"
  },
  {
    title: "Moon in Uttara Bhadrapada",
    body: "An Uttara Bhadrapada Moon is deep water that has made peace with its own dark. The deity is Ahir Budhnya, the **serpent of the depths**, who holds the foundations of the world from underneath without ever needing credit for it, and the symbol — the back legs of the funeral cot — speaks of the strength that bears what others cannot look at. Your stillness gets mistaken for detachment until somebody needs it; then it is **the steadiest thing in the room**. The cow is this star's animal: patient, giving, sacred in her ordinariness.\n\nThe practice is honoring the depths on purpose. **Take real rest as a discipline** — yoga nidra, long exhales, the lying-down kind of prayer — and sit near deep water when you can, letting it do the talking. Wisdom ripens slowly in you, and that is not lateness. **The depth is the gift.** Let it finish steeping."
  },
  {
    title: "Moon in Revati",
    body: "Revati closes the circle, and your Moon carries the sweetness of safe arrival. The symbol is the **fish swimming in the sea** — some say the drum that keeps time for the road — and the deity is Pushan, the gentle sun of journeys, protector of travelers, herds, and lost things, the god who makes sure everyone gets home. So you shepherd: people, animals, projects nearing their end, souls in transition, all with a gentleness that costs more than you show. The elephant, this star's animal, lends you its **deep memory and its wide, patient heart**. Endings trust you.\n\nThe practice is care with a circuit back to you. **Feed an animal regularly** — a pet, the birds, the neighborhood stray — as living homage to Pushan, and bless the traveler in yourself before every departure, even small ones. Then let someone accompany you for once. **Even the shepherd deserves a shepherd.**"
  }
];

export const DASHA_LORD: Record<string, Interpretation> = {
  ketu: {
    title: "Ketu Mahadasha",
    body: "Ketu chapters loosen your grip on the script. For seven years, ambition goes quiet and meaning gets loud: attachments lose their charge one by one, statuses stop tasting like anything, and the essential turns strangely luminous. It can feel like wandering — sometimes like grieving a self that dissolved without asking permission — but what is actually happening is **distillation**. Ketu is the headless one, done with appearances; his years show you what remains of you when the audience goes home, and that remainder is **the realest thing you own**.\n\nThe way through is lightness. Travel light, literally and otherwise: simplify the rooms, the schedule, the story you tell about yourself. Let what leaves, leave, and resist rehiring old identities out of loneliness. Meditation, retreat, and unglamorous service all ripen beautifully now. **What survives a Ketu period was never yours to lose** — and knowing that is the treasure the chapter came to deliver."
  },
  venus: {
    title: "Venus Mahadasha",
    body: "The Venus mahadasha is the long, luxurious chapter — twenty years, the longest of them all — where relationship, beauty, and comfort move to the center of the story. Love matters more here in every form it takes: partners, chosen family, friendships that function like marriages, the romance of a life arranged to please you. Art, home, the body's pleasures, and the making of lovely things all bear fruit now. **Your taste becomes a life-building tool**, and what you find beautiful quietly determines where you end up.\n\nBecause twenty years is a whole era, the practice is intentionality: **enjoy it on purpose, not by accident**. Refine what you love rather than accumulating what you are told to want. Choose your people the way a curator chooses what hangs in the light. Venus rewards devotion over consumption — to a craft, a garden, a person, a self. **Pleasure, taken seriously, is a discipline**, and this is your apprenticeship in it."
  },
  sun: {
    title: "Sun Mahadasha",
    body: "The Sun's chapter is the shortest — six years — and it works like a lens: everything narrows toward clarity. These years push you toward the center of your own life, sometimes gently and sometimes by removing every place to hide. Visibility rises; so does responsibility with **your name attached to it**. Work wants your authorship now, not your assistance. Health, confidence, and purpose tend to rise together in this period the moment you stop dimming to keep other people comfortable — a habit the Sun period has no patience for.\n\nThe curriculum is **sovereignty without arrogance**: shining because it is yours to do, not to eclipse anyone. Watch the relationship with authority — bosses, parents, institutions — because the Sun period often asks you to stop orbiting and start radiating. Morning light, honest ambition, and one pursuit that is unmistakably yours are the practices. **Warm the people in your orbit**, and the shine holds."
  },
  moon: {
    title: "Moon Mahadasha",
    body: "A Moon mahadasha turns life inward and homeward for ten years. Feelings run closer to the surface, and so does intuition; care, family in every configuration, belonging, and the state of your inner weather all take the foreground. The outer résumé may grow more slowly in this chapter, but **the inner architecture gets rebuilt entirely** — how you soothe yourself, whom you let close, what home actually means when you get to define it. The public may also find you softer and trust you more; the Moon draws people the way tide draws water.\n\nThe curriculum is simple to state and lifelong to learn: **nurture and be nurtured**. Tend the vessel — sleep, water, the rooms you live in, the rhythms of your month — and the decade tends you back. Keep gentle company. Let your moods be information rather than indictments. **A well-kept inner life is the harvest here**, and it outlasts the dasha."
  },
  mars: {
    title: "Mars Mahadasha",
    body: "Mars years bring heat and traction — seven of them, and they move fast. This chapter favors decisive action: the move you have deferred, the launch, the discipline finally kept, the boundary finally drawn out loud. Your courage gets tested in ways that build **genuine, load-bearing strength**, and your body wants to be part of the story now: training, effort, the satisfaction of physical work. Conflicts may spark more easily; handled cleanly and directly, they clear air that politeness had been letting go stale for years.\n\nThe practice is aim. Mars scattered is temper; Mars gathered is **one worthy campaign at a time**, prosecuted with full attention until won. Move your body most days — the period runs cleaner when the engine gets driven. Fight fair, finish what you draw the sword for, and protect someone weaker than you while you are strong. **You will be startled by what gets built.**"
  },
  rahu: {
    title: "Rahu Mahadasha",
    body: "Rahu's mahadasha is the hungry chapter: eighteen years of appetite for more life — new worlds, bigger stages, foreign territory literal and figurative, the unfamiliar thing you cannot stop reaching for. Rahu is the eclipse-maker, the outsider who crashed the gods' table and won immortality anyway, which makes this **the outsider's power period**: whatever the standard script excluded you from, these years give you the audacity to enter sideways and take a seat. Everything accelerates, including the lessons, and the wanting itself becomes a kind of engine.\n\nThe practice is staying awake at the wheel. Ambition here is fuel, not flaw — but **keep checking that the wanting is actually yours**, because Rahu borrows desires as easily as he grants them. Ground the acceleration in a body and a home base; keep one or two people who knew you before. **Ride it awake, and it carries you far from small.** Ride it asleep, and it just carries you."
  },
  jupiter: {
    title: "Jupiter Mahadasha",
    body: "The Jupiter chapter expands whatever you water, for sixteen years. Teachers arrive — some with titles, most without — doors open that you did not knock on, and your sense of purpose finally gets room to stretch to its full height. These years favor study, mentorship in both directions, children and creative offspring of every kind, philosophy, faith, and **generous risks taken in the direction of meaning**. Luck looks luckier now mostly because you are finally saying yes at the rate life is offering.\n\nThe practice is matching inner growth to outer growth, because expansion without wisdom just makes a bigger version of the same problems. **Grow in understanding alongside the growth in fortune** — that is what makes it hold. Study something deeply. Teach what you know before you feel ready. Give a percentage of everything away as a standing habit. **Grace multiplies where gratitude keeps the books**, and Jupiter audits kindly but thoroughly."
  },
  saturn: {
    title: "Saturn Mahadasha",
    body: "Saturn's mahadasha is the long apprenticeship — nineteen years of structure, patience, and honest work. It is not the punishment its reputation suggests; it is **the only period that pays in permanent currency**: mastery, endurance, self-respect earned the slow way, foundations that hold weight for the rest of your life. Whatever is flimsy — habits, arrangements, half-true stories about yourself — gets pruned, and the pruning can ache. But notice what Saturn never touches: anything real. The real things come through these years reinforced.\n\nThe practice is befriending the teacher instead of dodging him. Keep your word, especially to yourself, in small measurable ways. Show up on schedule for the work that matters; **consistency is the entire liturgy here**. Honor your elders and your limits, rest without guilt, and serve someone whose struggle is heavier than yours. The years feel weightier as you live them and leave you **unshakably built** — the kind of built that no one can repossess."
  },
  mercury: {
    title: "Mercury Mahadasha",
    body: "The Mercury chapter quickens the mind's whole economy for seventeen years. Ideas, conversations, skills, and trade multiply; these years favor learning fast, writing it down, teaching it forward, and connecting people and things that improve one another. Your **wit becomes infrastructure** — the newsletter, the practice, the network, the body of work that others end up standing on. Mercury is the planet that moves between worlds and translates as it goes, so lives that cross categories flourish especially well under this dasha: the multilingual, the multi-hyphenate, the ones fluent in more than one way of being.\n\nThe practice is depth of inquiry. **Stay curious past the first answer** — Mercury's shadow is cleverness that skims, and the remedy is the second question, the source checked, the skill drilled past competence into craft. Keep a notebook like it is a bank account. Speak precisely and kindly, since your words carry further now. **The chapter compounds like good interest**, and the principal is attention."
  }
};
