/**
 * Shared learning data: the glossaries and the nakshatra legend, used by
 * the Codex and by each system tab's Learn section.
 */
export const GLOSSARY: [string, string][] = [
  ["Angular, succedent, cadent", "The three strengths of houses. Angular houses (1st, 4th, 7th, 10th) sit on the chart's hinges — planets there act visibly and soon. Succedent houses (2nd, 5th, 8th, 11th) gather and stabilize what the angles set in motion. Cadent houses (3rd, 6th, 9th, 12th) are the in-between rooms: preparation, service, study, retreat — planets there work sideways, through process rather than declaration."],
  ["Applying & separating", "The direction of an aspect in time. An applying aspect is still tightening — the faster planet is closing the distance, and the matter is still unfolding, still negotiable. A separating aspect has already perfected and is loosening — the conversation happened, and what remains is its afterglow or aftermath. Traditional astrologers weighed applying aspects far more heavily for what is to come."],
  ["Ascendant (rising)", "The exact degree of the zodiac rising over the eastern horizon at the moment and place of your birth. It is the most time-sensitive point in the chart — shifting roughly one degree every four minutes — which is why an accurate birth time matters. The Ascendant sets the wheel of houses, names your rising sign, and describes the instrument through which everything else in the chart plays: your approach, your arrival, the face the world meets first. Its ruler becomes the captain of the whole chart."],
  ["Ayanamsa", "The measured angle between the tropical zodiac (seasons) and the sidereal zodiac (stars) — currently about 24 degrees and slowly growing, because Earth's axis wobbles over a ~25,800-year cycle (the precession of the equinoxes). Every Vedic chart subtracts an ayanamsa from tropical positions; Lahiri is the official Indian convention and our default, with Raman, Krishnamurti, and Fagan–Bradley offered for other lineages."],
  ["Antardasha (bhukti)", "The sub-period inside a Vimshottari mahadasha. Each major chapter subdivides into nine smaller ones in the same planetary order, each lasting a proportional share. The antardasha describes the sub-plot: a Venus year inside a Saturn decade feels different from a Mars year inside it. Timing in Jyotish is read maha + antar together, like a key signature and the phrase being played inside it."],
  ["Benefic & malefic", "The traditional temperament of the planets. Venus and Jupiter are the benefics — they tend to ease, connect, and grow what they touch. Mars and Saturn are the malefics — they cut, test, delay, and toughen. This is weather, not morality: a well-placed Saturn builds cathedrals, and sect softens or sharpens each (Jupiter is strongest by day, Venus by night; Mars is harder in day charts, Saturn harder at night)."],
  ["Bound (Egyptian term)", "One of five unequal slices inside each sign, each governed by one of the five visible planets — never the Sun or Moon. The bounds are among the oldest layers of the dignity system; Ptolemy records the 'Egyptian' table we use, and medieval astrologers called them terms. A planet in its own bound gains quiet self-possession. Traditionally the bound lord colors the fine grain of a placement — the accent within the accent — and was consulted for physical description and life-stage rulers."],
  ["Cazimi & combust", "Two fates of a planet near the Sun. Within about 8.5 degrees, a planet is combust — burned up in the glare, its significations weakened or hidden, working unseen. But within 17 arcminutes of the Sun's exact center it is cazimi, 'in the heart of the Sun' — the king's chosen advisor, singularly empowered. The same closeness that destroys at arm's length crowns at the heart."],
  ["Decan (face)", "A ten-degree third of a sign — thirty-six faces around the wheel, each assigned a planetary ruler in the descending Chaldean order (Saturn, Jupiter, Mars, Sun, Venus, Mercury, Moon, repeating). The decans began as Egyptian star-clocks marking the hours of the night, and they survive everywhere: the tarot's thirty-six minor pip cards (2–10) are the thirty-six decans wearing costumes. The weakest dignity, and the most visual — read it for imagery, mood, and texture."],
  ["Detriment (exile)", "A planet in the sign opposite one of its domiciles — Venus in Aries, the Moon in Capricorn. The planet is a guest in a house built on values opposite its own, so its style runs against the grain of the terrain. This produces friction and also its gifts: improvisation, self-awareness, fluency earned rather than inherited. Modern practice reads detriment less as weakness than as a placement that must become conscious of itself."],
  ["Dignity (essential)", "The five-layer system measuring how resourced a planet is by zodiac position alone: domicile (its own sign), exaltation (its honored sign), triplicity (its element team), bound (its degrees), and face (its decan) — with detriment and fall as the challenged mirror states, and peregrine as the unhoused wanderer with none. Essential dignity is about intrinsic resources; how a planet is placed in houses and aspects (accidental dignity) is about opportunity."],
  ["Domicile (rulership)", "A planet standing in a sign it rules — the Sun in Leo, the Moon in Cancer, Saturn in Capricorn or Aquarius. It is in its own house with its own tools and answers to no landlord: what it signifies, it can deliver by itself. The domicile lord of any sign also 'manages' every other planet staying there — which is why the ruler of your Ascendant matters so much."],
  ["Exaltation", "The sign where a planet is received like royalty — the Sun in Aries, the Moon in Taurus, Venus in Pisces, Saturn in Libra. Abu Ma'shar calls it the planet's kingdom. Exalted planets act with elevation and confidence, sometimes with the exaggeration of a guest of honor: celebrated, slightly idealized, expected to perform the best version of themselves."],
  ["Fall (depression)", "The sign opposite a planet's exaltation — the Moon in Scorpio, Venus in Virgo, Saturn in Aries. The planet's usual method finds no applause here; its confidence runs at low tide. Tradition read this as debility, and lived experience often reads it as depth: placements in fall tend to develop unusual honesty about their own workings, strength assembled from first principles rather than inheritance."],
  ["Graha", "Sanskrit for 'seizer' — the nine 'planets' of Jyotish: Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, and the two lunar nodes Rahu and Ketu. The name is the theory: a graha is that which grips consciousness and holds it to a storyline."],
  ["Lot of Fortune", "An Arabic part cast from the three great lights of the chart — Ascendant plus Moon minus Sun by day, reversed by night. Fortune concerns the given: the body, health, livelihood, circumstance — what happens to you and through you without your asking. Hellenistic astrologers treated it as a second Ascendant for matters of fortune and counted whole-sign houses from it."],
  ["Lot of Spirit", "Fortune's deliberate twin — Ascendant plus Sun minus Moon by day, reversed at night. Where Fortune is what befalls you, Spirit is what you set in motion: will, vocation, chosen action, the life you author. Zodiacal releasing is most often counted from Spirit for career and life-direction questions."],
  ["Mahadasha", "A major planetary chapter in the Vimshottari system, lasting from 6 years (Sun) to 20 (Venus). Which chapter you begin life inside — and how far along — is seeded entirely by the Moon's nakshatra at birth. People often recognize their mahadasha changes in hindsight as the chapter breaks of their biography."],
  ["Midheaven (MC)", "The Medium Coeli — the degree of the zodiac culminating overhead at your birth. It crowns the 10th house region: public work, reputation, the visible summit of a life, and (in older texts) 'praxis' — what you do. Aspects to the MC describe what colors your public becoming."],
  ["Nakshatra", "One of the 27 lunar mansions dividing the sidereal zodiac into 13°20' segments — the Moon's nightly resting places. Each has a presiding deity, a symbol, an animal, a temperament, and a planetary lord; together they are Jyotish's oldest layer, older than the twelve signs. The Moon's nakshatra at your birth (your janma nakshatra) names your emotional habitat and seeds the entire Vimshottari timeline. Our charts give the nakshatra and pada of every planet and of the Ascendant and Midheaven."],
  ["Navamsa (D9)", "The ninth harmonic chart: each sign divides into nine padas of 3°20', which reassemble into a second complete chart. Tradition reads it for marriage and partnership, dharma, and the inner fruit of the natal promise — the D1 is the tree, the D9 the fruit hidden inside it. A planet in the same sign in both charts (vargottama) gains uncommon strength."],
  ["Orb", "The allowance around an exact aspect within which it still 'works.' A trine at exactly 120°00' is rare; within a few degrees the conversation is still audible. We default to 8° for conjunctions, oppositions and trines, 7° for squares, 6° for sextiles — tighter orb, louder aspect. The orb number shown beside each aspect is its distance from exactness."],
  ["Pada", "A quarter of a nakshatra — 3°20', the smallest commonly-read unit of the sidereal zodiac. The four padas step each mansion through a fire–earth–air–water sequence and map one-to-one onto the navamsa: knowing a planet's pada is knowing its D9 sign. Pada lords add a final grace note to any placement."],
  ["Peregrine", "A planet with no essential dignity at its degree — not in its domicile, exaltation, triplicity, bound, or face. The medieval image is a wanderer without land: improvising, borrowing, unusually shaped by whoever rules the sign it visits (its dispositor). Peregrine planets often carry the most interesting plot lines, because they must make a life rather than inherit one."],
  ["Profection", "An ancient timing wheel: each birthday, your Ascendant 'profects' one house forward, and that year takes its themes from the house reached — its sign's ruler becomes your Lord of the Year. Twelve years, full circle, begin again. Simple, old, startlingly accurate as a table of contents for the year."],
  ["Rasi (D1)", "The root chart of Jyotish — the sidereal signs exactly as they stood at birth, before any division. All the divisional charts (vargas) are derived from it, which is why it is called D1: the ground floor of the whole Vedic reading."],
  ["Retrograde", "The apparent backward motion of a planet as Earth overtakes it (or is overtaken). Nothing in the sky reverses; the geometry of viewpoint does. Tradition reads retrograde planets as internalized, revisionary, working on their own schedule — strength turned inward, themes that return for a second pass. In the chart tables retrogrades are marked ℞."],
  ["Sect", "The chart's oldest sorting: were you born with the Sun above the horizon (a day chart) or below it (a night chart)? Each sect has a team — Sun, Jupiter, Saturn by day; Moon, Venus, Mars by night; Mercury swings with its sunrise position. Planets on duty in their own sect act with more grace: the benefic of sect gives more freely, the malefic contrary to sect tests more sharply. Sect is the first thing a Hellenistic astrologer checks, because it re-weights everything else."],
  ["Sidereal zodiac", "The zodiac measured against the fixed stars themselves, used by Jyotish and by Western sidereal astrologers. Because of precession it drifts about one degree every 72 years relative to the seasons — hence the ayanamsa correction, and hence your 'Vedic sign' often being one sign earlier than your tropical one. Neither zodiac is wrong; they measure different skies."],
  ["Solar return", "The chart cast for the exact moment the Sun returns to its natal degree each year — your astrological new year, accurate to the minute. Read as a standalone chart for the year's weather, then laid over the natal chart for where it lands. The location can be cast for where you'll be on the birthday, which is why some people travel for their returns."],
  ["Station", "The moments a planet appears to stand still, pivoting between direct and retrograde motion. Stationing planets are traditionally at their most potent — a held breath in the sky. A planet stationing on one of your natal degrees marks a season that asks your full attention."],
  ["Synastry", "The astrology of relationship: two charts laid over each other, each person's planets aspecting the other's. Your Moon on someone's Ascendant, their Saturn on your Venus — synastry maps where two skies interlock, comfort, and instruct each other."],
  ["Transit", "The sky as it moves now, read against the sky you were born under. A transit is a real-time aspect from a moving planet to a natal position — the mechanism behind every honest 'what's happening right now' reading, and the engine of our Transits room."],
  ["Triplicity", "The element-team dignity: each element (fire, earth, air, water) is stewarded by three planets who trade shifts — a day ruler, a night ruler, and a participating partner. A planet in its own triplicity has allies on call: not the keys to the house, but family in the neighborhood. Dorotheus made triplicity the backbone of his whole system."],
  ["Vimshottari dasha", "The 120-year master clock of Jyotish: nine planetary chapters — Ketu 7, Venus 20, Sun 6, Moon 10, Mars 7, Rahu 18, Jupiter 16, Saturn 19, Mercury 17 — whose order is fixed and whose starting point is seeded by the Moon's nakshatra at birth. Where you begin in the wheel, and how much of that first chapter remains, is the first timing fact of a Vedic reading."],
  ["Whole-sign houses", "The oldest and simplest house system: the entire rising sign is your 1st house, the next sign your 2nd, and so on around — every house exactly one sign. Standard in Hellenistic and Vedic practice, and enjoying a modern revival. We default to whole sign for Vedic charts and Placidus for Western, with both switchable — comparing the two is half the fun."],
  ["Zodiacal releasing", "Vettius Valens' grand timing technique: beginning from the Lot of Spirit (for deeds and career) or Fortune (for body and circumstance), life unfolds in sign-ruled chapters lasting that sign's 'minor years,' each subdividing fractally into months and days. Peak chapters arrive when the releasing reaches signs angular to Fortune; the 'loosing of the bond' marks a dramatic change of storyline. Recovered from near-oblivion by the modern Hellenistic revival, it is among the most striking timing tools ever devised — your L1 chapters are already computed in the deeper chart."],
];

export const VEDIC_TERMS = new Set([
  "Ayanamsa",
  "Antardasha (bhukti)",
  "Graha",
  "Mahadasha",
  "Nakshatra",
  "Navamsa (D9)",
  "Pada",
  "Rasi (D1)",
  "Sidereal zodiac",
  "Vimshottari dasha",
]);

export /** [name, presiding deity, Vimshottari lord] in classical order. */
const NAKSHATRA_LEGEND: [string, string, string][] = [
  ["Ashwini", "The Ashvins — twin physicians of the gods", "Ketu"],
  ["Bharani", "Yama — dharma and the threshold", "Venus"],
  ["Krittika", "Agni — sacred fire", "Sun"],
  ["Rohini", "Prajapati (Brahma) — creation", "Moon"],
  ["Mrigashira", "Soma — the nectar Moon", "Mars"],
  ["Ardra", "Rudra — the storm", "Rahu"],
  ["Punarvasu", "Aditi — the boundless mother", "Jupiter"],
  ["Pushya", "Brihaspati — priest of the gods", "Saturn"],
  ["Ashlesha", "The Nagas — serpent wisdom", "Mercury"],
  ["Magha", "The Pitrs — the ancestors", "Ketu"],
  ["Purva Phalguni", "Bhaga — pleasure and portion", "Venus"],
  ["Uttara Phalguni", "Aryaman — patronage and vows", "Sun"],
  ["Hasta", "Savitr — the golden hand of the Sun", "Moon"],
  ["Chitra", "Tvashtar (Vishvakarma) — divine architect", "Mars"],
  ["Swati", "Vayu — the wind", "Rahu"],
  ["Vishakha", "Indra-Agni — purpose with power", "Jupiter"],
  ["Anuradha", "Mitra — friendship and alliance", "Saturn"],
  ["Jyeshtha", "Indra — the elder's crown", "Mercury"],
  ["Mula", "Nirriti — the root and its undoing", "Ketu"],
  ["Purva Ashadha", "Apas — the invincible waters", "Venus"],
  ["Uttara Ashadha", "The Vishvedevas — universal principles", "Sun"],
  ["Shravana", "Vishnu — the listener's three steps", "Moon"],
  ["Dhanishta", "The Vasus — abundance in motion", "Mars"],
  ["Shatabhisha", "Varuna — the hundred healers", "Rahu"],
  ["Purva Bhadrapada", "Aja Ekapada — the one-footed fire", "Jupiter"],
  ["Uttara Bhadrapada", "Ahirbudhnya — serpent of the deep", "Saturn"],
  ["Revati", "Pushan — shepherd of safe passage", "Mercury"],
];
